### ISSUE TITLE
HEP over TCP not working

### ISSUE THREAD

**Issue by mkrokosz** [sipcapture/captagent#100]
When configuring a transport_hep profile with capture-proto as "tcp", the behavior is inconsistent.  The reason looks to be because the "type" field in hep_connection_t in transport_hep.h is defined as a BOOL but it is being set to "1" when proto is udp and "2" when proto is tcp.  The fix looks to be as simple as changing the type from "BOOL" to "int".

**Comment by adubovikov** [comment]
sorry, but i don't see it here

https://github.com/sipcapture/captagent/blob/master/src/modules/transport/hep/transport_hep.c#L1196-L1202

we use strncmp and call different functions for init sockets....

**Comment by mkrokosz** [comment]
See here..

https://github.com/sipcapture/captagent/blob/master/src/modules/transport/hep/transport_hep.c#L962

https://github.com/sipcapture/captagent/blob/master/src/modules/transport/hep/transport_hep.c#L636

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/601b2904ead63574ab3f700f55fe71ea4ac39237

fixed. Thank you!.
