### ISSUE TITLE
HEP over TCP not reconnecting

### ISSUE THREAD

**Issue by mkrokosz** [sipcapture/captagent#101]
If the HEP server is restarted, the captagent is catching SIGPIPE but not doing anything to re-establish the connection.  Is the expectation that TCP re-connect logic is currently implemented or is this an open feature request?

**Comment by adubovikov** [comment]
what type of the HEP server do you use ? And the version of the captagent ?

**Comment by mkrokosz** [comment]
We are using Homer server for UDP but over TCP we are looking at a custom server application to process the sip messages.  Does the server-side matter in terms of the reconnect logic on the client-side?

**Comment by adubovikov** [comment]
we use libuv and reconnect should be handle inside the library. Also server-side matter if the connection was not closed correct... i.e. no FYN

**Comment by mkrokosz** [comment]
There is never any guarantee of how a connection is closed from client perspective and it must handle all scenarios, regardless of implementation.  I couldn't find any indication in libuv that reconnect is handled within the library but maybe I missed something.  If we can confirm that it is not handled in libuv, I can provide a pull request with tcp reconnect logic implemented and functioning in captagent.

**Comment by adubovikov** [comment]
yeah, my bad, I have expect that libuv will handle tcp reconnection by self, but looks like need to implement minimum two triggers: sigpipe and check on uv_write -> on_send_tcp_request. If you can do it, it will be awesome!  Thank you!

**Comment by adubovikov** [comment]
so, looks like it have to be done this way:

https://github.com/libuv/libuv/blob/1a96fe33343f82721ba8bc93adb5a67ddcf70ec4/test/test-tcp-write-fail.c#L60-L67

and after you can call reinit tcp/udp connection from "close_cb" again.
