### ISSUE TITLE
Build failure with libuv-0.10 and uv_key_t (TLS)

### ISSUE THREAD

**Issue by zecke** [sipcapture/captagent#105]
The latest build is failing with libuv-0.10 (still the default in jessie). I think using TLS can be avoided by putting the hep_connection into handle->data.

I could either:

a.) Remove uv_key_t and related functions and store the handle
b.) Upgrade the ppa and debian/control to require libuv-1-dev.

Any preference?

**Comment by adubovikov** [comment]
I just compiled with libuv 0.1x without any issues. What is your issue ?

**Comment by zecke** [comment]
uv_key_t does not exist. It is not in 0.10.x as present on debian jessie (or the linuxjeddie build used by travis)

```
transport_hep.c:79:1: error: unknown type name ‘uv_key_t’
transport_hep.c: In function ‘on_tcp_close’:
transport_hep.c:708:9: warning: implicit declaration of function ‘uv_key_get’ [-Wimplicit-function-declaration]
transport_hep.c:708:38: warning: initialization makes pointer from integer without a cast [enabled by default]
transport_hep.c: In function ‘on_send_tcp_request’:
transport_hep.c:725:38: warning: initialization makes pointer from integer without a cast [enabled by default]
transport_hep.c: In function ‘_run_uv_loop’:
transport_hep.c:911:7: warning: implicit declaration of function ‘uv_key_set’ [-Wimplicit-function-declaration]
transport_hep.c: In function ‘on_tcp_connect’:
transport_hep.c:982:38: warning: initialization makes pointer from integer without a cast [enabled by default]
transport_hep.c: In function ‘load_module’:
transport_hep.c:1095:2: warning: implicit declaration of function ‘uv_key_create’ [-Wimplicit-function-declaration]
transport_hep.c: In function ‘unload_module’:
transport_hep.c:1272:2: warning: implicit declaration of function ‘uv_key_delete’ [-Wimplicit-function-declaration]
```

https://travis-ci.org/sipcapture/captagent/builds/183841897.

My patch to store the hep_connection inside uv_loop_t->data is almost ready.. just wondering how to test it. :)

**Comment by adubovikov** [comment]
ghmm, you are right.... checking

**Comment by zecke** [comment]
Let me push my "untested" change

**Comment by adubovikov** [comment]
sorry, I just fixed. 

unfortunately, libuv 0.10 doesn't have uv_key_*...

@mkrokosz  Anything that can be fixed/changed here ?

**Comment by zecke** [comment]
https://github.com/sipcapture/captagent/pull/106 can you test with TCP? I only tested it "connects" but nothing was written (my .pcap file was replayed too quickly and no reconnect testing)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/5e2668ccf1ef48620fae0b1f24af2fd4a18532f4

is it ok for you ?

**Comment by zecke** [comment]
From a code point of view it looks fine, I wonder why you want to keep the TLS usage on new versions?

**Comment by adubovikov** [comment]
HEP can be also TLS

**Comment by zecke** [comment]
TLS in the context of uv_key_t referred to Thread Local Storage. To me it just seemed convenient to use TLS to get the hep_connection as currently we have one-thread per connection, but thanks to uv we could have multiple threads in the future? Just trying to understand why you want to keep uv_key_t but it is not important.

**Comment by adubovikov** [comment]
I close the issue. Please reopen if needs.
