### ISSUE TITLE
Initial capagent start 

### ISSUE THREAD

**Issue by Sykrann** [sipcapture/captagent#108]
Hello Sirs,

I am pretty new in Capagent but I really want to try it out. 

Unfortunatelly I have troubles when I start Capagent.

It says to me:

_**root@switch:~# /etc/init.d/captagent stop  
[ ok ] Stopping Captagent: captagent:.
root@switch:~# /etc/init.d/captagent start
[....] Starting Captagent: captagent:[NOTICE] Loaded core config
[ERR] modules.c:75 dlopen error [libuv.so.1: cannot open shared object file: No such file or directory]
. ok 
root@switch:~# [ERR] conf_function.c:458 find_export_record: <send_hep> not found 

parse error (10,27-28): unknown command, missing loadmodule?

ERROR: bad config file (1 errors)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)**_

Captagent was installed based on instruction here on Debian 8 64-bit.

libuv packet exists:

root@switch:~# dpkg -l | grep libuv
ii  libuv                                 1.8.0-2                            amd64        libuv1

The captagent.xml it seems is correct:

<?xml version="1.0"?>
<document type="captagent/xml">
        <configuration name="core.conf" description="CORE Settings" serial="2014024212">
            <settings>
                <param name="debug" value="3"/>
                <param name="version" value="2"/>
                <param name="serial" value="2014056501"/>
                <param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
                <param name="daemon" value="false"/>
                <param name="syslog" value="false"/>
                <param name="pid_file" value="/var/run/captagent.pid"/>
                
                <param name="module_path" value="/opt/captagent/lib/captagent/modules"/>
                <param name="config_path" value="/opt/captagent/etc/captagent/"/>
                <param name="capture_plans_path" value="/opt/captagent/etc/captagent/captureplans"/>
                <param name="backup" value="/opt/captagent/etc/captagent/backup"/>
                <param name="chroot" value="/opt/captagent/etc/captagent"/>
            </settings>
        </configuration>
        <configuration name="modules.conf" description="Modules">
            <modules>
        
                <load module="transport_hep" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="database_hash" register="local"/>
                <load module="protocol_rtcp" register="local"/>                                           
                <load module="socket_pcap" register="local"/>
                <load module="socket_raw" register="local"/>
            
            </modules>
        </configuration>
</document>

Capagent is installed in /opt/captagent.

Please point me at a way I should check to fix the issue.

Thank you,

**Comment by adubovikov** [comment]
be sure that libuv.so.1 is in your ldpath.
i.e. run  ldconfig or set LD_PATH variable

**Comment by Sykrann** [comment]
Hello Sir, 
thank you for your prompt response. After I followed your advise I could start Capagent!
Unfortunately I faces another issue :( Homer web-interface does show me any stats.

In spite of the fact that mysql tables have data:

mysql> select count(*) from stats_ip;
+----------+
| count(*) |
+----------+
|       32 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from sip_capture_call_20170112;
+----------+
| count(*) |
+----------+
|   160370 |
+----------+
1 row in set (0.62 sec)

I can not find any errors. Firebug shows me that request returned 0 value:

{
    "sid": "sdtmon2le0tsqt9dl7d7tr0sc4",
    "auth": "true",
    "status": 200,
    "message": "no data",
    "data": [
        
    ],
    "count": 0
}

Please help

**Comment by adubovikov** [comment]
Be sure that you have selected a correct time range: The right corner on top.

**Comment by adubovikov** [comment]
I am closing the ticket. The init start was fixed.
