### ISSUE TITLE
HEP version 3 does not send capture_id 

### ISSUE THREAD

**Issue by jenniferakemi** [sipcapture/captagent#109]
Hi guys,

I finally got captagent setup instead of having all the various opensips and freeswitchs inserting into the homer database and it's great. Thanks so much for your awesome tool.

I was struggling with having the node populated correctly when I am using version 3 hep (the default). (we have 2 capture agents for redundancy but want to be able to filter it down to one for a cleaner display).

I found out in https://github.com/sipcapture/captagent/blob/master/src/modules/transport/hep/transport_hep.c on line 561 it says (and same again on 605)
    if(profile_transport[idx].version == 2) {
        totlen += sizeof(struct hep_timehdr);
        hep_time.tv_sec = rcinfo->time_sec;
        hep_time.tv_usec = rcinfo->time_usec;
        hep_time.captid = profile_transport[idx].capt_id;
    }

The node is filled in properly if I use version 2 HEP.
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="transport_hep" description="HEP Protocol" serial="2014010402">
        <profile name="hepsocket" description="Transport HEP" enable="true" serial="2014010402">
            <settings>
                <param name="version" value="2"/>
                <param name="capture-host" value="192.168.5.73"/>
                <param name="capture-port" value="9060"/>
                <param name="capture-proto" value="udp"/>
                <param name="capture-id" value="52"/>
                <param name="capture-password" value="myhep"/>
                <param name="payload-compression" value="false"/>
            </settings>
        </profile>
    </module>
</document>

(I wanted to help so I tried to make a pull request but I was actually unable to fix it by just changing those lines to include version 3 - I see there's a lot of other stuff going on as well if it's version 3 so that's probably why)

Thanks!
Jennifer

**Comment by adubovikov** [comment]
Hi,

it should be here:

https://github.com/sipcapture/captagent/blob/master/src/modules/transport/hep/transport_hep.c#L388-L391

but as I see there is no issue, need check on the server's side if there are the capture_id has been extracted

**Comment by adubovikov** [comment]
@jenniferakemi can you provide the kamailio's version of your sip capture server ?

**Comment by jenniferakemi** [comment]
it is version: kamailio 4.4.5 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 4.9.2
