### ISSUE TITLE
CentOS 5

### ISSUE THREAD

**Issue by vs1785** [sipcapture/captagent#111]
Is it possible to compile captagent onCentOS 5.10 ?

**Comment by adubovikov** [comment]
yes, if you have installed all libraries

**Comment by vs1785** [comment]
Thank you for the reply.

I did installed all required libraries but when i try to run build.sh, i am getting below error

You need to have m4, automake, autoconf, libtool...
configure.ac:2: /usr/bin/m4: Warning: Excess arguments to built-in `_m4_popdef' ignored
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
configure.ac:2: /usr/bin/m4: Warning: Excess arguments to built-in `_m4_popdef' ignored
autom4te: /usr/bin/m4 failed with exit status: 1
automake: autoconf failed with exit status: 1
configure.ac:2: /usr/bin/m4: Warning: Excess arguments to built-in `_m4_popdef' ignored
autom4te: /usr/bin/m4 failed with exit status: 1


Is there any changes required in configure.ac ?

Here are my versions

[root@voiceserver captagent]# autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

[root@voiceserver captagent]# autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.


[root@voiceserver captagent]# m4 --version
GNU m4 1.4

**Comment by adubovikov** [comment]
please install m4 version 1.4.17

**Comment by vs1785** [comment]
I dont think that will work.

I could not find compiled version of m4 1.4.17 anywhere for CentOS 5 and when i try to compile, it required automake and autoconf upgrades which in turn requires m4 1.4.11 or higher

Let me spend some more time and see if i can make it work

**Comment by vs1785** [comment]
I am able to find m4 1.4.16 rpm and it fixed the error.

Now i am getting error on ./configure for flex.

I will update if i am able to fix it. Below is the error

configure: error: flex missing yypop_buffer_state - upgrade to version 2.5.33 or later

**Comment by vs1785** [comment]
I am able to fix error on flex and libuv i found after that.

Now it does in ./configure with below error

configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

Can you help me on this ?

**Comment by adubovikov** [comment]
please run ./build.sh one more time

**Comment by vs1785** [comment]
I ran ./build.sh and it gave me lot of output.

It seems to be failing in 

autoreconf --force --install

Here is the error i got

configure.ac:150: the top level
configure.ac:325: required file `$PACKAGE_NAME.spec.in' not found
configure.ac:325: required file `conf/$PACKAGE_NAME.xml.in' not found
configure.ac:325: required file `pkg/debian/$PACKAGE_NAME.init.in' not found
autoreconf: automake failed with exit status: 1

**Comment by vs1785** [comment]
I was able to fix this problem by hardcoding captagent in $PACKAGE_NAME in lines where it thrown error.

After that i received below error

Makefile:245: *** Recursive variable `AM_CFLAGS' references itself (eventually).  Stop.

I fixed that by replacing

AM_CFLAGS = ${AM_CFLAGS} -I$(top_srcdir)/include

By

AM_CFLAGS += -I$(top_srcdir)/include

Now at last i got error in tcp protocol

make[3]: Entering directory `/root/temp/captagent/captagent/src/modules/protocol/tcp'
make[3]: *** No rule to make target `all'.  Stop.

It seems there is a missing make file in folder.

Any idea how it misses a make file ?

**Comment by adubovikov** [comment]
let me check the tcp module. Looks like it broken :-)

**Comment by vs1785** [comment]
Thanks, 

I noticed that it was added recently. 

I downloaded captagent-6.1.0.20 and it compiled fine except for 

AM_CFLAGS = ${AM_CFLAGS} -I$(top_srcdir)/include

Which i fixed.

I will run and report how it works out.

Thanks for your help.

**Comment by adubovikov** [comment]
protocol_tcp has been fixed. But only compiling :-), not functionality

**Comment by vs1785** [comment]
I am able to install but when i start, i get below error

[ERR] modules.c:75 dlopen error [/usr/local/captagent/lib/captagent/modules/socket_pcap.so: undefined symbol: pcap_set_promisc]

I have verified that i have latest version of libpcap installed.

Is there any way to resolve this error ?

**Comment by adubovikov** [comment]
old version of pcap. Please upgrade to > 1.6.x

**Comment by vs1785** [comment]
I have 1.8.1 installed.

It is still giving me this error.

**Comment by adubovikov** [comment]
and of course you didn't forget to remove old one ?

do: 

ldd /usr/local/captagent/lib/captagent/modules/socket_pcap.so

**Comment by vs1785** [comment]
ldd /usr/local/captagent/lib/captagent/modules/socket_pcap.so

        linux-gate.so.1 =>  (0x00f31000)
        libpcap.so.0.9.4 => /usr/lib/libpcap.so.0.9.4 (0x00d74000)
        libexpat.so.0 => /lib/libexpat.so.0 (0x00887000)
        libdl.so.2 => /lib/libdl.so.2 (0x00f07000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x00bdc000)
        libc.so.6 => /lib/libc.so.6 (0x001dc000)
        /lib/ld-linux.so.2 (0x005b3000)

Shall i just delete /usr/lib/libpcap.so.0.9.4 ?

**Comment by vs1785** [comment]
I have new version in /usr/local/lib

How can i link to new version when compiling captagent ?

**Comment by adubovikov** [comment]
man ldconfig

**Comment by adubovikov** [comment]
I hope the issue has been fixed :-)

**Comment by uppaljs** [comment]
Confirm works with centos 5 :) just went through this nightmare.

**Comment by slife80** [comment]
Hello, can you please let me know what are the steps to follow in order to install it correctly on centos 5?  It's driving me crazy!! Thanks a lot!
