### ISSUE TITLE
tcp module makefile

### ISSUE THREAD

**Issue by benpollard** [sipcapture/captagent#113]
Hi I've just tried to compile and I'm getting the following error

```
make[3]: Entering directory `/usr/src/captagent/src/modules/protocol/tcp'
make[3]: *** No rule to make target `all'.  Stop.
make[3]: Leaving directory `/usr/src/captagent/src/modules/protocol/tcp'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/src/captagent/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/captagent/src'
make: *** [all-recursive] Error 1
```
There doesn't seem to be a makefile generated in this module.

Any ideas?

**Comment by adubovikov** [comment]
we will check, but the tcp module has been not yet released

**Comment by kvishnivetsky** [comment]
Hello, Alexander.
I have the same issue with TCP module.
May be, it will be optimal to move this module code to additional branch to prevent such fails?

**Comment by adubovikov** [comment]
protocol_tcp has been fixed. But only compiling :-), not functionality

**Comment by benpollard** [comment]
Thank you, I shall give it another go.

**Comment by benpollard** [comment]
I can now compile. Thank you for sorting this so quickly.
