### ISSUE TITLE
Error enabling socket_tzsp

### ISSUE THREAD

**Issue by brianjones-v4n** [sipcapture/captagent#116]
I've enabled the module socket_tzsp in captagent.xml and enabled the profile in socket_tzsp.xml.  When starting captagent this error is logged:

[NOTICE] Loaded core config
parse error (7,30-31): unknown command, missing loadmodule?

This install of captagent works correctly with socket_pcap but not with socket_tzsp enabled and I was not able to find any example config to compare to.  Using captagent v 6.2.0.2.

**Comment by adubovikov** [comment]
did you compile this module ? please check if the module exists in the lib/modules directory

**Comment by brianjones-v4n** [comment]
/usr/local/captagent/lib/captagent/modules does contain:
socket_tzsp.a
socket_tzsp.la
socket_tzsp.so

**Comment by adubovikov** [comment]
please activate debug (>5), disable daemon mode and syslog and run in
foreground

**Comment by brianjones-v4n** [comment]
[NOTICE] Loaded core config
[NOTICE] Loaded transport_hep
[NOTICE] Loaded protocol_sip
[NOTICE] Loaded database_hash
[NOTICE] Loaded protocol_rtcp
[NOTICE] Loaded socket_tzsp
[ERR] conf_function.c:455 find_export_record: <tzsp_payload_extract> not found

parse error (7,30-31): unknown command, missing loadmodule?

ERROR: bad config file (1 errors)
[NOTICE] Loaded socket_pcap
ERROR: bad config file (1 errors)
ERROR: bad config file (1 errors)

**Comment by adubovikov** [comment]
please load the socket_pcap before socket_tzsp

**Comment by brianjones-v4n** [comment]
I've rebuilt, and reordered the modules as suggested and the startup is good.  Thank you.

**Comment by adubovikov** [comment]
super!
