### ISSUE TITLE
[ERR] protocol_sip.c:377 & [ERR] protocol_sip.c:353

### ISSUE THREAD

**Issue by ezrabenson** [sipcapture/captagent#120]
I have set up captagent on a voipnow server and it is sending data to homer.
Homer is working and receiving the data, however on the voipnow server, these errors keep popping up

> [ERR] protocol_sip.c:377 sipPacket CALLID has 0 len
[ERR] protocol_sip.c:353 SIP PARSE ERROR [-1]

Right at the same time, in homers syslog, this is what appears each time

> Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/msg_parser.c:253]: get_hdr_field(): bad body for <Supported: replace>(16)
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/msg_parser.c:329]: parse_headers(): bad header field [Supported: replace]
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/msg_parser.c:253]: get_hdr_field(): bad body for <Supported: replace>(16)
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/msg_parser.c:329]: parse_headers(): bad header field [Supported: replace]
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: sipcapture [sipcapture.c:1209]: sip_capture_prepare(): cannot parse headers
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/msg_parser.c:253]: get_hdr_field(): bad body for <Supported: replace>(16)
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/msg_parser.c:329]: parse_headers(): bad header field [Supported: replace]
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/parse_ppi_pai.c:124]: parse_pai_header(): Error parsing PAI header
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/msg_parser.c:253]: get_hdr_field(): bad body for <Supported: replace>(16)
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/msg_parser.c:329]: parse_headers(): bad header field [Supported: replace]
Mar  2 23:27:52 hep /usr/sbin/kamailio[1488]: ERROR: <core> [parser/parse_ppi_pai.c:171]: parse_ppi_header(): Error parsing PPI header

Any help would be appreciated, thank you

**Comment by lmangani** [comment]
Hi @ezrabenson 

This suggests messages being capture and processed are malformed and can't be parsed.
This could be either due to fragmentation (see relevant options in captagent) or an actual issue.

**Comment by adubovikov** [comment]
Can you please enable debug 5 and you will see if your packets are corrupted

**Comment by ezrabenson** [comment]
This is what I get when I enable debug 5

> [root@vn25 captagent]# captagent
[NOTICE] Loaded core config
[NOTICE] Loaded transport_hep
[NOTICE] Loaded protocol_sip
[NOTICE] Loaded database_hash
[NOTICE] Loaded protocol_rtcp
[NOTICE] Loaded socket_pcap
********[NOTICE] Loaded socket_raw



> [ERR] protocol_sip.c:377 sipPacket CALLID has 0 len
[ERR] protocol_sip.c:353 SIP PARSE ERROR [-1]

> [ERR] protocol_sip.c:377 sipPacket CALLID has 0 len
[ERR] protocol_sip.c:353 SIP PARSE ERROR [-1]

When I quit

> [NOTICE] unloaded module socket_raw
[NOTICE] unloaded module socket_pcap
[NOTICE] Unloaded protocol_rtcp
[NOTICE] unloaded module database_hash
[NOTICE] unloaded module protocol_sip
[NOTICE] unloaded module transport_hep

**Comment by adubovikov** [comment]
ok, set to 10 and check again

**Comment by ezrabenson** [comment]
Sorry for the long reply, We have found the errors are coming from a SIP trunk we have created a while back, found it by setting debug 10. Thank You
