### ISSUE TITLE
ERSPAN feature enable?

### ISSUE THREAD

**Issue by ashmirza** [sipcapture/captagent#122]
Hey,
the code looks like there is conditional support for ERSPAN now.
Can someone help me in setting up the captagent to be able to parse ERSPAN traffic?
I am not able to find any documentation to enable ERSPAN.

Thanks.

**Comment by adubovikov** [comment]
we don't have currently support for GRE.

**Comment by adubovikov** [comment]
another question, do you mean ERSPAN von Cisco with unicast header ?
