### ISSUE TITLE
Match RTCP packets to SDPs with NAT'd address

### ISSUE THREAD

**Issue by tslytsly** [sipcapture/captagent#125]
Hi Guys,

Please see this issue for a bit more info: [#97](https://github.com/sipcapture/captagent/issues/97)

Would it be possible to look at adding this feature? Most of our deployments are behind NAT, so it is important for us to be able to configure captagent this way.

Thanks

Tom

**Comment by adubovikov** [comment]
we can focus on it only after OpenSIPs summit and Kamailio World

**Comment by tslytsly** [comment]
Great @adubovikov thanks.
Happy to help with any testing, not sure my coding skills are up to any actual coding. :)

**Comment by tslytsly** [comment]
Hi Guys,
Any progress on this?

Is it in the pipeline?

Thanks

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/c29f79fb5ae1622fc17c921ae2593e0f04f1cd2c

**Comment by tslytsly** [comment]
thanks @adubovikov 
I don't think it's working, but I may have missed something:
1. I checkedout your commit
2. did the buikd, configure and make.
3. added `<param name="nat-mode" value="true"/>` to `database_hash.xml`
4. restarted captagent

But I'm still getting: `[ERR] protocol_sip.c:132 Couldnot find this call` in the logs
Some of the SIP calls have the Qos metrics page, but nothing in them. And others just say no Qos metrics available.

**Comment by lmangani** [comment]
Tom,

Please perform some control calls and capture the output to confirm if:

* captagent is sending any of the unmatched statistics w/ or w/o nat
* how they are stored in the database

**Comment by adubovikov** [comment]
@tslytsly Please be sure that SIP and RTP traffic are on the same interface/box and captagent can see it (portranges in the socket_pcap for both profiles)

**Comment by adubovikov** [comment]
also, here we use the source ip machining and we expect that RTP will come from SAME source port, but from public IP.  Anyway a trace will be very helpful.

**Comment by tslytsly** [comment]
Okay, you can get the capture from here: https://1drv.ms/u/s!AmjEaFke2E2Mha5j11eVBeHmOrXUbg
This is the Qos report from Homer:
![image](https://user-images.githubusercontent.com/17383159/28875008-f56c6a06-778b-11e7-8a72-df4ee3e1d7fc.png)

**Comment by lmangani** [comment]
The chart being displayed means something WAS matched by the correlation - could you check in the API response for qos what is returned? If this was a very short call, could you try with a longer duration call (with more reports) does display any points?

**Comment by adubovikov** [comment]
do you have any RTCP data for call: 868fa9070ab8a86d7402538e89f485a9

**Comment by adubovikov** [comment]
the problem in your trace is something different, you have public IP in the SDP but RTCP packets come from intranet IP, so, this is something wrong with your scenario and this is couldn't be fixed in passive mode.
