### ISSUE TITLE
RTCP data not showing on Homer GUI.

### ISSUE THREAD

**Issue by aliraxa** [sipcapture/captagent#127]
Hi,

I am new to Homer .. still looking into how it works. I need some help:

I used Centos7 installer to do my setup .. everything is working fine except I cant see Call QoS on HomerGUI. I can see data is populated in rtcp_capture table but can't find it on GUI:

| 531 | 2017-04-10 02:14:30 | 1491776070769225 | 7559cc162fb5b6957c25fef36be710b8@111.222.222.222:5060 | 111.222.222.222 | 14861 | 113.110.11.113 | 10303 | 1 | 2 | 1 | homer01:0 | { "sender_information":{"ntp_timestamp_sec":3325072860,"ntp_timestamp_usec":2061101508,"octets":55360,"rtp_timestamp":4029052574, "packets":346},"ssrc":420075750,"type":200, "report_blocks":[{"source_ssrc":1296135884,"highest_seq_no":73968,"fraction_lost":0,"ia_jitter":0,"packets_lost":57246,"lsr":818005205,"dlsr":327614}],"report_count":1,"sdes_ssrc":420075750,"sdes_chunk_ssrc":16777216,"sdes_information": [],"sdes_report_count":0} |
| 532 | 2017-04-10 02:14:30 | 1491776070769593 | 7559cc162fb5b6957c25fef36be710b8@113.110.11.113:5060 | 113.110.11.113 | 10303 | 111.222.222.222 | 14861 | 1 | 2 | 1 | homer01:0 | { "ssrc":1296135884,"type":201, "report_blocks":[{"source_ssrc":0,"highest_seq_no":0,"fraction_lost":0,"ia_jitter":0,"packets_lost":1,"lsr":818005232,"dlsr":327548}],"report_count":1,"sdes_ssrc":1296135884,"sdes_chunk_ssrc":16777216,"sdes_information": [],"sdes_report_count":0}

Also, I am getting : "server*CLI> [ERR] protocol_sip.c:133 couldn't parse RTCP to json"

I have seen all related threads but all seems fine .. looks like i am doing something else wrong. If you need anything then let me know.

**Comment by lmangani** [comment]
Since the data is actually sent by CaptAgent, you were right to open the issue on the HOMER Project as this is related to data search matching. Please perform a search in HOMER for the same Call-ID and compare any differences in timestamping, which is probably the root cause here.
