### ISSUE TITLE
WARNING: run_actions: null action list (rec_level=4)

### ISSUE THREAD

**Issue by gunjanmk** [sipcapture/captagent#129]
Keep getting about warning and only way to stop this is to kill captagent process.

root@scas3:/home/scsupport# /usr/src/captagent/src/captagent -f /usr/local/captagent/etc/captagent/captagent.xml
[NOTICE] Loaded core config
root@scas3:/home/scsupport# parse error (9,27-28): unknown command, missing loadmodule?

ERROR: bad config file (1 errors)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
parse error (39,30-31): unknown command, missing loadmodule?

ERROR: bad config file (2 errors)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)

root@scas3:/home/scsupport# cat /usr/local/captagent/etc/captagent/captagent.xml
<?xml version="1.0"?>
<document type="captagent/xml">
	<configuration name="core.conf" description="CORE Settings" serial="2014024212">
	    <settings>
		<param name="debug" value="1"/>
		<param name="version" value="2"/>
		<param name="serial" value="2014056501"/>
		<param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
		<param name="daemon" value="true"/>
		<param name="syslog" value="true"/>
		<param name="pid_file" value="/var/run/captagent.pid"/>
		
		<param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
		<param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
		<param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
		<param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
		<param name="chroot" value="/usr/local/captagent/etc/captagent"/>
	    </settings>
	</configuration>
	<configuration name="modules.conf" description="Modules">
	    <modules>

		<load module="transport_hep" register="local"/>
		<load module="database_hash" register="local"/>
		<load module="protocol_sip" register="local"/>
		<load module="protocol_rtcp" register="local"/>
		<load module="socket_pcap" register="local"/>
	    </modules>
	</configuration>
</document>

Anything specific that we should check ?

**Comment by adubovikov** [comment]
please set debug 10 and check thats command are not enabled.

**Comment by gunjanmk** [comment]
Thanks for your quick response, 

I have increased debug to 10 but can NOT see much, See below output

Does this "parse error (9,27-28)" mean anything specific ?


root@as3:/home/scsupport# cat /usr/local/captagent/etc/captagent/captagent.xml
<?xml version="1.0"?>
<document type="captagent/xml">
	<configuration name="core.conf" description="CORE Settings" serial="2014024212">
	    <settings>
		<param name="debug" value="10"/>
		<param name="version" value="2"/>
		<param name="serial" value="2014056501"/>
		<param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
		<param name="daemon" value="true"/>
		<param name="syslog" value="true"/>
		<param name="pid_file" value="/var/run/captagent.pid"/>
		
		<param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
		<param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
		<param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
		<param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
		<param name="chroot" value="/usr/local/captagent/etc/captagent"/>
	    </settings>
	</configuration>
	<configuration name="modules.conf" description="Modules">
	    <modules>

		<load module="transport_hep" register="local"/>
		<load module="database_hash" register="local"/>
		<load module="protocol_sip" register="local"/>
		<load module="protocol_rtcp" register="local"/>
		<load module="socket_pcap" register="local"/>
	    </modules>
	</configuration>
</document>
root@as3:/home/scsupport#
++++++++++++++++++++++++++++++

root@scas3:/home/scsupport# /usr/src/captagent/src/captagent -f /usr/local/captagent/etc/captagent/captagent.xml
[NOTICE] Loaded core config
root@scas3:/home/scsupport# parse error (9,27-28): unknown command, missing loadmodule?

ERROR: bad config file (1 errors)
parse error (39,30-31): unknown command, missing loadmodule?

ERROR: bad config file (2 errors)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)

**Comment by adubovikov** [comment]
Please disable daemon mode and syslog options and try again

On 12 Apr 2017 01:35, "gunjanmk" <notifications@github.com> wrote:

Thanks for your quick response,

I have increased debug to 10 but can NOT see much, See below output

Does this "parse error (9,27-28)" mean anything specific ?

root@as3:/home/scsupport# cat /usr/local/captagent/etc/
captagent/captagent.xml

	<load module="transport_hep" register="local"/>
	<load module="database_hash" register="local"/>
	<load module="protocol_sip" register="local"/>
	<load module="protocol_rtcp" register="local"/>
	<load module="socket_pcap" register="local"/>
    </modules>
</configuration>

root@as3:/home/scsupport# ++++++++++++++++++++++++++++++

root@scas3:/home/scsupport# /usr/src/captagent/src/captagent -f
/usr/local/captagent/etc/captagent/captagent.xml
[NOTICE] Loaded core config
root@scas3:/home/scsupport# parse error (9,27-28): unknown command, missing
loadmodule?

ERROR: bad config file (1 errors)
parse error (39,30-31): unknown command, missing loadmodule?

ERROR: bad config file (2 errors)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sipcapture/captagent/issues/129#issuecomment-293430405>,
or mute the thread

**Comment by gunjanmk** [comment]
This worked. 
Thanks
