### ISSUE TITLE
HEP3 and ISUP 

### ISSUE THREAD

**Issue by jarek-j** [sipcapture/captagent#130]
Hi,
I try to send ISUP to Homer. When starting ./captagent -D isup.pcap I can see HEP3 packets but no ISUP inside of it.

Captagent launched with debug=10 shows in log:

Apr 14 23:23:46 homer-client captagent[2385]: [DEBUG] sctp_support.c:75 sctp: chunk type ignored 3
Apr 14 23:23:46 homer-client captagent[2385]: [DEBUG] sctp_support.c:75 sctp: chunk type ignored 3
Apr 14 23:23:46 homer-client captagent[2385]: [DEBUG] sctp_support.c:75 sctp: chunk type ignored 3
Apr 14 23:23:46 homer-client captagent[2385]: [DEBUG] protocol_ss7.c:286 ISUP service indicator not ISUP but 1
Apr 14 23:23:46 homer-client captagent[2385]: [DEBUG] sctp_support.c:75 sctp: chunk type ignored 3
Apr 14 23:23:46 homer-client captagent[2385]: [DEBUG] sctp_support.c:75 sctp: chunk type ignored 3
Apr 14 23:23:46 homer-client captagent[2385]: [DEBUG] sctp_support.c:75 sctp: chunk type ignored 3
Apr 14 23:23:46 homer-client captagent[2385]: [DEBUG] sctp_support.c:75 sctp: chunk type ignored 3

Regards
--
Jarek

**Comment by lmangani** [comment]
HI @jarek-j please attach the relevant agent config/plan plus a sample PCAP with the traffic you're feeding the agent with. If you can't share this publicly send it to support@sipcapture.org referring this issue.

**Comment by jarek-j** [comment]
OK, I sent an email with PCAP and config attached to support@sipcapture.org.

**Comment by jarek-j** [comment]
Don't you have some example PCAP with ISUP which I can use to check if my captagent will send to Homer properly?

**Comment by lmangani** [comment]
My Apologies for not being able to follow up with this old issue myself - if its still a challenge, please reopen with a fresh trace!
