### ISSUE TITLE
Captagent stopped sending data to Homer

### ISSUE THREAD

**Issue by gunjanmk** [sipcapture/captagent#131]
Hi Team,

Captagent has stopped sending data to homer for some reason and I can not work out why. It was working fine, not aware of any changes which was done on server.

- I can see some output from captagent but homer is not getting this data
- anything specific info we can provide 

Below is logs and file output

++++++++
# cat /usr/local/captagent/etc/captagent/captagent.xml
<?xml version="1.0"?>
<document type="captagent/xml">
	<configuration name="core.conf" description="CORE Settings" serial="2014024212">
	    <settings>
		<param name="debug" value="10"/>
		<param name="version" value="2"/>
		<param name="serial" value="2014056501"/>
		<param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
		<param name="daemon" value="false"/>
		<param name="syslog" value="false"/>
		<param name="pid_file" value="/var/run/captagent.pid"/>
		
		<param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
		<param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
		<param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
		<param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
		<param name="chroot" value="/usr/local/captagent/etc/captagent"/>
	    </settings>
	</configuration>
	<configuration name="modules.conf" description="Modules">
	    <modules>

		<load module="transport_hep" register="local"/>
		<load module="database_hash" register="local"/>
		<load module="protocol_sip" register="local"/>
		<load module="protocol_rtcp" register="local"/>
		<load module="socket_pcap" register="local"/>
	    </modules>
	</configuration>
</document>

++++++++

/usr/src/captagent/src/captagent -f /usr/local/captagent/etc/captagent/captagent.xml
[NOTICE] Loaded core config
[DEBUG] modules.c:50 Loading module: [transport_hep]
[ERR] modules.c:75 dlopen error [/usr/local/captagent/lib/captagent/modules/transport_hep.so: undefined symbol: uv_key_set]
[DEBUG] modules.c:50 Loading module: [database_hash]
[NOTICE] Loaded database_hash
[DEBUG] modules.c:50 Loading module: [protocol_sip]
[NOTICE] Loaded protocol_sip
[DEBUG] modules.c:50 Loading module: [protocol_rtcp]
[NOTICE] Loaded protocol_rtcp
[DEBUG] modules.c:50 Loading module: [socket_pcap]
[NOTICE] Loaded socket_pcap
[DEBUG] socket_pcap.c:573 Activating device: vlan201

[DEBUG] socket_pcap.c:609 Activated device: [vlan201]

[NOTICE] Using filter: (portrange 5060-5091)
[DEBUG] conf_function.c:453 find_export_record: found <msg_check> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <parse_sip> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
[ERR] conf_function.c:458 find_export_record: <send_hep> not found

parse error (9,27-28): unknown command, missing loadmodule?

[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <sip_has_sdp> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <check_rtcp_ipport> in module database_hash [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
ERROR: bad config file (1 errors)
[DEBUG] socket_pcap.c:573 Activating device: vlan201

[DEBUG] socket_pcap.c:764 Link offset interface type [1] [1] [14]
[DEBUG] protocol_sip.c:370 SIP: [OPTIONS sip:61283790369@192.168.1.104:5063;transport=tcp SIP/2.0
Via: SIP/2.0/UDP 103.55.116.65:5060;branch=z9hG4bK0ab875bd;rport
Max-Forwards: 70
From: "2talkpbx" <sip:2talkpbx@103.55.116.65>;tag=as378b9006
To: <sip:61283790369@192.168.1.104:5063;transport=tcp>
Contact: <sip:2talkpbx@103.55.116.65:5060>
Call-ID: 1d741c9478fe2f8e2186ab457b98ea6a@103.55.116.65
CSeq: 102 OPTIONS
User-Agent: YCT PBX
Date: Mon, 24 Apr 2017 01:14:29 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INF

**Comment by adubovikov** [comment]
You try use HEP tcp and in this case better install libuv 1.x, because the
0.1 doesn't support tcp reconnect well. Or switch to hep up.

**Comment by gunjanmk** [comment]
Thanks @adubovikov This is our main frame server so i can probably try second option first. 

"Or switch to hep up"  <<< you mean UDP ? 

Correct me if i am wrong but I assume this is changed by below ? If not, please let me know where to change this

<load module="protocol_rudp" register="local"/> 

+++++

If above change is correct then I assume this did not fix issue for me.

# /usr/src/captagent/src/captagent -f /usr/local/captagent/etc/captagent/captagent.xml
[NOTICE] Loaded core config
[DEBUG] modules.c:50 Loading module: [transport_hep]
[ERR] modules.c:75 dlopen error [/usr/local/captagent/lib/captagent/modules/transport_hep.so: undefined symbol: uv_key_set]
[DEBUG] modules.c:50 Loading module: [database_hash]
[NOTICE] Loaded database_hash
[DEBUG] modules.c:50 Loading module: [protocol_sip]
[NOTICE] Loaded protocol_sip
[DEBUG] modules.c:50 Loading module: [protocol_rudp]
[ERR] modules.c:75 dlopen error [/usr/local/captagent/lib/captagent/modules/protocol_rudp.so: cannot open shared object file: No such file or directory]
[DEBUG] modules.c:50 Loading module: [socket_pcap]
[NOTICE] Loaded socket_pcap
[DEBUG] socket_pcap.c:573 Activating device: vlan201

[DEBUG] socket_pcap.c:609 Activated device: [vlan201]

[NOTICE] Using filter: (portrange 5060-5091)

WARNING: run_actions: null action list (rec_level=3)
WARNING: run_actions: null action list (rec_level=3)
WARNING: run_actions: null action list (rec_level=3)
[DEBUG] socket_pcap.c:775 loop stopped by breakloop
[DEBUG] socket_pcap.c:794 exit loop
[DEBUG] socket_pcap.c:775 loop stopped by breakloop
[DEBUG] socket_pcap.c:794 exit loop
[NOTICE] unloaded module protocol_sip
[NOTICE] unloaded module database_hash

**Comment by adubovikov** [comment]
You have to compile the last version of captagent and use the same libuv library.

Looks like you have compiled the captagent with libuv 1.x but try use libuv0.10
