### ISSUE TITLE
transport_hep.xml capture-host must be IP address

### ISSUE THREAD

**Issue by cervajs** [sipcapture/captagent#133]
for newbies is confusing that capture-host must be IP address. with dns name it doesnt work

**Comment by adubovikov** [comment]
Yes... unfortunately libuv doesn't support it natively... need make a patch.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/08dd902819d8b27a66ecc011511a4ed32241efec

should works now

**Comment by itlevel3** [comment]
I can confirm this is working now using hostname for capture host :)
Thank you.
