### ISSUE TITLE
no rtcp sent by captagent

### ISSUE THREAD

**Issue by mattki** [sipcapture/captagent#135]
I run Ubuntu 16.04.2 and Asterisk 13.15 using only chan_sip and latest homer running on a different host.

Using mostly default captagent config I get sip call detail sent to homer host with no issue.

rtcp does not get sent to homer host but seems to be detected by captagent. I have checked this with ngrep on homer host, and also checked the homer databases and no rtcp rows are inserted.

captagent 6.2.0.2 and homer 5

rtcp_capture_plan.cfg:

capture[pcap] {

        # here we can check source/destination IP/port, message size
        if(msg_check("size", "20")) {

                if(is_rtcp()) {
                        clog("ERROR", "found rtcp matt");
                        #Only for redis!

                        if(is_rtcp_exist()) {

                                #Convert to JSON if needed.
                                if(parse_rtcp_to_json()) {

                                        #Can be defined many profiles in transport_hep.xml
                                        if(!send_hep("hepsocket")) {
                                                clog("ERROR", "Error sending HEP!!!!");
                                        }

                                } else {
                                        clog("ERROR", "couldn't parse RTCP to json");
                                }

                        } else {
                                clog("ERROR", "Couldnot find this call");
                        }
                } else {
                        clog("ERROR", "This is not RTCP");
                }
        }
        drop;
}

sip capture plan:

capture[pcap] {

        # here we can check source/destination IP/port, message size
        if(msg_check("size", "100")) {

            #Do parsing
            if(parse_sip()) {
                #Can be defined many profiles in transport_hep.xml

                if(!send_hep("hepsocket")) {
                    clog("ERROR", "Error sending HEP!!!!");
                }

                 if(sip_has_sdp())
                 {
                        #Activate it for RTCP checks
                        if(!check_rtcp_ipport())
                        {
                                clog("ERROR", "ALREADY EXIST");
                        }
                 }

                #Duplicate all INVITEs to JSON transport
                # if(sip_is_method() && sip_check("method","INVITE")) {
                #    #Can be defined many profiles in transport_json.xml
                #    if(!send_json("jsonsocket")) {
                #       clog("ERROR", "Error sending JSON!!!");
                #    }
                # }
            }
        }
        drop;
}

transport_hep.xml:

<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="transport_hep" description="HEP Protocol" serial="2014010402">
        <profile name="hepsocket" description="Transport HEP" enable="true" serial="2014010402">
            <settings>
                <param name="version" value="3"/>
                <param name="capture-host" value="actual homer host ip address"/>
                <param name="capture-port" value="9060"/>
                <param name="capture-proto" value="udp"/>
                <param name="capture-id" value="2001"/>
                <param name="capture-password" value=""/>
                <param name="payload-compression" value="false"/>
            </settings>
        </profile>
    </module>
</document>

protocol_sip.xml:

<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="protocol_sip" description="SIP Protocol" serial="2014010402">
        <profile name="proto_sip" description="PROTO SIP" enable="true" serial="2014010402">
            <settings>
                <param name="dialog-type" value="2"/>
                <param name="dialog-timeout" value="180"/>
            </settings>
        </profile>
    </module>
</document>

captagent.xml:

<?xml version="1.0"?>
<document type="captagent/xml">
        <configuration name="core.conf" description="CORE Settings" serial="2014024212">
            <settings>
                <param name="debug" value="9999"/>
                <param name="version" value="2"/>
                <param name="serial" value="2014056501"/>
                <param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
                <param name="daemon" value="false"/>
                <param name="syslog" value="true"/>
                <param name="pid_file" value="/var/run/captagent.pid"/>
                
                <param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
                <param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
                <param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
                <param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
                <param name="chroot" value="/usr/local/captagent/etc/captagent"/>
            </settings>
        </configuration>
        <configuration name="modules.conf" description="Modules">
            <modules>

                <load module="transport_hep" register="local"/>
                <load module="database_hash" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="protocol_rtcp" register="local"/>
                <load module="socket_pcap" register="local"/>
                <load module="socket_raw" register="local"/>
                <load module="socket_rtcpxr" register="local"/>
                <load module="transport_json" register="local"/>

        
            </modules>
        </configuration>
</document>

protocol_rtcp.xml:

<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="protocol_rtcp" description="RTCP Protocol" serial="2014010402">
        <profile name="proto_rtcp" description="PROTO RTCP" enable="true" serial="2014010402">
            <settings>
                <param name="rtcp-version" value="2"/>
            </settings>
        </profile>
    </module>
</document>

**Comment by adubovikov** [comment]
please check your  socket_pcap.xml and be sure that the socket profile for rtcp has been activated.

**Comment by mattki** [comment]
Thank you for the response and the great software!

You're right, just had to change enabled=false to enabled=true for profile socketspcap_rtcp in socket_pcap.xml.

**Comment by adubovikov** [comment]
ok. you are welcome

**Comment by agicblack** [comment]
<------><profile name="socketspcap_rtcp" description="RTCP Socket" enable="true" serial="2014010402">
but don't work

**Comment by hoangtuan151** [comment]
Dear @adubovikov ,
I very much appreciate your fantastic project.

I got the same issue here: the Homer server has not received any QoS reports for media.

Here's my CaptAgent configuration:
* FreeSwitch, CaptAgent, and Homer are on the same server
* `socketspcap_rtcp` in `socket_pcap.xml` is enabled
* `if(sip_has_sdp())` block in `sip_capture_plan.cfg` is un-commented

**Comment by kYroL01** [comment]
First, could you guys @mattki @hoangtuan151 double-check if the SIP and RTCP traffic is correctly ingested to captagent ?
Second, you can run captagent in foreground mode to see what's happening in real time with the traffic 
`/usr/local/captagent/sbin/captagent -x 10`

Thanks
