### ISSUE TITLE
./configure fails CentOS 6

### ISSUE THREAD

**Issue by gdalgliesh** [sipcapture/captagent#137]
git commit 17984273a735c9794122ff36d763ab289b10622d
failed on ./configure

checking for yywrap in -lfl... yes
./configure: line 14180: syntax error near unexpected token `else'
./configure: line 14180: `else'

seems to be some strange stuff in configure

if test "x$ac_cv_lib_wireshark_epan_get_version" = x""yes; then

else
  { { $as_echo "$as_me:$LINENO: error: $PACKAGE_NAME requires but cannot find wireshark libraries" >&5
$as_echo "$as_me: error: $PACKAGE_NAME requires but cannot find wireshark libraries" >&2;}
   { (exit 1); exit 1; }; }
fi

**Comment by adubovikov** [comment]
did you run with --enable-epan ?

**Comment by Dreamtilt** [comment]
Hi, can also confirm the same error on Centos 6 when running configure.

./configure: line 14180: syntax error near unexpected token `else'
./configure: line 14180: `else'

Have tried with --enable-epan - still fails.

**Comment by adubovikov** [comment]
please check it:

https://github.com/sipcapture/captagent/commit/bb94f213df9ee039138b174d54545e38d4af0107
