### ISSUE TITLE
RTCP data not sending to Homer

### ISSUE THREAD

**Issue by ezrabenson** [sipcapture/captagent#138]
I have been trying to get RTCP data to show in Homer for a while but have not had any luck. Whenever I startup captagent, with the settings I have below, it gives me this error.

`[ERR] protocol_sip.c:132 Couldnot find this call` 

I have performed a packet capture and viewed the results in wireshark and noticed that captagent is not even sending rtcp packets. I am not sure if that is because they may be encapsulated into HEP packets?

On the Homer GUI when I view the QoS Reports it tells me that there are no Statistics Available but I can see some information under "SDP Session 1" [view here](http://imgur.com/GAGv5ly)

Is there something I missed? 

**socket_pcap.xml**

    <?xml version="1.0"?>
    <document type="captagent_module/xml">
        <module name="socket_pcap" description="HEP Socket" serial="2014010402">
            <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
                <settings>
                    <param name="dev" value="eth0"/>
                    <param name="promisc" value="true"/>
                    <param name="reasm" value="false"/>
                    <param name="tcpdefrag" value="false"/>
                    <param name="capture-plan" value="sip_capture_plan.cfg"/>
                    <param name="filter">
                        <value>portrange 5060-5091</value>
                    </param>
                </settings>
            </profile>
            <profile name="socketspcap_rtcp" description="RTCP Socket" enable="true" serial="2014010402">
                <settings>
                    <param name="dev" value="eth0"/>
                    <param name="promisc" value="true"/>
                    <param name="reasm" value="false"/>
                    
                    <param name="ring-buffer" value="20"/>
                    
                    <param name="snap-len" value="256"/>
                    <param name="capture-filter" value="rtcp"/>
                    <param name="capture-plan" value="rtcp_capture_plan.cfg"/>
                    <param name="filter">
                        <value>portrange 10000-20000</value>
                    </param>
                </settings>
            </profile>
        </module>
    </document>

**captagent.xml**

    <?xml version="1.0"?>
    <document type="captagent/xml">
            <configuration name="core.conf" description="CORE Settings" serial="2014024212">
                <settings>
                    <param name="debug" value="3"/>
                    <param name="version" value="2"/>
                    <param name="serial" value="2014056501"/>
                    <param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
                    <param name="daemon" value="false"/>
                    <param name="syslog" value="false"/>
                    <param name="pid_file" value="/var/run/captagent.pid"/>
                    
                    <param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
                    <param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
                    <param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
                    <param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
                    <param name="chroot" value="/usr/local/captagent/etc/captagent"/>
                </settings>
            </configuration>
            <configuration name="modules.conf" description="Modules">
                <modules>
    
                    <load module="transport_hep" register="local"/>
                    <load module="protocol_sip" register="local"/>
                    <load module="database_hash" register="local"/>
                    <load module="protocol_rtcp" register="local"/>
                    <load module="socket_pcap" register="local"/>
                    <load module="socket_raw" register="local"/>
                
                </modules>
            </configuration>
    </document>

**protocol_rtcp.xml**

    <?xml version="1.0"?>
    <document type="captagent_module/xml">
        <module name="protocol_rtcp" description="RTCP Protocol" serial="2014010402">
            <profile name="proto_rtcp" description="PROTO RTCP" enable="true" serial="2014010402">
                <settings>
                    <param name="rtcp-version" value="2"/>
                </settings>
            </profile>
        </module>
    </document>

**transport_hep.xml**

    <?xml version="1.0"?>
    <document type="captagent_module/xml">
        <module name="transport_hep" description="HEP Protocol" serial="2014010402">
            <profile name="hepsocket" description="Transport HEP" enable="true" serial="2014010402">
                <settings>
                    <param name="version" value="3"/>
                    <param name="capture-host" value="10.10.11.225"/>
                    <param name="capture-port" value="9060"/>
                    <param name="capture-proto" value="udp"/>
                    <param name="capture-id" value="2016"/>
                    <param name="capture-password" value="myhep"/>
                    <param name="payload-compression" value="false"/>
                </settings>
            </profile>
        </module>
    </document>

**sip_capture_plan.cfg**

    capture[pcap] {
    
            # here we can check source/destination IP/port, message size
            if(msg_check("size", "100")) {
    
                #Do parsing
                if(parse_sip()) {
                    #Can be defined many profiles in transport_hep.xml
    
                    if(!send_hep("hepsocket")) {
                        clog("ERROR", "Error sending HEP!!!!");
                    }
    
                     if(sip_has_sdp())
                     {
                            #Activate it for RTCP checks
                            if(!check_rtcp_ipport())
                            {
                                    clog("ERROR", "ALREADY EXIST");
                            }
                    }
    
                    #Duplicate all INVITEs to JSON transport
                    # if(sip_is_method() && sip_check("method","INVITE")) {
                    #    #Can be defined many profiles in transport_json.xml
                    #    if(!send_json("jsonsocket")) {
                    #       clog("ERROR", "Error sending JSON!!!");
                    #    }
                    # }
                }
            }
            drop;
    }

**Comment by adubovikov** [comment]
Does SIP and RTP are on the same server ? Do you have any NAT devices ?

**Comment by itlevel3** [comment]
I am experiencing the same issue. Receiving HEP info, but no RTCP. Have modified settings as per requirements in sip_capture_plan.cfg, transport_hep.xml, and enabled RTCP socket in socket_pcap.xml.
I also see [ERR] Couldnot find call in syslog.

**Comment by adubovikov** [comment]
same question as above....

**Comment by itlevel3** [comment]
Hi,
No NATing at all. Servers using public IPs.
Not sure I understand this question "Do you have SIP and RTP on the same server ?". We are using Kazoo, and so we have both Kamailio and FS servers (all separate servers).

**Comment by adubovikov** [comment]
now it's clear. In your scenario it will not work, because captagent should have SIP messages to make correlation between SIP session and RTCP. As a alternative, you can use REDIS and REDIS module to synchronize SIP/RTCP information across multiple catpagent instances. 

unfortunately there is no FAQ how to do it, but if you are brave, please take look how the capture plan works and how to use database_redis module!

Good luck!

**Comment by itlevel3** [comment]
Thanks for the clarification Alex. Can you please please give me a hint at the required config? Something to get me started? :)

**Comment by adubovikov** [comment]
sure:

https://github.com/sipcapture/captagent/blob/master/src/modules/database/redis/database_redis.c#L86-L89

https://github.com/sipcapture/captagent/blob/master/conf/captureplans/sip_capture_plan.cfg#L14-L21

https://github.com/sipcapture/captagent/blob/master/conf/captureplans/rtcp_capture_plan.cfg#L9-L17

**Comment by itlevel3** [comment]
Thank you. I have the items in both capture_plans uncommented. What do I do with database_redis?

Do I need to recompile kamailio or FS to include this file? If not, where do I need to include it?

**Comment by itlevel3** [comment]
Sorry, forget the above comment. I can see the file and I assume it is used when I compile captagent. Problem is I don't know what modifications need to be made here to correlate the calls between Kam and FS. Can you make a suggestion?
Thank you so much Alex. I appreciate any insight you can provide. I must get some QoS stats from my servers at the very least.

**Comment by adubovikov** [comment]
sorry, but as i wrote before there is no FAQ and provided all information that I can....

**Comment by itlevel3** [comment]
I understand. What would it cost to have a small consulting job done for me to set this up? Who can I contact?
Thank you.

**Comment by itlevel3** [comment]
thanks.
