### ISSUE TITLE
cannot 'make' captagent

### ISSUE THREAD

**Issue by itlevel3** [sipcapture/captagent#141]
Hello, 
Please see attached pastebin.
I installed this agent a couple of days ago on another FS server and there was no issue.
I did not specify to use --enable-ssl during ./configure
I am using CentOS 7.3 x64

https://pastebin.com/s8zxdFDw

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/e5770139409431625a073ed755994209a398594f

please check

**Comment by itlevel3** [comment]
It compiles now and I am able to install, but it is not sending packets to the homer server. I have configured all settings but am not getting packets.
I had setup several severs in the same cluster on saturday and they all work. However any servers setup today (using todays git clone) are not sending any packets.

**Comment by adubovikov** [comment]
let us check...

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/e26206491effe6bc5bad77d616ee88a76b7de62e

please check it

**Comment by itlevel3** [comment]
Excellent! Working again now. Thank you very much!
I can also confirm that using hostname for capture server is also working (issue #133).

**Comment by adubovikov** [comment]
super! ;-) thank u
