### ISSUE TITLE
HEP UDP packets > MTU

### ISSUE THREAD

**Issue by awiefhlwheajrliawuqfhlahfjsd** [sipcapture/captagent#144]
When using the latest HOMER docker image and latest CaptAgent6 docker image, SIP message bodies like SDP, etc.. are truncated at whatever fits in the MTU.  I've increased MTU to 10,000 in docker and the host, but the messages remain truncated in HOMER.

It should be noted that in wireshark, with default MTU of 1500, wireshark is able to rebuild message and decode the HEP3 payload using your HEP LUA dissector.  tcpdump on both sides show the fragments arrive to the HOMER docker container.

**Comment by adubovikov** [comment]
you have to activate reassambling for UDP packets in the profile of socket_pcap

**Comment by awiefhlwheajrliawuqfhlahfjsd** [comment]
Thanks, I wasn't clear enough: the SIP traffic is TCP.  The fragmentation I speak of is the HEPv3 traffic.

**Comment by lmangani** [comment]
@awiefhlwheajrliawuqfhlahfjsd most likely the packets are truncated on insert and not on the network or interface. You can set the size of the message column as part of the rotation script settings to be as large as you need it to be.

**Comment by adubovikov** [comment]
you have to activate tcpdefrag in the socket_pcap

**Comment by awiefhlwheajrliawuqfhlahfjsd** [comment]
The table size did it.  FYI I use captagent as a reference, we developed a HEPv3 module for our SIP elements to directly to HOMER.  For captagent, the tcpdefrag was also needed.

Thanks to you both.

**Comment by lmangani** [comment]
Thanks for the confirmation @awiefhlwheajrliawuqfhlahfjsd is your HEPv3 integration or the product you integrated to support HEPv3 public?

**Comment by awiefhlwheajrliawuqfhlahfjsd** [comment]
The integration is part of a commercial product (not FOSS).

**Comment by lmangani** [comment]
Can it be disclosed so we can inform potential users, or is it a secret integration?
