### ISSUE TITLE
X-RTP and P-RTP how to see on QOS Homer?

### ISSUE THREAD

**Issue by KyleHyde6** [sipcapture/captagent#146]
Hi all guys, i have this trouble and im looking about what im doing wrong.

I have a machine with freeswitch - captagent.

i have anotehr with kamailio and homer.

Everything is correct.

But when i  try to cllect info from this BYE packets

User-Agent: Cisco/SPA112-1.3.5(004p)
P-RTP-Stat: PS=20366,OS=3258560,PR=20202,OR=3232320,PL=0,JI=0,LA=0,DU=396,EN=G711u,DE=G711u

Also i dont have any publish package on my Db stored, what im missing?

Some tips on what to do?

My Homer receives P-RTPP-stat but not showing X-Rtp stats on homer screen.

thank u a lot from now for ur good work and hour help!

Here is a full BYE packet on Homer BYE -->

2017-08-29 11:07:38 +0200 : 111.111.111.111:6231 -> 200.000.110.100:5060
BYE sip:mod_sofia@11111118.20.4:5060 SIP/2.0
Via: SIP/2.0/UDP 111111111:6231;branch=z9hG4bK-cc0aded;rport
From: <sip:11111111@11111111:6231>;tag=4cf8a71ecc1c81b3i0
To: "91111111" <sip:1111111@Domain.es>;tag=D7jr4t9Nt15Um
Call-ID: 44f5daa4-073c-1236-94be-fe43e96724ad
CSeq: 101 BYE
Max-Forwards: 70
User-Agent: Cisco/SPA112-1.3.5(004p)
P-RTP-Stat: PS=1622,OS=259520,PR=1001,OR=160160,PL=0,JI=0,LA=0,DU=20,EN=G711u,DE=G711u
Content-Length: 0

**Comment by adubovikov** [comment]
Be sure that the P-RTP-Stats extracted and stored into x-rtp field
sorry, but this is not an issue, please ask in the mail list how to do it.

**Comment by KyleHyde6** [comment]
Can i pay for some info about how to configure captagent to solve this
issue ?

**Comment by adubovikov** [comment]
you can do similar as here:

https://github.com/sipcapture/homer/wiki/Example%3A-RTCPXR

but again, this is not a captagent requirement. This should be done in the sipcapture module of kamailio or opensips

if you want to do some customization or you have trouble to configure kamailio's config, please send an request to support@sipcapture.org

Thank you!
