### ISSUE TITLE
After some time captagent stops forwarding packets, logs [ERR] conf_function.c:164 ERROR: eval_expr: too many expressions (101) over and over

### ISSUE THREAD

**Issue by dancapper** [sipcapture/captagent#148]
After some hours, captagent one one of our capture nodes starts logging this to the syslog over and over:

Sep 14 13:51:14 nthc-homercapture captagent[11288]: [ERR] conf_function.c:164 ERROR: eval_expr: too many expressions (101)
Sep 14 13:51:14 nthc-homercapture captagent[11288]: #015
Sep 14 13:51:14 nthc-homercapture captagent[11288]: [ERR] conf_function.c:94 WARNING: do_action: error in expression

It stops forwarding packets when this happens also
Restarting captagent restores service.

**Comment by dancapper** [comment]
Further - looks like it happened again overnight and recovered on its own (no action taken) after a few hours.  I will check our other capture nodes

**Comment by SipSeb** [comment]
I can confirm this problem. After I reconfigured my captagent to capture on two interfaces (two profiles in socket_pcap.conf), this message appears after a few seconds running. The host running captagent gets about 30-40 Mbits of traffic. I didn't see the message before when running only with one interface.

From looking into the code, it is something with recursing over something. Haven't found out yet what exactly it is doing there.

**Comment by dancapper** [comment]
I am using multiple interfaces on the host where this occurs also. That may be the trigger.

**Comment by adubovikov** [comment]
inside we use same pointer to the functions structure from different threads. Need to make a dedicated for each.

**Comment by SipSeb** [comment]
Is there an ETA for a fix? Or should I work around it by running multiple captagent instances on the machine?

**Comment by adubovikov** [comment]
i can take look only next week, currently on the way to AsterConf.RU

**Comment by jenniferakemi** [comment]
We too have this issue - and are also capturing on multiple interfaces. 
I have this issue on the captagent running 6.2.11 but not on the captagent running 6.2.0.2. (However the one running version: 6.2.0.2 is currently also not parsing RTCP properly, so there may be some config differences as well.)

**Comment by kYroL01** [comment]
@jenniferakemi IMHO the "not parsing RTCP properly" is a different problem, related with RTCP parser. Do u have a scenario to evidence this incomplete parsing ? A pcap could be great to fix the wrong or missing parsing.

**Comment by jenniferakemi** [comment]
Oh sorry kYroL01, I just wanted to comment to say I was also experiencing the OP issue, I realize the RTCP thing is another issue entirely - I was just mentioning it because it might mean that the fact that 6.2.11 has the OP issue and 6.2.0.2 does not have the OP issue is a red herring (I obviously have something else going wrong on 6.2.0.2 -- I was planning to update to 6.2.11 on that one as well, but now I'm going to wait until OP issue is resolved).

**Comment by kYroL01** [comment]
Now I understand better the scenario. I think you're right and we have to look also if in 6.2.11 RTCP have the same parsing problem or not.
Thanks

**Comment by jenniferakemi** [comment]
kYroL01, sorry for confusion, my 6.2.11 instance does not have the RTCP parsing problem - it is correctly parsing the RTCP. I'm going to wait until the OP issue is resolved before updating both to 6.2.11 though.

I have 2 machines that are both monitoring the same ports (so same input). They are both capturing on multiple interfaces.

machine #1 runs 6.2.11 - sometimes doesn't forward packets at all and gets an error eval_expr: too many expressions (101). When it does work, RTCP is also parsed correctly.
machine #2 runs 6.0.2.2 - works all the time, I never see the 101 error, but RTCP is not parsed correctly. (but having the flow all the time trumps having working RTCP so I'm waiting for a fix to OP before upgrading to fix RTCP) 
Thanks

**Comment by games130** [comment]
did anyone try to run multiple instance of the captagent as a temporary solution -- (as mention by SipSeb commented on Sep 21)
does this solve the problem? I am encountering the same issue, captagent capturing on 6 interfaces.
If it is a temporary solution, may i ask how do we run multiple instance of captagent ?

Thank You

**Comment by SipSeb** [comment]
We run one captagent instance per interface now, and the problem has disappeared.

We have a configuration directory for each instance, specifying the interface, target and stuff, and then there is a systemd unit file for each one, specifying the configuation to load. Pretty straightforward.

**Comment by lmangani** [comment]
Is the `101` error still happening when using 6.3.x?

**Comment by mpavlin** [comment]
Hi

I am using 6.3.0 and got this error 

root@voip:/var/log# /usr/local/captagent/sbin/captagent -v
version: 6.3.0

Logs:

Feb 16 06:25:06 voip captagent[4954]: [ERR] conf_function.c:164 ERROR: eval_expr: too many expressions (1435)
Feb 16 06:25:06 voip captagent[4954]: [ERR] conf_function.c:94 WARNING: do_action: error in expression
Feb 16 06:25:06 voip captagent[4954]: [ERR] conf_function.c:164 ERROR: eval_expr: too many expressions (1435)


Conf: 

<profile name="socketspcap_sip_eth1" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="eth1"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                    <value>port 5060</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_sip_eth3" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="eth3"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                    <value>port 5060</value>
                </param>
            </settings>
        </profile>




capture[pcap] {

        # here we can check source/destination IP/port, message size
        if(msg_check("size", "100")) {

            #Do parsing
            if(parse_sip()) {
                #Can be defined many profiles in transport_hep.xml

                if(!send_hep("hepsocket")) {
                    clog("ERROR", "Error sending HEP!!!!");
                }

                if(sip_has_sdp())
                {
                        #Activate it for RTCP checks
                        if(!check_rtcp_ipport())
                        {
                                clog("ERROR", "ALREADY EXIST");
                        }
                }

                #Duplicate all INVITEs to JSON transport
                # if(sip_is_method() && sip_check("method","INVITE")) {
                #    #Can be defined many profiles in transport_json.xml
                #    if(!send_json("jsonsocket")) {
                #       clog("ERROR", "Error sending JSON!!!");
                #    }
                # }
            }
        }
        drop;
}

**Comment by adubovikov** [comment]
can you please share the socket_pcxp.xml ?

**Comment by mpavlin** [comment]
Here you go, complete file

[socket_pcap.xml.txt](https://github.com/sipcapture/captagent/files/1736574/socket_pcap.xml.txt)

**Comment by adubovikov** [comment]
if you make one profile with dev = any ? does it work well ?

**Comment by mpavlin** [comment]
No packets are captured with dev=any, that's why I created two profiles, as proposed in one of the past issues here.

**Comment by adubovikov** [comment]
how much packets do you have on interfaces ?

**Comment by mpavlin** [comment]
Average:        IFACE   rxpck/s   txpck/s      rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
Average:         eth3      368.45      0.00         67.76      0.00      0.00      0.00        3.55         0.06
Average:         eth1     1023.16      0.00       351.85      0.00      0.00      0.00       2.35         0.29
Average:         eth0        1.19        1.11            0.09      0.72      0.00      0.00       0.00         0.00

**Comment by dancapper** [comment]
We found interface bonding (in the O/S) works for capturing multiple
interfaces

**Comment by mpavlin** [comment]
I used NIC bonding in the past directly with kamailio  v3 and had a lot of problems there also. Sometimes Kamailio  did not capture some packets from one interface member in that bond ( tcpdump showed those packets...). With new fresh installation I wanted to have setup without bond, but it looks like captagent is not that stable....

**Comment by adubovikov** [comment]
Do you use kamailio in "RAW SOCKET" mode ?

**Comment by adubovikov** [comment]
ok, but why you are writing about "a lot problems there". Kamailio is in this case just a receiver of HEP packets. The captagent capture it and send it. If you see that some packets are missed, check if they has been delivered over HEP protocol to kamailio.

**Comment by mpavlin** [comment]
As I wrote in the past I used kamailio directly on bonded interface, without captagent. In this new setup I wanted to use captagent, as it could capture 2 interfaces with SIP signalling and 3rd one with ISUP. 
But I am having stability issues with captagent on basic 2 interace capture, as you see. Today my logs are again full of 

Feb 21 09:13:16 voip captagent[15508]: [ERR] conf_function.c:164 ERROR: eval_expr: too many expressions (559)

**Comment by crashza** [comment]
I have recently noticed these logs too (I also capture on multiple interfaces),I started investigating as NMS started too complain about high memory usage and seems mem usage started same time as these log entries. Let me know if there is anything i can contribute to finding the root cause

**Comment by jenniferakemi** [comment]
Just wanted to comment that on a new machine using nic bonding of 3 interfaces, running 1 instance of captagent 6.3.0 i have the "too many expressions" error. I guess I will go back to running 3 instances of captagent. (when doing this I did not have any issues)

Here's my socket_pcap.xml
```
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
	<profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
	    <settings>
		<param name="dev" value="bond0"/>
		<param name="promisc" value="true"/>
		<param name="reasm" value="false"/>
		<param name="tcpdefrag" value="false"/>
		<param name="capture-plan" value="sip_capture_plan.cfg"/>
		<param name="filter">
		    <value>port 5060-5091</value>
		</param>
	    </settings>
	</profile>
	<profile name="socketspcap_tls" description="TLS Socket" enable="false" serial="2014010402">
	    <settings>
		<param name="dev" value="any"/>
		<param name="promisc" value="true"/>
		<param name="reasm" value="false"/>
		<param name="tcpdefrag" value="true"/>
		<param name="capture-plan" value="tcp_capture_plan.cfg"/>
		<param name="filter">
		    <value>tcp port 5061</value>
		</param>
	    </settings>
	</profile>
	<profile name="socketspcap_rtcp" description="RTCP Socket" enable="true" serial="2014010402">
	    <settings>
		<param name="dev" value="bond0"/>
		<param name="promisc" value="true"/>
		<param name="reasm" value="false"/>
		<!-- size in MB -->
		<param name="ring-buffer" value="20"/>
		<!-- for rtp && rtcp < 250 -->
		<param name="snap-len" value="256"/>
		<param name="capture-filter" value="rtcp"/>
		<param name="capture-plan" value="rtcp_capture_plan.cfg"/>
		<param name="filter">
		    <value>portrange 10000-30000 and len >=50 </value>
		</param>
	    </settings>
	</profile>
    </module>
</document>
```

**Comment by nward** [comment]
Another datapoint - please let me know if I can provide any more info, or contribute data in some way.

I noticed this issue today in our infrastructure - I had not noticed it before and our logging indicates that we haven't seen this at all back as far as I searched - April 2018.

About 6 hours prior to this happening, we moved from a single SBC (Linux, running SEMS, captagent runs here) with 3 interfaces (user, core, provider), to 2 SBCs with 2 interfaces each (user, core) + (provider, core). Our "core" interface has our SIP server (Kamailio), and the SBC sees 2 seperate calls - user>core and core>provider for each actual phone call.

Additionally, the SBCs use addresses on dummy0 rather than the physical NIC address for signalling/media.

Since starting the captagent process, one SBC had an IP address added to dummy0, but, no other network changes (i.e. no interfaces added, removed, etc.)

One SBC had errors ramp up over time, the other came in spikes. I've attached a chart of log message frequency.

Both captagent processes are still running, the issue appear to resolve itself. Happy to get a core or something if that's useful.

![screen shot 2018-08-16 at 3 34 33 pm](https://user-images.githubusercontent.com/43847/44185838-02c6fa00-a16a-11e8-92a9-0ddb91eede3e.png)

**Comment by Rico29** [comment]
Hello,
Any news on this bug ?

**Comment by adubovikov** [comment]
does it stop after last patches  ?
