### ISSUE TITLE
MikroTIK and TZSP

### ISSUE THREAD

**Issue by adubovikov** [sipcapture/captagent#153]
During last workshop  at AsterConf.RU we have found that packet's pointer doesn't show to begin of the ethernet header and therefore we have some garbage during SIP parsing. Need to check and fix.

**Comment by adubovikov** [comment]
if the guys can provide us the pcap with tzsp (SIP) data , that we have tried convert to HEP during Aserconf, it will be awesome.

**Comment by adubovikov** [comment]
Just to show the latest "working scenario"
https://mum.mikrotik.com/presentations/NL16/presentation_3876_1479372782.pdf

**Comment by adubovikov** [comment]
so, after some time we have received the TZSP packets from our partner and all works as expected:
here is the configuration:

/ip firewall mangle
add action=sniff-tzsp chain=prerouting log=yes log-prefix="Sip Sniff " \
   port=5060 protocol=udp sniff-target=XXX.XXX.XXX.XXX sniff-target-port=\
   37008

So, all to all users of mikroTIK, please take the latest git of captagent and retest it.

Thank you and thank you our friends from Voicenter.co.il.

**Comment by swoga** [comment]
Hello,

I tried to send SIP data with MikroTik to captagent and had the problem that the data could not be parsed, because the link_offset was wrong.
`[DEBUG] socket_pcap.c:764 Link offset interface type [113] [113] [16]`

After setting `<param name="dev" value="any"/>` to `<param name="dev" value="eth0"/>` in the `socket_pcap.xml` it worked.
`[DEBUG] socket_pcap.c:764 Link offset interface type [1] [1] [14]`

Now I only have a problem with the IP addresses...
![image](https://user-images.githubusercontent.com/3697291/31996389-a065a6d2-b988-11e7-8153-14c81c8670ec.png)

**Comment by adubovikov** [comment]
you should use socket_collector to get all TZSP packets, not a raw socket.

**Comment by ameurbendriss** [comment]
hello,
i have the same problem when ysing tzsp, IP adresse are not displayed correctly.
did you  solve the issue?

**Comment by adubovikov** [comment]
do you use the collector or raw socket ?

**Comment by ameurbendriss** [comment]
I have tried to load socket_collector , but got the same issue, here is the configuration 
 

<configuration name="modules.conf" description="Modules">
            <modules>

                <load module="transport_hep" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="database_hash" register="local"/>
                <load module="protocol_rtcp" register="local"/>
                <load module="socket_pcap" register="local"/>    
                <load module="protocol_rtcpxr" register="local"/>
                <load module="socket_collector" register="local"/>
                <load module="socket_tzsp" register="local"/>

**Comment by Requium** [comment]
Got the same problem, and the config as above on captagent.xml, as anyone solved and can share the solution :S, thanks in advancement.
