### ISSUE TITLE
Cannot turn off promisc mode in socket/pcap

### ISSUE THREAD

**Issue by shripchenko** [sipcapture/captagent#157]
grep promisc captagent/src/modules/socket/pcap/socket_pcap.c

>>profile_socket[profile_size].promisc = 1;
>>					else if (!strncmp(key, "promisc", 7) && !strncmp(value, "true", 4))
>>						profile_socket[profile_size].promisc = 1;

**Comment by kYroL01** [comment]
Try after this https://github.com/sipcapture/captagent/commit/0cbc66a6b5fef8f16f00d8b72b69f3e208a202fb

Maybe is the initialization value

**Comment by shripchenko** [comment]
it works.
thx!
