### ISSUE TITLE
centos 5 installation

### ISSUE THREAD

**Issue by slife80** [sipcapture/captagent#160]
Hello, i'm unable to install captagent on centos 5 64bit, does someone have an installation steps to follow? Can you help me? Thanks a lot!!!

**Comment by lmangani** [comment]
Hi @slife80 I see you also commented on other threads where those details are available, my suggestion is to try HEPlify, our GO capture agent if you are having difficulties with Captagent.

**Comment by slife80** [comment]
Hi, thank you very much for your answer, does it support also qos reports on homer? That's what i'm looking for. Thank you

**Comment by negbie** [comment]
Yes it does
