### ISSUE TITLE
captagent don't capture rtp statictic

### ISSUE THREAD

**Issue by agicblack** [sipcapture/captagent#163]
I take statistics from mvts sr-s4000 with the help of captagent, I do not see the rtp statistics, and also some packages are lost, sometimes there is no "invite" or any other, through "tcpdump" they are.
default config files

**Comment by agicblack** [comment]
if I use sngrep I see everything.

sngrep portrange 5060-5090 -H udp:127.0.0.1:9060 --no-interface  -q

**Comment by lmangani** [comment]
Hi Agic,

You might want to give HEPlify a try i you're not familiar with the modular
configuration needs of Captagent.


Kind Regards,

Lorenzo Mangani
*Managing Director and Core Dev*

QXIP BV - Capture Engineering
Amsterdam, The Netherlands

Desk: +31-20-8080468 / +1 260-632-7227
Mobile: +31-6-46032730
Email: info@qxip.net

Find our more about HOMER, PCAPTURE, CAPTAGENT and all our Services and
Solutions at http://qxip.net

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential or
legally privileged information. Any unauthorized review, use, disclosure or
distribution is prohibited. If you are not the intended recipient,
please contact
the sender by reply e-mail and destroy all copies of this original message.

**Comment by agicblack** [comment]
sngrep I can not use.
I need to also work correctly captagent
[agent.zip](https://github.com/sipcapture/captagent/files/1575429/agent.zip)

**Comment by lmangani** [comment]
There is no RTP support in OSS Captagent, just RTCP and User-Agent Generated media reports. 
If you need RTP Analytics, please contact sales@qxip.net
