### ISSUE TITLE
Captagent install failure

### ISSUE THREAD

**Issue by waynemillskidals** [sipcapture/captagent#169]
Hello,

ive recently used the homer-installer script which has installed homer fine but it doesn't incude installing Captagent.

When following the install steps of captagent, when progressing to the ./configure it fails with the following
```

checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for pthread_create in -lpthread... yes
checking for dlopen in -ldl... yes
checking for XML_ParserCreate in -lexpat... yes
checking for pcap_open_live in -lpcap... yes
checking for json_object_get in -ljson... no
checking for json_object_get in -ljson-c... yes
checking for yywrap in -lfl... yes
configure: checking for LiBUV and Header files...
checking uv.h usability... no
checking uv.h presence... no
checking for uv.h... no
configure: error: uv.h headers not found.
[root@homer5 captagent]# 

```

I am running CentOS 7 

Any ideas why this is failing? i believe all the dependencies have been installed

Thanks

**Comment by kYroL01** [comment]
Hi @waynemillskidals .
You need to install [libuv](https://github.com/libuv/libuv) library.

Install that and I think you solve the issue.
Br

**Comment by waynemillskidals** [comment]
Hello, 

ive installed captagent before on Centos 7 and never had to install libuv separately and followed exactly the same process as before.

There is no easy information on how to install libuv library? i have downloaded this libuv-v1.19.1.tar.gz and extracted but the documentation is not clear how this libaray is installed.

 I dont believe this issue is closed

**Comment by lmangani** [comment]
Hey Wayne,
This is mentioned in the Wiki and valid for all modern captagent versions.
Here's a link: https://github.com/sipcapture/captagent/wiki/Installation

We also have packages for CaptAgent on github, in case you want to try them. If you compile you want to see the following when running `configure` and see it succeed:
```
checking uv.h usability... yes
checking uv.h presence... yes
checking for uv.h... yes
```
_(Depending on your needs, you might want to try HEPlify instead which has basically no requirements)_

**Comment by waynemillskidals** [comment]
Hi Lorenzo

I did follow the steps as per your Wiki but this happens

 yum -y install json-c-devel expat-devel libpcap-devel flex-devel automake libtool bison libuv-devel flex
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repo.uk.bigstepcloud.com
 * extras: repo.uk.bigstepcloud.com
 * updates: repo.uk.bigstepcloud.com
Package json-c-devel-0.11-4.el7_0.x86_64 already installed and latest version
Package expat-devel-2.1.0-10.el7_3.x86_64 already installed and latest version
Package 14:libpcap-devel-1.5.3-9.el7.x86_64 already installed and latest version
Package flex-devel-2.5.37-3.el7.x86_64 already installed and latest version
Package automake-1.13.4-3.el7.noarch already installed and latest version
Package libtool-2.4.2-22.el7_3.x86_64 already installed and latest version
Package bison-3.0.4-1.el7.x86_64 already installed and latest version
No package libuv-devel available.
Package flex-2.5.37-3.el7.x86_64 already installed and latest version

**Comment by lmangani** [comment]
Wayne,

In the wiki we mention if your repo does not provide the libuv packages you can use ours:
https://github.com/sipcapture/captagent/tree/master/dependency/centos/7

Have you attempted so yet?

**Comment by waynemillskidals** [comment]
not sure what im doing wrong but im struggling
```

sudo rpm -i https://github.com/sipcapture/captagent/blob/master/dependency/centos/7/libuv-1.8.0-1.el7.centos.x86_64.rpm
error: /var/tmp/rpm-tmp.u9hSJj: not an rpm package (or package manifest): 
```
Strange thing is, i never had to do this before so has captagent changed that now requires this library?

**Comment by lmangani** [comment]
Yes, as mentioned in the Wiki core functionality uses libuv. Try downloading the package locally and installing from file, github might stream it with the wrong headers to avoid being used as CDN, or add a repository which provides libuv for your OS (epel perhaps? not sure) If this is an issue, there's HEPlify which instead requires next to nothing and covers much of the same work at similar cycle cost.

**Comment by waynemillskidals** [comment]
Tried that – downloaded from your git page and then installed, same issue..

ls -l |grep lib
-rw-r--r--. 1 root root  39024 Feb 13 20:55 libuv-1.8.0-1.el7.centos.x86_64.rpm
-rw-r--r--. 1 root root  39156 Feb 13 20:56 libuv-devel-1.8.0-1.el7.centos.x86_64.rpm

sudo rpm -i libuv-1.8.0-1.el7.centos.x86_64.rpm
error: libuv-1.8.0-1.el7.centos.x86_64.rpm: not an rpm package (or package manifest):

☹

**Comment by lmangani** [comment]
Wayne, I don't understand the issue, assuming there's an issue with the file (are you downloading raw?) this same RPM is available at a dozen locations, pick any -ie: https://downloads.datastax.com/cpp-driver/centos/7/dependencies/libuv/v1.8.0/

**Comment by waynemillskidals** [comment]
That now works..

The issue is your GitHub rpm files do not work..  i thought that was obvious in the outputs that i attached?

anyway, after the link you sent i installed the rpm for libuv and it works so i guess you need to fix your wiki to have rpm files .. initially though i overlooked that libuv was required as i never had to install this before when I did a HOMER installation with Captagent

output of configure appears succesful so i will finish it up tomorrow

`
captagent 6.3.0

Build directory............. :
Installation prefix......... : /usr/local/captagent
HEP Compression............. : no
IPv6 support.................: no
HEP SSL/TLS................. : no
Flex........................ : flex
Bison....................... : bison -y

Build with REDIS............ : no
Build with MySQL............ : no
Build with PCRE............. : no
Build with LibUV............ : yes
Build with EPAN............. : no
Build with TLS.............. : no

`
