### ISSUE TITLE
TCP error

### ISSUE THREAD

**Issue by DigiDaz** [sipcapture/captagent#173]
When using TCP as the protocol for the HEP I find many of these in my log:

[ERR] transport_hep.c:768 tcp send failed! err=-32

I also get lots of missing parts of the sip dialog

This is the latest capture agent from github.

**Comment by lmangani** [comment]
Hi @DigiDaz whats on the receiving side and how is it configured? Are you observing errors there too?

**Comment by DigiDaz** [comment]
Is homer, I'm pretty sure its never even going there, I will do some ngrepping and find out.

**Comment by adubovikov** [comment]
be sure you have enabled tcp defrag in the captagent and und you use the
latest version of kamailio or opensips

**Comment by kYroL01** [comment]
Close for inactivity. Reopen if necessary. 
Thanks
