### ISSUE TITLE
captagent -D never ends

### ISSUE THREAD

**Issue by jmgonzalezp** [sipcapture/captagent#175]
Hello! I have started using captagent together with my traffic capture system, everytime a file is closed, I run captagent -D cap_ file to send the information to kamailio. I think it is running quite good but the problem I have is that the captagent -D processes never end, and I have to kill them manually. Can you help me to solve this problem?

Thanks.

**Comment by kYroL01** [comment]
Hello @jmgonzalezp .
It depends on signal at the end of `pcap_open_offline`.
If the function send a `close` signal at the end of file, the file closed automatically; if not, maybe it could be closed manually. I need to check better. 
Your ideal behaviour is that, one time a file is completely read, must be close, right ?

**Comment by jmgonzalezp** [comment]
Hello @kYroL01 , that's right, what I expect is if I run captagent in that way, the process should stop when it finishes reading the pcap file.

**Comment by kYroL01** [comment]
Bug fixed by 2da152ca501c2739178e96a53189c58aab21cb8a

Reopen if necessary
