### ISSUE TITLE
Unable to kill captagent on Debian 9

### ISSUE THREAD

**Issue by Joonake** [sipcapture/captagent#177]
Dear Community,

I have encountered a problem where I am unable to kill captagent process with SIGTERM on freshly installed debian 9. Only way to kill the process is to use SIGKILL, which is kind of extreme. I was able to reproduce this problem on four differenct machines, all running same version of debian:

```
# uname -a
Linux hostname_here 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
```
I have installed captagent with following commands:

```
apt-get install build-essential git automake libtool libexpat1-dev libpcap-dev libjson-c-dev libtool automake flex bison libuv1-dev
cd /usr/src/
git clone https://github.com/sipcapture/captagent.git
cd captagent
./build.sh
./configure
make && make install
```
And after I start captagent in daemon mode `/usr/local/captagent/sbin/captagent -f /usr/local/captagent/etc/captagent/captagent.xml -d`, SIGTERM won't kill the process:

```
# pgrep captagent
22724
# kill 22724
# pgrep captagent
22724
```
Any idea how to debug this issue more?

**Comment by kYroL01** [comment]
Hi @Joonake .
I'm trying to reproduce you error. II'll setting Debian 9 on VM and let u know asap.

**Comment by kYroL01** [comment]
@Joonake .
If you demonize a process, you want that process runs in background and forever, usually do not die or get restarted, waits for requests and respond to them.
So if you can kill a demonized process as you do for a normal program, this behaviour is in contrast with the _demonization_.
So, if you stat captagent in a daemon mode, you want the process running in backgound and can't be closed with a SIGTERM or SIGINT signal.
This is not an issue.
Btw, if you don't want to kill using SIGKILL, you can use `pkill -SIGTERM captagent`, and the sigterm does the work. Try and let me know.

**Comment by Joonake** [comment]
Thank you for your reply. I tested `pkill -SIGTERM captagent` but it did not work either. The main problem is with systemd and repository provided service-file. If you use service-file from repository and try to run `service captagent stop`, it will try to send SIGTERM and waits for 90 seconds. When this fails, systemd will kill the process with SIGKILL which is not clean and may even corrupt something? Quote from `man systemd.service`:

```
If a service is asked to stop, but does not terminate in the specified time, it will be terminated forcibly via SIGTERM, and after another timeout of equal duration with SIGKILL
```

If SIGKILL is really the only way to stop the process, it should be added to systemd service-file to avoid 90 second timeout:
`KillSignal=SIGKILL`

**Comment by lmangani** [comment]
@Joonake thanks for the valuable input - this sounds like the correct approach, we'll doublecheck it internally for inclusion. If you wish feel free to send a PR the change so you can get credit for finding it ;)

**Comment by kYroL01** [comment]
Close by https://github.com/sipcapture/captagent/pull/178

Thank you!
