### ISSUE TITLE
Capturing packets w/invalid fragmentation

### ISSUE THREAD

**Issue by nevian427** [sipcapture/captagent#180]
Hi,
We have Avaya system which sends us fragmented packets aprox 300b long. Problem that it is NOT mark them as fragments and CaptAgent and HEPlify process only first part at best.
I showed these at AsterConf Moscow last year :)
SNGrep can cope with it.
btw FreeSWITCH also can parse them but internal capture called too early and sends incorrect data
[maxus_fragments.pcap.gz](https://github.com/sipcapture/captagent/files/2209506/maxus_fragments.pcap.gz)

**Comment by adubovikov** [comment]
Hi,
Did you actiivate udp/tcp defragmentation in the socket_pcap profile ?

**Comment by kYroL01** [comment]
Close for inactivity. Reopen if necessary
