### ISSUE TITLE
missing protocol check?

### ISSUE THREAD

**Issue by btriller** [sipcapture/captagent#191]
https://github.com/sipcapture/captagent/blob/e0703365aab2b68a0f75549a75cd58a344b07f17/src/modules/socket/pcap/socket_pcap.c#L268-L273

Does this check search for an [ERSPAN Type II](https://tools.ietf.org/html/draft-foschiano-erspan-03#section-4.2) header? @adubovikov

**Comment by btriller** [comment]
If so, can we move it up here:
https://github.com/sipcapture/captagent/blob/e0703365aab2b68a0f75549a75cd58a344b07f17/src/modules/socket/pcap/socket_pcap.c#L201-L212
and prevent the possibility of a segfault for small packets?

**Comment by btriller** [comment]
This would also fix non RFC compliance concerning static [IPv4 header length](https://tools.ietf.org/html/rfc791#section-3.1) (where we have to implement IPv6 support for GRE packets).

**Comment by btriller** [comment]
Anyone? @adubovikov @kYroL01 @lmangani

**Comment by lmangani** [comment]
@btriller sorry to keep you waiting, on it

**Comment by adubovikov** [comment]
> [captagent/src/modules/socket/pcap/socket_pcap.c](https://github.com/sipcapture/captagent/blob/e0703365aab2b68a0f75549a75cd58a344b07f17/src/modules/socket/pcap/socket_pcap.c#L268-L273)
> 
> Lines 268 to 273 in [e070336](/sipcapture/captagent/commit/e0703365aab2b68a0f75549a75cd58a344b07f17)
> 
>  else if(ntohs((uint16_t)*(&cooked)) == COOKED_INT) 
>  { 
>          /* LINK_OFFSET + IPV4_SIZE + GRE_ERSPAN + ERSPAN INFO */ 
>          hdr_offset = hdr_preset = link_offset + IPV4_SIZE + ERSPANHDR_SIZE ; 
>          vlan = 3; 
>  }     
> Does this check search for an [ERSPAN Type II](https://tools.ietf.org/html/draft-foschiano-erspan-03#section-4.2) header? @adubovikov

this does check for COOKED device = linux "any"

**Comment by adubovikov** [comment]
> If so, can we move it up here:
> [captagent/src/modules/socket/pcap/socket_pcap.c](https://github.com/sipcapture/captagent/blob/e0703365aab2b68a0f75549a75cd58a344b07f17/src/modules/socket/pcap/socket_pcap.c#L201-L212)
> 
> Lines 201 to 212 in [e070336](/sipcapture/captagent/commit/e0703365aab2b68a0f75549a75cd58a344b07f17)
> 
>  if (profile_socket[loc_index].erspan == 1) { 
>    memcpy(&tmp_ip_proto, (packet + ETHHDR_SIZE + IPPROTO_OFFSET), 1); 
>    if (tmp_ip_proto == GRE_PROTO) { 
>      memcpy(&tmp_ip_len, (packet + ETHHDR_SIZE), 1); 
>      tmp_ip_len = (tmp_ip_len & IPLEN_MASK) * 4; // LSB 4 bits: length in 32-bit words 
>      //printf("ip.proto: %u, ip header len: %u\n", tmp_ip_proto, tmp_ip_len); 
>      erspan_offset = ETHHDR_SIZE + tmp_ip_len + GREHDR_SIZE; // Ethernet + IP + GRE 
>      pkthdr->len -= erspan_offset; 
>      pkthdr->caplen -= erspan_offset; 
>      packet += erspan_offset; 
>    } 
>  } If so, can we move it up here:
[captagent/src/modules/socket/pcap/socket_pcap.c](https://github.com/sipcapture/captagent/blob/e0703365aab2b68a0f75549a75cd58a344b07f17/src/modules/socket/pcap/socket_pcap.c#L201-L212)

Lines 201 to 212 in [e070336](/sipcapture/captagent/commit/e0703365aab2b68a0f75549a75cd58a344b07f17)

 if (profile_socket[loc_index].erspan == 1) { 
   memcpy(&tmp_ip_proto, (packet + ETHHDR_SIZE + IPPROTO_OFFSET), 1); 
   if (tmp_ip_proto == GRE_PROTO) { 
     memcpy(&tmp_ip_len, (packet + ETHHDR_SIZE), 1); 
     tmp_ip_len = (tmp_ip_len & IPLEN_MASK) * 4; // LSB 4 bits: length in 32-bit words 
     //printf("ip.proto: %u, ip header len: %u\n", tmp_ip_proto, tmp_ip_len); 
     erspan_offset = ETHHDR_SIZE + tmp_ip_len + GREHDR_SIZE; // Ethernet + IP + GRE 
     pkthdr->len -= erspan_offset; 
     pkthdr->caplen -= erspan_offset; 
     packet += erspan_offset; 
   } 
 } 

and prevent the possibility of a segfault for small packets?
> 
> and prevent the possibility of a segfault for small packets?

to prevent segfaut, IMHO better check the len and discard if *end is over of (ETHHDR_SIZE + IPPROTO_OFFSET)

**Comment by btriller** [comment]
> > [captagent/src/modules/socket/pcap/socket_pcap.c](https://github.com/sipcapture/captagent/blob/e0703365aab2b68a0f75549a75cd58a344b07f17/src/modules/socket/pcap/socket_pcap.c#L268-L273)
> > Lines 268 to 273 in [e070336](/sipcapture/captagent/commit/e0703365aab2b68a0f75549a75cd58a344b07f17)
> > else if(ntohs((uint16_t)_(&cooked)) == COOKED_INT)
> > {
> > /_ LINK_OFFSET + IPV4_SIZE + GRE_ERSPAN + ERSPAN INFO */
> > hdr_offset = hdr_preset = link_offset + IPV4_SIZE + ERSPANHDR_SIZE ;
> > vlan = 3;
> > }
> > Does this check search for an [ERSPAN Type II](https://tools.ietf.org/html/draft-foschiano-erspan-03#section-4.2) header? @adubovikov
> 
> this does check for COOKED device = linux "any"

This looks odd to me, since
* link type is detected before `pcap_loop` is set up. So I'd rather not expect it to change while capturing (maybe a tailored PCAP is read)
https://github.com/sipcapture/captagent/blob/e070336/src/modules/socket/pcap/socket_pcap.c#L820-L863
* `cooked` is already mapped after link and IPv4 header
https://github.com/sipcapture/captagent/blob/e070336/src/modules/socket/pcap/socket_pcap.c#L255

**Comment by kYroL01** [comment]
Hi all. @btriller

> link type is detected before pcap_loop is set up
Right, and captagent correctly set the link_offset to 16 (aka ISDNHDR_SIZE).

> cooked is already mapped after link and IPv4 header
I think this scenario is to check if a vlan header is present, so this is why there is also
`memcpy(&cooked, (packet + link_offset + IPV4_SIZE + 2), 2);`
and then the following check is for `LINK_OFFSET + IPV4_SIZE + GRE_ERSPAN + ERSPAN INFO`.
@adubovikov correct ?

For what I understand you say this last case is useless in this position ?
