### ISSUE TITLE
msg_check by IP

### ISSUE THREAD

**Issue by sergey-safarov** [sipcapture/captagent#193]
This is feature request
In current implementation is possible check message ip source IP or destination IP. In my case need check IP not matter source or destination. I must combine check like
```
if (msg_check("dst_ip", "8.8.8.8") or msg_check("src_ip", "8.8.8.8")) {
}
```
Could you add check by IP. In this case possible to write rule like
```
if (msg_check("ip", "8.8.8.8")) {
}
```

Also will be great to check with network address not only IP. like
```
if (msg_check("ip", "192.168.1.0/24")) {
}
```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/46006e0c4961088b4d12a42e14cdc8252aa4687e

if (msg_check("any_ip", "8.8.8.8")) {
}

or you can do by octet match:
if (msg_check("ip", "192.168.0.")) {
}
