### ISSUE TITLE
msg_check by source IP works as not expected

### ISSUE THREAD

**Issue by sergey-safarov** [sipcapture/captagent#194]
I want print logs message when received SIP message received from IP othe, then.
To do this i use construction, like
```
                if(!msg_check("src_ip", "8.8.8.8")) {
                        clog("ERROR", "This message never printed!!!");
                }
```
And this message never printed.

**Comment by adubovikov** [comment]
sorry is it still broken ?

**Comment by kYroL01** [comment]
Close for inactivity. Reopen if necessary
