### ISSUE TITLE
how to support captagent with pf_ring?

### ISSUE THREAD

**Issue by nageshnath** [sipcapture/captagent#198]
i can see in wiki captagent has support for pf_ring (Multiple incoming sockets (PCAP, RAW, PF_RING, RX-RING, FILE).So i tried loading socket_pfring module from captagent.xml,but when i run captagent got error 
root@tb906imsoam01> ./captagent 
[NOTICE] Loaded core config
[ERR] modules.c:75 dlopen error [/usr/local/captagent/lib/captagent/modules/socket_pfring.so: cannot open shared object file: No such file or directory]
So there is library missing for pf_ring .I saw in source code as well as in rpm installed one there is no lib for socket_pfring.
So please let me know how can i enable support for pf_ring .

**Comment by kYroL01** [comment]
Hi. Did u try to install pf_ring library manually ? Does captagent continue to complains ?

**Comment by adubovikov** [comment]
just my 5 cents, are you sure that you really need pf_ring ? It makes sense if you have more than 50MB/s of SIP traffic and even in this case better to use RX_RING V3 with fanout,  In other cases libpcap more than enough

**Comment by nageshnath** [comment]
@kYroL01:
My aim is run captagent with pf_ring to enhance capture performance of captagent.
Question here is to run captagent with pf_ring what is the procedure?

Actually i installed pf_ring rpm's and started pf_ring as well.
what i did is i installed pf_ring rpm's then started pf_ring .After that if i run captagent but i am not sure captagent is using pf_ring.My captagent was using socket_pcap ,So i searched internet and i came to know that we need to do some configuration in captagent to run it with pf_ring.
So i saw there is one module "socket_pfring" under captagent.xml but when i load this moudle and start captagent ,captagent throws following error..
root@tb906imsoam01> ./captagent
[NOTICE] Loaded core config
[ERR] modules.c:75 dlopen error [/usr/local/captagent/lib/captagent/modules/socket_pfring.so: cannot open shared object file: No such file or directory]

So when i saw module under installed dir there was no mudole with socket_pfring.

So i am not sure how to use pf_ring with captagent.

**Comment by kYroL01** [comment]
@nageshnath Got it. I'll check it asap.
Thanks

**Comment by adubovikov** [comment]
for pf_ring - as I wrote, you can open a virtual interface and read all packets, but again, to use PF_RING make no sense, since captagent has RX_RING support with fanout.
