### ISSUE TITLE
Error using TLS

### ISSUE THREAD

**Issue by lfzaracho** [sipcapture/captagent#202]
Hi, I'm getting these errors when I try to use TLS:

homer[26244]: ERROR: tls [tls_util.h:42]: tls_err_ret(): TLS accept:error:1408F10B:SSL routines:ssl3_get_record:wrong version number
homer[26244]: BUG: tls [tls_server.c:1303]: tls_read_f(): IO error (0) Success
homer[26244]: ERROR: <core> [core/tcp_read.c:1505]: tcp_read_req(): ERROR: tcp_read_req: error reading - c: 0x7ff2374a6b18 r: 0x7ff2374a6b98 (-1)

I'm using Kamailio 5.2.2 and captagent 6.2 (last version).

I already tried changing the "method" param in kamailio's TLS config but I get the same result.

Could you help me please?

Thanks in advance

**Comment by lmangani** [comment]
The exchange seems unsupported. What ciphers are you using?

**Comment by lfzaracho** [comment]
Here is the list: 

cipher_list = “TLSv1+HIGH : !SSLv2 : kECDH+AES128 : kEDH+AES128 : HIGH : !aNULL : !eNULL : !3DES : !RC4 : !aNULL : !MD5 : @STRENGTH”

I've tried too with the default tls configuration created in the compilation of kamailio, with no success.

**Comment by kYroL01** [comment]
As written on [Wiki](https://github.com/sipcapture/captagent/wiki/TLS#supported) we provide only two supported cipher suite for TLS in captagent. It seems you want to use _Elliptic-curve Diffie–Hellman_ and _Elliptic Diffie–Hellman_ that's impossibile to decrypt in captagent.

**Comment by essodjolo** [comment]
@lfzaracho Have you found a solution for you issue? I'm facing a similar issue while trying to encrypt the traffic between captagent and homer sipcature host.
