### ISSUE TITLE
what is minimum installation required to run captagent?

### ISSUE THREAD

**Issue by nageshnath** [sipcapture/captagent#203]
If i install rpm for captagent for centos ,what is minimum rpm's required?
As i think only libuv and captagent not even libuv-devel?Please correct me.
I want to know list of minimum required dependent rpms if i install captagent rpm.

**Comment by lmangani** [comment]
Hi @nageshnath 
We don't have automated `rpm` or `deb` packages for captagent yet but we're planning to do so for our new agents. The `-dev` packages are indeed only required to compile the agent, then only the actual libraries are required. This said, you might want to consider `HEPlify` which comes as single binary.

**Comment by nageshnath** [comment]
i am using the captagent rpm as mentioned in below link:
https://github.com/sipcapture/captagent/releases
captagent-6.3.0-1.x86_64.rpm

if i check the dependent :
root@node> rpm -qpR captagent-6.3.0-1.x86_64.rpm 
json-c
expat
libpcap
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1

So i can see only json-c,expat and lipcap are required for captagent .Even devel rpm's of json-c,expat and libpcap are not required.
As i m installing in centos 7 so libuv also required.And devel rpm of libuv not required.
Am i correct if not then let me know dependent ?
