### ISSUE TITLE
SIP PARSE ERROR, debian, 3CX

### ISSUE THREAD

**Issue by syadnom** [sipcapture/captagent#204]
debian stretch, installed from repos v6.1.0.20
Changed the transport_hep to update capture-host and capture-port
no other changes.

[ERR] protocol_sip.c:369 bad parsing
[ERR] protocol_sip.c:350 SIP PARSE ERROR [-1]

PBX is 3CX.  sngrep and sipgrep both handle this fine and can send to a Homer5 instance.  I'm wanting to move to captagent for QoS.

Thanks.

**Comment by kYroL01** [comment]
Hi @syadnom . Do you have a pcap to reproduce the issue ? How is your config files ? Thank you

**Comment by kYroL01** [comment]
Any news ?

**Comment by syadnom** [comment]
no, I had to table this because I'm having some trouble installing the rest
of the stack.

**Comment by kYroL01** [comment]
All the Homer stack ?

**Comment by syadnom** [comment]
Yes, want to run homer 7 in EC2 and feed it with captagent.

**Comment by kYroL01** [comment]
Maybe @adubovikov and @lmangani could help u.

**Comment by lmangani** [comment]
@syadnom feel free to open an issue on the main `homer` repo for guidance, or on `homer7-docker` if you believe this being a docker related issue

**Comment by syadnom** [comment]
More a matter of what I need minimally to do call logs with mos .  I really
don’t need or want a giant stack, just the basics so I have records for
when I sent tickets to upstreams and I can hunt down poor calls by low mos .

**Comment by kYroL01** [comment]
Did u follow [this](https://github.com/sipcapture/homer/wiki/Quick-Install) ?
Which part are u struggling with ?

**Comment by syadnom** [comment]
Yes, but there are a dozen options.

Seems that I want Homer8 and Heplify server, but what else is needed?

**Comment by lmangani** [comment]
@syadnom there's no Homer 8 yet :) Just 7 so you should pick the backend you're most comfortable operating or interested in discovering - its either InfluxDB or Prometheus for stats, and PgSQL for data.
If you need a ready-to-run kind of thing, checkout hepic.tel perhaps?
