### ISSUE TITLE
i am using the captagent rpm as mentioned in below link:

### ISSUE THREAD

**Issue by nageshnath** [sipcapture/captagent#205]
i am using the captagent rpm as mentioned in below link:
https://github.com/sipcapture/captagent/releases
captagent-6.3.0-1.x86_64.rpm

if i check the dependent :
root@node> rpm -qpR captagent-6.3.0-1.x86_64.rpm 
json-c
expat
libpcap
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1

So i can see only json-c,expat and lipcap are required for captagent .Even devel rpm's of json-c,expat and libpcap are not required.
As i m installing in centos 7 so libuv also required.And devel rpm of libuv not required.
Am i correct if not then let me know dependent ?

_Originally posted by @nageshnath in https://github.com/sipcapture/captagent/issues/203#issuecomment-476551566_

**Comment by kYroL01** [comment]
`libuv` is required due to transport side. If u don't have HEP will be not send out.
