### ISSUE TITLE
capturing diameter traffic but getting error in captagent

### ISSUE THREAD

**Issue by nageshnath** [sipcapture/captagent#206]
I want to capture diameter traffic via captagent.I am generating diameter traffic via seagull and traffic contains cer,cea,sar,saa messages,even tried with ccr,cca messages.Getting error as below when i run captagent binary:

root@SOUTHLAKEcscfcif01> ../../../sbin/captagent 
[NOTICE] Loaded core config
[DEBUG] modules.c:50 Loading module: [transport_hep]
[NOTICE] Loaded transport_hep
[DEBUG] modules.c:50 Loading module: [protocol_sip]
[NOTICE] Loaded protocol_sip
[DEBUG] modules.c:50 Loading module: [database_hash]
[NOTICE] Loaded database_hash
[DEBUG] modules.c:50 Loading module: [protocol_rtcp]
[NOTICE] Loaded protocol_rtcp
[DEBUG] modules.c:50 Loading module: [protocol_diameter]
[NOTICE] Loaded protocol_diameter
[DEBUG] modules.c:50 Loading module: [socket_pcap]
[NOTICE] Loaded socket_pcap
[DEBUG] socket_pcap.c:573 Activating device: any

[DEBUG] socket_pcap.c:609 Activated device: [any]

[NOTICE] Using filter: (port 3868)
[DEBUG] conf_function.c:453 find_export_record: found <msg_check> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <is_diameter> in module protocol_diameter [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <parse_diameter_to_json> in module protocol_diameter [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <send_hep> in module transport_hep [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
[DEBUG] captagent.c:316 The Captagent is ready
[DEBUG] socket_pcap.c:764 Link offset interface type [113] [113] [16]
[ERR] protocol_diameter.c:126 Error: NO DIAMETER packet found

[ERR] protocol_sip.c:132 This is not DIAMETER

[ERR] protocol_diameter.c:126 Error: NO DIAMETER packet found

[ERR] protocol_sip.c:132 This is not DIAMETER

[ERR] protocol_diameter.c:126 Error: NO DIAMETER packet found

[ERR] protocol_sip.c:132 This is not DIAMETER

[ERR] protocol_diameter.c:126 Error: NO DIAMETER packet found

[ERR] protocol_sip.c:132 This is not DIAMETER

My configuration is as below:
**captagent.xml:**
<?xml version="1.0"?>
<document type="captagent/xml">
        <configuration name="core.conf" description="CORE Settings" serial="2014024212">
            <settings>
                <param name="debug" value="10"/>
                <param name="version" value="2"/>
                <param name="serial" value="2014056501"/>
                <param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
                <param name="daemon" value="false"/>
                <param name="syslog" value="false"/>
                <param name="pid_file" value="/var/run/captagent.pid"/>
                
                <param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
                <param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
                <param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
                <param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
                <param name="chroot" value="/usr/local/captagent/etc/captagent"/>
            </settings>
        </configuration>
        <configuration name="modules.conf" description="Modules">
            <modules>

                <load module="transport_hep" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="database_hash" register="local"/>
                <load module="protocol_rtcp" register="local"/>
                <load module="protocol_diameter" register="local"/>
                <load module="socket_pcap" register="local"/>

                
                

                
        </modules>
        </configuration>
</document>

**socket_pcap.xml:**
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_diameter" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="false"/>
                <param name="capture-plan" value="diameter_capture_plan.cfg"/>
                <param name="filter">
                    <value>port 3868</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_tls" description="TLS Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="eth1"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="true"/>
                <param name="capture-plan" value="tcp_capture_plan.cfg"/>
                <param name="filter">
                    <value>tcp port 5061</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_rtcp" description="RTCP Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="eth1"/>
                <param name="reasm" value="false"/>
                
                <param name="ring-buffer" value="20"/>
                
                <param name="snap-len" value="256"/>
                <param name="capture-filter" value="rtcp"/>
                <param name="capture-plan" value="rtcp_capture_plan.cfg"/>
                <param name="filter">
                    <value>port </value>
                </param>
            </settings>
        </profile>
    </module>
</document>

**protocol_diameter.xml :**
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="protocol_diameter" description="DIAMETER Protocol" serial="2014010402">
        <profile name="proto_diameter" description="PROTO DIAMETER" enable="true" serial="2014010402">
          <settings>
            
            <param name="diameter-version" value="1"/>
          </settings>
        </profile>
    </module>
</document>

please let me know what wrong i am doing or what is missing?
It's a bit urgent.

**Comment by kYroL01** [comment]
@nageshnath Can u pass a pcap with portion of diameter traffic ? This should be faster to check. For sure is a dissector issue, maybe the dissector must be update.
Thank you

**Comment by nageshnath** [comment]
Hi Michele ,
i sent u mail with pcap

**Comment by kYroL01** [comment]
Thank you so much. 
I'll check asap.

**Comment by kYroL01** [comment]
Solved by 1ca3af24dc13bc8e0a1366959b531cd966310b29

**Comment by nageshnath** [comment]
Hi michele,
I reported you problem of diameter not transmitting to ip,port configured in output_json.xml .
Can you let me know if u got some pointers on that?

Regards
Nagesh

**Comment by kYroL01** [comment]
I replied you in private.
Please dont write again in this closed issue.
Thank you so much
