### ISSUE TITLE
Does Captagent suppoprt ipv6 packet capturing?can it capture packet from mirrored port on cloud?

### ISSUE THREAD

**Issue by nageshnath** [sipcapture/captagent#207]
Hi ,
i have tested capturing ipv4 packets,it works fine .Then i tried capturing ipv6 but captagent was not captuting it,though Heplify was capturing fine.
Similarly i tried capturing packet from mirrored port on cloud but it was not capturing .
Does captagent support ipv6 capturing and capturing from mirrored port on cloud?

**Comment by adubovikov** [comment]
yes, it does, just check your ip filter: i.e. ip6
