### ISSUE TITLE
How do i set up to capture for all ports ?

### ISSUE THREAD

**Issue by nageshnath** [sipcapture/captagent#209]
Hi ,
I want to remove port filter and wanna make it generic capturing for all ports.Here i am capturing for sip at any interface and any port.I think captagent is capturing trying to capture packets but i saw error while captagent start saying error for port filter.
Following is my socket_pcap.xml:
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                
            </settings>
        </profile>
        <profile name="socketspcap_tls" description="TLS Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="true"/>
                <param name="capture-plan" value="tcp_capture_plan.cfg"/>
                <param name="filter">
                    <value>tcp port 5061</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_sctp" description="SCTP Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="true"/>
                <param name="ipv4fragments" value="true"/>
                <param name="ipv6fragments" value="true"/>
                <param name="proto-type" value="sip"/>
                <param name="capture-plan" value="isup_capture_plan.cfg"/>
                <param name="filter">
                    <value>proto 132</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_rtcp" description="RTCP Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                
                <param name="ring-buffer" value="20"/>
                
                <param name="snap-len" value="256"/>
                <param name="capture-filter" value="rtcp"/>
                <param name="capture-plan" value="rtcp_capture_plan.cfg"/>
                <param name="filter">
                    <value>portrange 10000-30000 and len >=50 </value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_diameter" description="DIAMETER Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="eth1"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="true"/>
                <param name="capture-plan" value="diameter_capture_plan.cfg"/>
                <param name="filter">
                    <value>tcp port 3868</value>
                </param>
            </settings>
        </profile>
    </module>
</document>

Error for port filter:

root@SOUTHLAKEcscfcif01> ./captagent -f etc_bak/captagent/captagent.xml 
[NOTICE] Loaded core config
[DEBUG] modules.c:50 Loading module: [transport_hep]
[NOTICE] Loaded transport_hep
[DEBUG] modules.c:50 Loading module: [protocol_sip]
[NOTICE] Loaded protocol_sip
[DEBUG] modules.c:50 Loading module: [database_hash]
[NOTICE] Loaded database_hash
[DEBUG] modules.c:50 Loading module: [protocol_rtcp]
[NOTICE] Loaded protocol_rtcp
[DEBUG] modules.c:50 Loading module: [protocol_diameter]
[NOTICE] Loaded protocol_diameter
[DEBUG] modules.c:50 Loading module: [output_json]
[NOTICE] Loaded output_json
[DEBUG] modules.c:50 Loading module: [socket_pcap]
[NOTICE] Loaded socket_pcap
[DEBUG] socket_pcap.c:675 Activating device: any

[DEBUG] socket_pcap.c:711 Activated device: [any]

[NOTICE] Using filter: b©
[ERR] socket_pcap.c:758 Failed to compile filter "b": syntax error
[DEBUG] conf_function.c:453 find_export_record: found <msg_check> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <parse_sip> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <send_hep> in module transport_hep [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <sip_has_sdp> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <check_rtcp_ipport> in module database_hash [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] socket_pcap.c:866 Link offset interface type [113] [113] [16]
[DEBUG] captagent.c:316 The Captagent is ready
[DEBUG] socket_pcap.c:906 STARTING STATS....
[NOTICE] No packet drops on interface [any], index: [0], received: [11]

**Comment by adubovikov** [comment]
check you filter  - it's wrong

**Comment by nageshnath** [comment]
Hi ,
i mentioned my socket_pcap.xml in my previous comment ,not sure it's now showing now,anyway following way i commented out port filter ,so that i can capture for all ports .
what wrong am i doing ?
i wanted to know that only what is the correct way?
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                
            </settings>
        </profile>

**Comment by kYroL01** [comment]
If you don't want port filter, just remove it.

**Comment by nageshnath** [comment]
socket_pcap.xml:
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
            </settings>
        </profile>


removing also i tried ..but still getting error:
[NOTICE] Using filter: b	
[ERR] socket_pcap.c:758 Failed to compile filter "b    ": syntax error

as can be seen in following log:
root@SOUTHLAKEcscfcif01> ./captagent -f etc_bak/captagent/captagent.xml 
[NOTICE] Loaded core config
[DEBUG] modules.c:50 Loading module: [transport_hep]
[NOTICE] Loaded transport_hep
[DEBUG] modules.c:50 Loading module: [protocol_sip]
[NOTICE] Loaded protocol_sip
[DEBUG] modules.c:50 Loading module: [database_hash]
[NOTICE] Loaded database_hash
[DEBUG] modules.c:50 Loading module: [protocol_rtcp]
[NOTICE] Loaded protocol_rtcp
[DEBUG] modules.c:50 Loading module: [protocol_diameter]
[NOTICE] Loaded protocol_diameter
[DEBUG] modules.c:50 Loading module: [output_json]
[NOTICE] Loaded output_json
[DEBUG] modules.c:50 Loading module: [socket_pcap]
[NOTICE] Loaded socket_pcap
[DEBUG] socket_pcap.c:675 Activating device: any

[DEBUG] socket_pcap.c:711 Activated device: [any]

[NOTICE] Using filter: b	
[ERR] socket_pcap.c:758 Failed to compile filter "b    ": syntax error
[DEBUG] conf_function.c:453 find_export_record: found <msg_check> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <parse_sip> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <send_hep> in module transport_hep [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <sip_has_sdp> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <check_rtcp_ipport> in module database_hash [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] conf_function.c:453 find_export_record: found <clog> in module protocol_sip [/opt/SMAW/INTP/install/IMSPimslb/linking/lib64/impl]
[DEBUG] captagent.c:316 The Captagent is ready
[DEBUG] socket_pcap.c:866 Link offset interface type [113] [113] [16]
[DEBUG] socket_pcap.c:906 STARTING STATS....

**Comment by adubovikov** [comment]
in the filter just do:
<filter>ip</filter>
it will capture all packets

**Comment by nageshnath** [comment]
> in the filter just do:
> ip
> it will capture all packets
can you give me a sample socket_pcap.xml to refer? want to remove port filter but wanna keep others like interface and all will be there like eth1.

**Comment by adubovikov** [comment]
```
<profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2019010402">
            <settings>
                <param name="dev" value="eth1"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                    <value>ip</value>
                </param>
            </settings>
        </profile>
```

**Comment by adubovikov** [comment]
in worse case: 
port not 1
or portrange 1-65535

**Comment by nageshnath** [comment]
> in worse case:
> port not 1
> or portrange 1-65535

By giving portrange ,its not giving failed to compile filter error.

i tried with ip but this is not working and  giving error :
<param name="filter">
                    <value>ip</value>
                </param>

[NOTICE] Using filter: bYػ 
[ERR] socket_pcap.c:758 Failed to compile filter "bY": syntax error

**Comment by adubovikov** [comment]
sorry, but can you paste your socket_pcap.xml ?

**Comment by nageshnath** [comment]
> sorry, but can you paste your socket_pcap.xml ?

<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                    <value>ip</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_tls" description="TLS Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="true"/>
                <param name="capture-plan" value="tcp_capture_plan.cfg"/>
                <param name="filter">
                    <value>tcp port 5061</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_sctp" description="SCTP Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="true"/>
                <param name="ipv4fragments" value="true"/>
                <param name="ipv6fragments" value="true"/>
                <param name="proto-type" value="sip"/>
                <param name="capture-plan" value="isup_capture_plan.cfg"/>
                <param name="filter">
                    <value>proto 132</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_rtcp" description="RTCP Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                
                <param name="ring-buffer" value="20"/>
                
                <param name="snap-len" value="256"/>
                <param name="capture-filter" value="rtcp"/>
                <param name="capture-plan" value="rtcp_capture_plan.cfg"/>
                <param name="filter">
                    <value>portrange 10000-30000 and len >=50 </value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_diameter" description="DIAMETER Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="eth1"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="tcpdefrag" value="true"/>
                <param name="capture-plan" value="diameter_capture_plan.cfg"/>
                <param name="filter">
                    <value>tcp port 3868</value>
                </param>
            </settings>
        </profile>
    </module>
</document>

**Comment by adubovikov** [comment]
@nageshnath 
sorry, I have asked for socket_pcap.xml and not broken bpf filter. If you wanna see how to use bpf filter, I sugest you read this article: http://biot.com/capstats/bpf.html
