### ISSUE TITLE
FreeBSD Install

### ISSUE THREAD

**Issue by overload08** [sipcapture/captagent#215]
Hi.

Is it possible to install Captagent on pfSense ?
If yes, how ?

Thank's

**Comment by lmangani** [comment]
Hi @overload08 I guess its possible to cross-compile for FreeBSD with some adjustments, but its not part of our scope so you would have to try. It's probably much easier to do this with [heplify](https://github.com/sipcapture/heplify) so I would give that a shot. Thanks!
