### ISSUE TITLE
RPM build and Travis fail

### ISSUE THREAD

**Issue by kYroL01** [sipcapture/captagent#216]
1) RPM for Centos fail cause error for `libfl`
```
checking for flex... no
checking for lex... no
configure: error: captagent requires but cannot find libfl
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
```
even if flex is installed `flex-devel.x86_64 0:2.5.37-6.el7`

2) I saw that Travis is always complaining on building the captagent.
```
E: Failed to fetch http://ppa.launchpad.net/linuxjedi/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting
The command "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -" failed and exited with 1 during .
```

**Comment by cervajs** [comment]
change build.sh
yum -y install gcc make git json-c-devel expat-devel libpcap-devel flex-devel ...
to
yum -y install gcc make git json-c-devel expat-devel libpcap-devel flex-devel flex ...

(add flex package)

**Comment by kYroL01** [comment]
Thanks @cervajs for the hint. I'm doing it
