### ISSUE TITLE
protocol_sip.c:132 Couldnot find this call

### ISSUE THREAD

**Issue by changzx** [sipcapture/captagent#218]
dear：
  
![image](https://user-images.githubusercontent.com/42836671/65502954-81a66e80-def6-11e9-8f17-b3ff602d2195.png)

**Comment by kYroL01** [comment]
Hello @changzx 

Can u be more specific ? How are u using captagent ? If u can, past me also the `captagent.xml` so I can help u better.

Thank you

**Comment by lmangani** [comment]
@changzx this very simply means the agent is seeing RTCP reports it cannot pair with a session, suggesting NAT or other mechanism are at play (or perhaps you restarted the agent and it captured reports for calls it did not see INVITE/200 SDP for)

Closing this as a non-issue
