### ISSUE TITLE
captagent6 install

### ISSUE THREAD

**Issue by Mickaelh51** [sipcapture/captagent#22]
Hi,
there is maybe an issue with Captagent6 in debian 8.
I must change the file: /usr/src/captagent/src/modules/transport/json/transport_json.c

I've changed json lib: from #include <json/json.h> to #include <json-c/json.h>
And I installed others dependances: libjson-c-dev / bison / flex

I don't know if it's a bug or a bad json dependance.

bye

**Comment by adubovikov** [comment]
hi,
sorry, tags are missed, can you make merge request ?

**Comment by Mickaelh51** [comment]
Re,
tags are missed ? What is the tags ? ;)

For make merge request, I'm ok to make it . But I don't sure about this bug. I'm not C dev ;)
Thanks

**Comment by adubovikov** [comment]
your text:

I've changed json lib: from #include to #include

**Comment by Mickaelh51** [comment]
I'm sorry!!!
 I don't see this mistake ;)
I've changed json lib: from #include<json/json.h>  to #include <json-c/json.h>

**Comment by adubovikov** [comment]
:-)

try to use preview....

**Comment by Mickaelh51** [comment]
lol thanks for your advise
