### ISSUE TITLE
RPM build is not exported to host filesystem

### ISSUE THREAD

**Issue by cervajs** [sipcapture/captagent#220]
build is run with 
docker run -v $(pwd)/:/tmp/build -v $(pwd)/:/scripts --entrypoint=/scripts/install.sh --name centos7 centos:centos7

but in build.sh
final rpm is copied to ${EXEC_DIR}
cp -v *.rpm ${EXEC_DIR}

but 
export EXEC_DIR=$(pwd)  is /

so its not written to host filesystem

solution is i.e. 
cp -v *.rpm /tmp/build

**Comment by lmangani** [comment]
the key directory is `$(pwd)/:/scripts` which is indeed a double. We'll clear this up on the next release

**Comment by kYroL01** [comment]
Thanks @cervajs . I think this but is related with https://github.com/sipcapture/captagent/issues/216
I'll modify the rpm asap .
Thank you

**Comment by lmangani** [comment]
Please retest using the latest `build.sh` this should be fixed! Thanks for your report
