### ISSUE TITLE
captagent -D import SIP packets or HEP packets

### ISSUE THREAD

**Issue by sipsorcery** [sipcapture/captagent#221]
I use WireShark to capture some SIP traces from devices that aren't able to send HEP packets to my Homer7 server.

Can I use the command below to import the SIP packets on the Homer7 server or is that intended to import HEP packets?

`captagent -D ~/attended_transfer3.pcapng`

**Comment by kYroL01** [comment]
Hi @sipsorcery .
The command `-D` itself it is used by captagent to read a single **generic** pcap file.
If you're able to send HEP packet to Homer 7 server means the problem is in another place IMHO.
Did you correctly modify your transport_hep.xml with the correct Homer 7 server IP ?

Thanks

**Comment by sipsorcery** [comment]
Thx for the response. I converted my `pcapng` file to a `pcap` file and now seem to be getting somewhere.

**Comment by kYroL01** [comment]
Ok glad to hear that!
