### ISSUE TITLE
Homer 7 and ACME Packet (IP-to-IP) assistance with captagent

### ISSUE THREAD

**Issue by dmigardos** [sipcapture/captagent#231]
Hi Team,

I have upgraded to Homer 7 and needed assistance to configure IP-to-IP using the captagent for ACME SBCs.

**Comment by kYroL01** [comment]
Hello @dmigardos is simple IP-to-IP tunneling right ? Do you have a pcap file so I can validate it ? I'm adding this to captagent

**Comment by dmigardos** [comment]
Hi Michele,

I have attached a trace.

**Comment by kYroL01** [comment]
I'm sorry but I don't see any file here :(

**Comment by dmigardos** [comment]
Hi Michele,

Sorry, I attached it to the previous email but it might have been
stripped.  Here is a link to the file.

https://drive.google.com/file/d/1y2OvPuVxordQhU2yMJEAWffamQzsCxjk/view?usp=sharing

**Comment by kYroL01** [comment]
No problem. Thanks.

**Comment by kYroL01** [comment]
Hello @dmigardos I added the patch by fc22fc498f1fecbf00ba676433861ddfd84ae34a
Could you please test and let me know if it works ?
Thank you

**Comment by dmigardos** [comment]
Hi Michele,

I think we are close.

I set an acme to send capture traffic to homer/captagent.

I now see calls from the acme in the gui but there are two problems (might
be related)

1) When I click on the call ID instead of the SIP Ladder popping up I just
see the progress circle gif going around and around but the SIP ladder
never shows.

2) when I click on the packet (ex: the invite packet) I see the following
at the end.  Like there are extra characters in each packet (ex:  c _y F F
)

m=audio 9632 RTP/AVP 18 0 8 101
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
c _y 	F F

**Comment by dmigardos** [comment]
Hi Michele,

Regarding the progress bar it only occurs with ip-to-ip packets.
 Packets/calls processed via heplify are showing fine.

Below is the full packet.

Thank you for your help and please let me know if you need anything else.

  -----------------------------

INVITE sip:3103935681@10.10.10.117 SIP/2.0
Via: SIP/2.0/UDP 10.100.10.198:5060;branch=z9hG4bK3qtqrb1038a1o0jqv4g1.1
From: "WIRELESS CALLER" <sip:3102318479@10.100.10.198:5060
>;tag=SDvnva401-gK0d387f72
To: <sip:3103935681@10.10.10.117>
Remote-Party-ID: "WIRELESS CALLER" <sip:3102318479@10.100.10.198:5060
>;privacy=off;screen=yes
X-Charge-Info: 3103935681;Rate=0.0003
Call-ID: SDvnva401-591841487ad902ba8c86303660e0f608-2duna33
CSeq: 26774 INVITE
Max-Forwards: 61
Allow:
INVITE,ACK,CANCEL,BYE,REGISTER,REFER,INFO,SUBSCRIBE,NOTIFY,PRACK,UPDATE,OPTIONS
Accept: application/sdp, application/isup, application/dtmf,
application/dtmf-relay,  multipart/mixed
Contact: <sip:10.100.10.198:5060;did=f6b.ce1f1a06;transport=udp>
Supported: timer,100rel,replaces
Session-Expires: 1800; refresher=uac
Min-SE: 90
Content-Length: 261
Content-Disposition: session; handling=required
Content-Type: application/sdp

76 3D 30
o=- 3776545124 12504 IN IP4 10.120.10.70
s=-
c=IN IP4 10.120.10.70
t=0 0
m=audio 7984 RTP/AVP 0 8 18 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20

Vi _ 8K K

-----------------------------

**Comment by adubovikov** [comment]
@kYroL01 I think here is wrong calculated lenght of full message, looks like the second IP header was not subtracted.

**Comment by kYroL01** [comment]
Ok let me check. Thanks

**Comment by kYroL01** [comment]
Now should be correct 42cfeb5813e02967881117815e6814cef3ad30cc
Please test and let me know.
Thank you!

**Comment by dmigardos** [comment]
Hi Michele,

I no longer see the additional characters when I click on the packet.

However, I still see the progress circle gif going around and around but
the SIP ladder never shows on IP-toIP packets only.   If I click on a
heplify packet it shows.  Want me to reach out to the homer team on this?
Do you have a link so I could contact them on?

**Comment by kYroL01** [comment]
Hi @dmigardos 

>>I no longer see the additional characters when I click on the packet.

Good, thanks for confirmation :)

>>However, I still see the progress circle gif going around and around but
the SIP ladder never shows on IP-toIP packets only

Could you please check on port 9063 (or 9062 if you use TCP) if the HEP packets are created ?

run `sudo ngrep -W byline -q -d any port 9063 -O hep.pcap` and attach me the pcap
change 9063 with 9062 if you put TCP on transport_hep.xml

If this is good then we can move the quetion to the Homer.

Thanks

**Comment by dmigardos** [comment]
Hi Michale,

The heplify packet is sent to the homerv7 server as such from OpenSIPs:
/usr/sbin/heplify -hs 172.16.166.251:9060 -dim OPTIONS -m SIP &

I ran the following on port 9060 on the capture server
ngrep -W byline -q -d any port 9060 -O hep.pcap

I also ran the following to capture the packets from the acme on the
capture server
tcpdump -i any ip and not port 22 -s 2000 -w acme.pcap

This way you have a comparison of the packets from heplify and ip-to-ip

Since I wanted to keep the data private and not public only your gmail.com
account has access to download these files.

I put them in a zip:file located here:
https://drive.google.com/file/d/179KcpSFmdVfhYYzhToEgA2bDRUHjTfM9/view?usp=sharing

Thank you again for your time on this.

**Comment by kYroL01** [comment]
I sent you the request for the pcap

**Comment by dmigardos** [comment]
Thank you, just allowed access.

**Comment by adubovikov** [comment]
@dmigardos please open F12 (Web console) and check if you have any erros there

**Comment by kYroL01** [comment]
Great, checking ;)

**Comment by lmangani** [comment]
Also attach a screenshot or a gif displaying this progress bar, its unclear to me from the description.

**Comment by kYroL01** [comment]
Hi @dmigardos .

I took your original pcap, setup the `ip-to-ip` as I explained, and sent to a Homer instance
then I check one call-id (`SDe920001-6b0eece9f3e8c5249be57554b2d17df0-2duna33`) from your pcap and I can see correctly the call in Homer
![homer](https://user-images.githubusercontent.com/7222956/98009758-33041d00-1df6-11eb-9aa5-c573624dece4.png)

**Comment by dmigardos** [comment]
I have attached it to this email.  Let me know if you see it, if not I will
load it to drive

[image: image.png]

**Comment by lmangani** [comment]
@dmigardos you can drag and drop images in issues, they will be converted inline

**Comment by dmigardos** [comment]
Thank you.

**Comment by dmigardos** [comment]
Hi Michele,

What version of homer did you use for the test?  I'm using 7.8.5

**Comment by lmangani** [comment]
@dmigardos please follow up in order to understand the client-side issue:

- please open F12 (Web console) and check if you have any erros as the issue is triggered
- please paste a screenshot of the issue by dragging the image in your reply (github will do the rest)

**Comment by dmigardos** [comment]
Lorenzo,

No error from what I could see.

[image: image.png]

**Comment by adubovikov** [comment]
we dont see any pic

**Comment by dmigardos** [comment]
Hi Alexandr,

Here is the picture:
https://drive.google.com/file/d/1buAQbmsocDZ_bgK5fmwfKTpyFoGLx6Oc/view?usp=sharing

**Comment by adubovikov** [comment]
@dmigardos you are not on the console. Please follow the procedure!

**Comment by adubovikov** [comment]
@dmigardos please show the console and not the network tab :-)

**Comment by dmigardos** [comment]
Hi Alexandr,

I think all the work you and your team put in has IP-toIP working now.
After a reboot of the homer server, the ladder diagram now shows without
issues.   If anything changes I will let you know.

**Comment by adubovikov** [comment]
Perfect. Glad that it works now. Please star our project and I will close the ticket:
https://github.com/sipcapture/homer/stargazers

Have a nice day!
