### ISSUE TITLE
I do not receive data to my server Homer

### ISSUE THREAD

**Issue by wvalles3010** [sipcapture/captagent#236]
Hello good day,

Please your support, I have Homer version 7.7 installed on a Linux Centos server and also I have CaptAgent version 3 installed on an Asterisk 11 server (using chan_sip). I was receiving all the flow of calls to Homer without any problem, but now for no reason Homer stopped receiving information. My configuration file of the captagent.xml is the following:

<?xml version="1.0"?>
<document type="captagent/xml">
        <configuration name="core.conf" description="CORE Settings" serial="2014024212">
            <settings>
                <param name="debug" value="3"/>
                <param name="version" value="2"/>
                <param name="serial" value="2014056501"/>
                <param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
                <param name="daemon" value="false"/>
                <param name="syslog" value="false"/>
                <param name="pid_file" value="/var/run/captagent.pid"/>
                
                <param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
                <param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
                <param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
                <param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
                <param name="chroot" value="/usr/local/captagent/etc/captagent"/>
            </settings>
        </configuration>
    <configuration name="modules.conf" description="Modules">
        <modules>
                
                

                

                <load module="transport_hep" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="socket_pcap" register="local"/>
        </modules>
        </configuration>
</document>

Also, I run the following command to see the CaptAgent logs. The result is as follows:

/ usr / src / captagent / src / captagent -f /usr/local/captagent/etc/captagent/captagent.xml

[NOTICE] Loaded core config
[ERR] conf_function.c: 458 find_export_record: <check_rtcp_ipport> not found

parse error (17,26-27): unknown command, missing loadmodule?

ERROR: bad config file (1 errors)
[ERR] conf_function.c: 458 find_export_record: <is_rtcp> not found

parse error (40,14-15): unknown command, missing loadmodule?

[ERR] conf_function.c: 458 find_export_record: <is_rtcp_exist> not found

parse error (43.21-22): unknown command, missing loadmodule?

[ERR] conf_function.c: 458 find_export_record: <parse_rtcp_to_json> not found

parse error (46,27-28): unknown command, missing loadmodule?

ERROR: bad config file (4 errors)
WARNING: run_actions: null action list (rec_level = 5)
WARNING: run_actions: null action list (rec_level = 5)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)
WARNING: run_actions: null action list (rec_level = 3)

Could you please give me a hint on how to solve this problem?

Greetings

**Comment by wvalles3010** [comment]
Sorry, I forgot to paste all the content of my captagent.xml file, here I send all the content.

<?xml version="1.0"?>
<document type="captagent/xml">
        <configuration name="core.conf" description="CORE Settings" serial="2014024212">
            <settings>
                <param name="debug" value="3"/>
                <param name="version" value="2"/>
                <param name="serial" value="2014056501"/>
                <param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
                <param name="daemon" value="false"/>
                <param name="syslog" value="false"/>
                <param name="pid_file" value="/var/run/captagent.pid"/>
                
                <param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
                <param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
                <param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
                <param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
                <param name="chroot" value="/usr/local/captagent/etc/captagent"/>
            </settings>
        </configuration>
    <configuration name="modules.conf" description="Modules">
        <modules>
                
                

                

                <load module="transport_hep" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="socket_pcap" register="local"/>
        </modules>
        </configuration>
</document>

**Comment by kYroL01** [comment]
Hello @wvalles3010 . It seems you don't have the RTCP modules enabled in your `captagent.xml`
Try to enable also `<load module="protocol_rtcp" register="local"/>`
and let me know

Thank you!

**Comment by wvalles3010** [comment]
Hi Michele,

Thanks for your answer, I made the change you suggested and my captagent.xml looked like this:

<?xml version="1.0"?>
<document type="captagent/xml">
        <configuration name="core.conf" description="CORE Settings" serial="2014024212">
            <settings>
                <param name="debug" value="3"/>
                <param name="version" value="2"/>
                <param name="serial" value="2014056501"/>
                <param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
                <param name="daemon" value="false"/>
                <param name="syslog" value="false"/>
                <param name="pid_file" value="/var/run/captagent.pid"/>
                
                <param name="module_path" value="/usr/local/captagent/lib/captagent/modules"/>
                <param name="config_path" value="/usr/local/captagent/etc/captagent/"/>
                <param name="capture_plans_path" value="/usr/local/captagent/etc/captagent/captureplans"/>
                <param name="backup" value="/usr/local/captagent/etc/captagent/backup"/>
                <param name="chroot" value="/usr/local/captagent/etc/captagent"/>
            </settings>
        </configuration>
    <configuration name="modules.conf" description="Modules">
        <modules>
                <load module="protocol_rtcp" register="local"/>
                <load module="transport_hep" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="socket_pcap" register="local"/>
        </modules>
        </configuration>
</document>

Checking the logs now I see these errors:

[NOTICE] Loaded core config
[ERR] conf_function.c:458 find_export_record: <check_rtcp_ipport> not found 

parse error (17,26-27): unknown command, missing loadmodule?

ERROR: bad config file (1 errors)
[ERR] conf_function.c:458 find_export_record: <is_rtcp_exist> not found 

parse error (43,21-22): unknown command, missing loadmodule?

ERROR: bad config file (2 errors)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)
WARNING: run_actions: null action list (rec_level=4)

**Comment by kYroL01** [comment]
You miss also `database_hash.xml`
The complete (basic) modules to be enabled should be this
```
    <load module="transport_hep" register="local"/>
    <load module="protocol_sip" register="local"/>
    <load module="protocol_rtcp" register="local"/>
    <load module="database_hash" register="local"/>
    <load module="socket_pcap" register="local"/>
 ```
 
 Regards
 Michele

**Comment by wvalles3010** [comment]
Hello,

Add what you suggested to me.

    <load module="transport_hep" register="local"/>
    <load module="protocol_sip" register="local"/>
    <load module="protocol_rtcp" register="local"/>
    <load module="database_hash" register="local"/>
    <load module="socket_pcap" register="local"/>

But now I see these errors:

/usr/src/captagent/src/captagent -f /usr/local/captagent/etc/captagent/captagent.xml

[NOTICE] Loaded core config
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call

On the other hand, I made a couple of calls and my Homer server still does not receive information from my Asterisk server that has CaptAgent installed.

I will investigate from my side what else I can find.

**Comment by wvalles3010** [comment]
Hello everyone,

I'm afraid I still can't find a solution to my problem, my Homer server still doesn't receive information.

Checking the CaptAgent logs on my Asterisk server, I still see the following errors:

/usr/src/captagent/src/captagent -f /usr/local/captagent/etc/captagent/captagent.xml

[NOTICE] Loaded core config
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call
[ERR] protocol_sip.c:141 Couldnot find this call

Please could you give me some idea how to solve this.

Greetings

**Comment by wvalles3010** [comment]
Hello,

I just found the problem, it happens that my Homer server was receiving information through CapAgent, however, Homer is only showing 200 results of SIP calls, but it is NOT showing information greater than 200 results, my query is, how can I expand the "Call Sip Search" to show me for example 100000 results ?, Is this possible ?, I stay tuned.

Greetings

**Comment by kYroL01** [comment]
Hi @wvalles3010 . Thanks for this answer. So, yes, it's possible, but in this case I suggest you to directly open an issue to [Homer](https://github.com/sipcapture/homer/issues)  where you explain what you need to solve.

Thank you - I'm closing this one.

Greeting!
