### ISSUE TITLE
Installing Captagent on Debian 11 not working correctly

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/captagent#243]
Hello,

on Debian 11 i tried to git clone and compile captagent but it ends with an error:

First i installed the depencies:

_`apt-get install libexpat1-dev libpcap-dev libjson-c-dev libtool automake flex bison libgcrypt11-dev libuv1-dev libpcre3-dev libfl2 libfl-dev`
`apt-get install -y libgcrypt20 libgcrypt20-dev libssl-dev`
`apt-get install gcc`_

then i clone and try to compile

_`cd /usr/src`
`git clone https://github.com/sipcapture/captagent.git captagent`
`cd captagent`
`./build.sh`
`./configure --enable-ssl --enable-tls  --enable-ipv6`
`make && make install`_

and got this error output by executing "make && make install"

_`# make && make install
Making all in src
make[1]: Entering directory '/usr/src/captagent/src'
make  all-recursive
make[2]: Entering directory '/usr/src/captagent/src'
Making all in .
make[3]: Entering directory '/usr/src/captagent/src'
  CCLD     captagent
/usr/bin/ld: conf_function.o:/usr/src/captagent/src/../include/captagent/api.h:125: multiple definition of `module_list'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:125: first defined here
/usr/bin/ld: conf_function.o:/usr/src/captagent/src/../include/captagent/modules.h:30: multiple definition of `module_path'; captagent.o:/usr/src/captagent/src/../include/captagent/modules.h:30: first defined here
/usr/bin/ld: conf_function.o:/usr/src/captagent/src/../include/captagent/api.h:123: multiple definition of `hepmod'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:123: first defined here
/usr/bin/ld: modules.o:/usr/src/captagent/src/../include/captagent/modules.h:30: multiple definition of `module_path'; captagent.o:/usr/src/captagent/src/../include/captagent/modules.h:30: first defined here
/usr/bin/ld: modules.o:/usr/src/captagent/src/../include/captagent/api.h:125: multiple definition of `module_list'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:125: first defined here
/usr/bin/ld: modules.o:/usr/src/captagent/src/../include/captagent/api.h:123: multiple definition of `hepmod'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:123: first defined here
/usr/bin/ld: xmlread.o:/usr/src/captagent/src/../include/captagent/api.h:125: multiple definition of `module_list'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:125: first defined here
/usr/bin/ld: xmlread.o:/usr/src/captagent/src/../include/captagent/api.h:123: multiple definition of `hepmod'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:123: first defined here
/usr/bin/ld: capplan.o:/usr/src/captagent/src/conf_function.h:82: multiple definition of `modules'; conf_function.o:/usr/src/captagent/src/conf_function.h:82: first defined here
/usr/bin/ld: capplan.o:/usr/src/captagent/src/../include/captagent/modules.h:30: multiple definition of `module_path'; captagent.o:/usr/src/captagent/src/../include/captagent/modules.h:30: first defined here
/usr/bin/ld: capplan.o:/usr/src/captagent/src/../include/captagent/api.h:125: multiple definition of `module_list'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:125: first defined here
/usr/bin/ld: capplan.o:/usr/src/captagent/src/../include/captagent/api.h:123: multiple definition of `hepmod'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:123: first defined here
/usr/bin/ld: capplan.tab.o:/usr/src/captagent/src/conf_function.h:82: multiple definition of `modules'; conf_function.o:/usr/src/captagent/src/conf_function.h:82: first defined here
/usr/bin/ld: capplan.tab.o:/usr/src/captagent/src/../include/captagent/modules.h:30: multiple definition of `module_path'; captagent.o:/usr/src/captagent/src/../include/captagent/modules.h:30: first defined here
/usr/bin/ld: capplan.tab.o:/usr/src/captagent/src/../include/captagent/api.h:125: multiple definition of `module_list'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:125: first defined here
/usr/bin/ld: capplan.tab.o:/usr/src/captagent/src/../include/captagent/api.h:123: multiple definition of `hepmod'; captagent.o:/usr/src/captagent/src/../include/captagent/api.h:123: first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:624: captagent] Error 1
make[3]: Leaving directory '/usr/src/captagent/src'
make[2]: *** [Makefile:733: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/captagent/src'
make[1]: *** [Makefile:520: all] Error 2
make[1]: Leaving directory '/usr/src/captagent/src'
make: *** [Makefile:465: all-recursive] Error 1
`_

**Comment by ciscospirit** [comment]
if i try to use gcc-9 instead of gcc on Debian 11 (apt-get install gcc vs. apt-get install gcc-9) i got an error by command "./configure --enable-ssl --enable-tls --enable-ipv6":

_checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/usr/src/captagent':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details_

**Comment by kYroL01** [comment]
Thank you @ciscospirit .

1. Debian 11 has `gcc-10` by default, so if you install `apt-get install gcc`, it will install version **10**.
In this case you can solve it change this line https://github.com/sipcapture/captagent/blob/master/configure.ac#L115
with this
`CFLAGS="$CFLAGS -g -O0 -Wno-error -fcommon"`
and run again 
```
./build.sh
./configure --enable-ssl --enable-tls --enable-ipv6
make && make install
```

2. If you have installed `gcc-9` you have to _symlink_ the version 9 on Debian 11 in this way:
`sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc`
and then place the same line as before
`CFLAGS="$CFLAGS -g -O0 -Wno-error -fcommon"`

I think this will solve your problem - I tested on a Debian 11 VM

**Comment by ciscospirit** [comment]
i already tried this to change this Line 115 in /usr/src/captagent/configure.ac but still got the same problem.

make && make install is not working and bring out the above error.


i have this gcc installed:

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)

**Comment by kYroL01** [comment]
@ciscospirit 
I reproduced exactly the same situation on a new Debian11 and in the way I suggest you I solve the problem for gcc-10.
Could you please try from scratch again and install all the pkgs suggested ?
The `-Wno-error -fcommon` must do the trick here.

**Comment by ciscospirit** [comment]
Hello,

now it worked!
i rm the whole usr/src/captagent directory and git clone again captagent, made the edit in configure.ac and now all went through... looks like ./build.sh doesn't work well, if there is ./build already once executed in directory.

**Comment by kYroL01** [comment]
Thanks @ciscospirit for the test and the confirmation.
I'll do some test and probably I'll create a `debian11` branch with that fix in the `configure.ac` and put some comment about that.
Thanks a lot again.

**Comment by btriller** [comment]
I think there is already #239, which fixes this issue. @kYroL01

**Comment by adubovikov** [comment]
@btriller don't forget to star us :-) https://github.com/sipcapture/homer/stargazers

**Comment by adubovikov** [comment]
@ciscospirit and you as well :-) https://github.com/sipcapture/homer/stargazers

**Comment by kYroL01** [comment]
@btriller I test today and I'll merge it. Wanted to be sure this was tested more and have different feedback.
Thank you all! and as Alex said, star us :D

**Comment by btriller** [comment]
🌟
