### ISSUE TITLE
Multiple transport profiles

### ISSUE THREAD

**Issue by tuan-pham-hoiio** [sipcapture/captagent#251]
Hi, I am wondering if I could set up multiple profile to send HEP to multiple endpoints?
Saw https://github.com/sipcapture/captagent/issues/50 and seem like it possible.
However after multiple tries with this transport_hep.xml set up:
```
<?xml version="1.0"?>
<document type="captagent_module/xml">
  <module name="transport_hep" description="HEP Protocol" serial="2014010402">
    <profile name="hepsocket_homer" description="Transport HEP to homer" enable="true" serial="2014010402">
        <settings>
      <param name="version" value="3"/>
      <param name="capture-host" value="192.168.1.2"/>
      <param name="capture-port" value="9060"/>
      <param name="capture-proto" value="UDP"/>
      <param name="capture-id" value="2001"/>
      <param name="capture-password" value=""/>
      <param name="payload-compression" value="false"/>
        </settings>
    </profile>
    <profile name="hepsocket_sip3" description="Transport HEP to SIP3" enable="true" serial="2014010402">
        <settings>
      <param name="version" value="3"/>
      <param name="capture-host" value="192.168.1.3"/>
      <param name="capture-port" value="15060"/>
      <param name="capture-proto" value="UDP"/>
      <param name="capture-id" value="2001"/>
      <param name="capture-password" value=""/>
      <param name="payload-compression" value="false"/>
        </settings>
    </profile>
  </module>
</document>
```
Only the first profile (I have also switched them to check) get sent to. Can you check if I set anything wrong? Thank you.
I am using version 6.3.1 by the way.

**Comment by lmangani** [comment]
The solution is using the capture plan for the protocols of interest - that's where you can fork HEP to multiple targets.

Perhaps you should ask the SIP3 forum or use their "agents" since apparently that's your goal? 👎

**Comment by tuan-pham-hoiio** [comment]
Thanks for your quick answer, I will look into it.
About the suggestion, since I have already successfully use Captagent with SIP3 (both use sip protocol along with HEP with exact same setup), I believe the issue lies at Captagent. Hence, raising the issue here.

**Comment by kYroL01** [comment]
Hi @tuan-pham-hoiio there's no issue.
As Lorenzo said, if you define an additional profile you have then to check [here](https://github.com/sipcapture/captagent/blob/master/conf/captureplans/sip_capture_plan.cfg#L8) 
and define additional `send_hep` with the name of your additional profile.

**Comment by tuan-pham-hoiio** [comment]
Oh, thank you a lot for pointing that out.
I didn't notice I miss that.

**Comment by kYroL01** [comment]
Please star our repo if you did not have done yet. 
Thank you

**Comment by tuan-pham-hoiio** [comment]
Oh, sure. :+1:
