### ISSUE TITLE
Can not compile - Missing files?

### ISSUE THREAD

**Issue by botts99** [sipcapture/captagent#253]
Making all in modules/protocol/sip
make[3]: Entering directory `/usr/src/captagent/src/modules/protocol/sip'
Making all in .
make[4]: Entering directory `/usr/src/captagent/src/modules/protocol/sip'
  CC       protocol_sip_la-protocol_sip.lo
In file included from protocol_sip.c:37:0:
protocol_sip.h:30:18: fatal error: pcre.h: No such file or directory
 #include <pcre.h>
                  ^
compilation terminated.
make[4]: *** [protocol_sip_la-protocol_sip.lo] Error 1
make[4]: Leaving directory `/usr/src/captagent/src/modules/protocol/sip'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/usr/src/captagent/src/modules/protocol/sip'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/src/captagent/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/captagent/src'
make: *** [all-recursive] Error 1
[root@freepbx captagent]#

**Comment by adubovikov** [comment]
Hello @botts99 

you should add pcre-devel (FreePBX is CentOS base distributive)
