### ISSUE TITLE
captagent 6.4.1 DEB Missing the package dependencies: error while loading shared libraries: libfl.so.2:

### ISSUE THREAD

**Issue by silentindark** [sipcapture/captagent#257]
Hello,

After installing on Debian 11.6 and starting the captagent.service, I got the following error message:

captagent[3444432]: /usr/local/captagent/sbin/captagent: error while loading shared libraries: libfl.so.2: cannot open shared object file: No such file or directory
systemd[1]: captagent.service: Control process exited, code=exited, status=127/n/a

So looks like that captagent.service depends on libfl, and after installing 
\# apt install libfl-dev
It solved the issue.

If checked with command
\# apt-cache show ./captagent_6.4.1.bullseye.amd64.deb
Package: captagent
Version: 6.4.1-1
License: unknown
Vendor: none
Architecture: amd64
Maintainer: <@36e6097d1859>
Installed-Size: 10408
**Depends: libexpat1,libjson-c5,libmcrypt4,libpcap0.8,libpcre3,libuv1**
Section: default
Priority: optional
Homepage: http://example.com/no-uri-given
Description: captagent 6.4.1
Description-md5: 95a95850dbd976eb7407434b3a31df9e
Filename: /usr/src/captagent_6.4.1.bullseye.amd64.deb
Size: 3450442

I think that libfl needs to be added to the package dependencies.
Depends: libexpat1,**libfl**,libjson-c5,libmcrypt4,libpcap0.8,libpcre3,libuv1

**Comment by kYroL01** [comment]
Hi @silentindark thank you so much for your test. 
Yes, you're totally right.
Fixed by https://github.com/sipcapture/captagent/commit/fdb564cb8c73855327c75000bc0ea51e37dd4ec7
