### ISSUE TITLE
have problem with debian 12 and capagent

### ISSUE THREAD

**Issue by mahmoudAlziem98** [sipcapture/captagent#275]
Hi,

I recently using my OS from Deb12. I started noticing coredumps from captagent after the upgrade. I am using captagent version 6.4.1. I am running captagent within a Kubernetes pod (mentioning it here in case it makes any difference)
I have included the details below. Please let me know if you require further information.
![Screenshot from 2023-11-06 17-24-20](https://github.com/sipcapture/captagent/assets/140612614/1ca42e3f-c67a-482e-a6ca-e3fa6b1d598b)

**Comment by lmangani** [comment]
Hello @mahmoudAlziem98 
We cannot really work with screenshots. I'd suggest switching to our other agent [heplify](https://github.com/sipcapture/heplify)

**Comment by kYroL01** [comment]
Hi @mahmoudAlziem98 
It seems you are compiling **captagent** with two different versions, as I can see your logs are showing **6.3.1**, but you're speaking about **6.4.1**.

Anyway, as Lorenzo said, you can also try [heplify](https://github.com/sipcapture/heplify) that is statically compiled.

Thank you
Michele
