### ISSUE TITLE
Missing some parts of SIP header and the entire SDP in HEP ​​message

### ISSUE THREAD

**Issue by matuskaacc** [sipcapture/captagent#278]
I'm noticing that when the SIP message collected for the captagent is a little larger, is missing out part of the header and the entire SDP body in the HEP message sent to the heplify-server. Does anyone know if there is any configuration in the captagent that could cause this behavior? 

I have enabled the reasm parameter in socket_pcap.xml file but didn't work. The captagent  stops to send the Invite message to heplify-server

<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>

                <param name="dev" value="enp129s0f0"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="true"/>
                <param name="websocket-detection" value="false"/>
                <param name="tcpdefrag" value="false"/>
                <param name="erspan" value="false"/>
                
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                    <value>portrange 5060-5091</value>
                </param>
            </settings>
        </profile>

**Comment by lmangani** [comment]
The issue is indeed packet fragmentation. The `reasm` parameter only affects UDP packets, while for TCP you need to also enable `tcpdefrag`. If none works, I would suggest attempting the same with `heplify` to determine if this is a bug or some other issue.

**Comment by matuskaacc** [comment]
Thank you for your quick response. I noticed in source SIP signaling that isn’t receiving some of fragmented packets. In Wireshark it’s just cames one packet of this Invite message with fragment-offset = 1480. I am not seeing the packet with fragment-offset=0. I will open a ticket with the switch supplier to understand this behavior in the mirror process.

**Comment by kYroL01** [comment]
Most likely you're not receiving the _last fragment_, the one with **fragment-offset = 0**, but only the first one (**fragment-offset = 1480**).

Thank you

**Comment by matuskaacc** [comment]
After checking more carefully, wireshark did not show off-set because it had the default reasemble configuration. When I disabled this option I was able to check the part of the fragment with off-set=0. So what could be causing this Invite message to not be sent to these fragmented UDP packets received even with the reasm parameter enabled?

**Comment by kYroL01** [comment]
It's very hard to say. `reasm = true` should do the trick.
I will retest my lab and see if I discover something.

**Comment by kYroL01** [comment]
@matuskaacc I just tested and for me it works fine. I import a fragmented INVITE and I see it reassembled.
Just to test, can you please try to remove the value inside `filter` and try it again ?
Thank you

**Comment by matuskaacc** [comment]
Thank you. Could you show here how your socket_pcap file that you tested was configured?

**Comment by kYroL01** [comment]
```
<profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
	    <settings>
		<param name="dev" value="eth0"/>
		<param name="promisc" value="true"/>
		<param name="reasm" value="true"/>
		<param name="websocket-detection" value="false"/>
		<param name="tcpdefrag" value="false"/>
		<param name="erspan" value="false"/>
	        <!-- <param name="capture-filter" value="ip_to_ip"/> -->
		<param name="capture-plan" value="sip_capture_plan.cfg"/>
		<param name="filter">
		    <value>port 5060</value>
		</param>
	    </settings>
	</profile>
```

Have you already tried to remove the BPF filter and retest ?
Remove the `filter` part and give it another shot.

**Comment by matuskaacc** [comment]
How can i remove the all BPF filter? I have tried do this:
root@SPCEN-HOMER-AGENT1:/usr/local/captagent/etc/captagent# cat socket_pcap.xml
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="enp129s0f0"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="true"/>
                <param name="websocket-detection" value="false"/>
                <param name="tcpdefrag" value="true"/>
                <param name="erspan" value="true"/>
                
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                   <value>ip</value>
                </param>
            </settings>
        </profile>
but this error is ocurring:
root@SPCEN-HOMER-AGENT1:/usr/local/captagent/etc/captagent# systemctl status captagent
● captagent.service - Captagent - monitoring system
     Loaded: loaded (/etc/systemd/system/captagent.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-05-07 14:39:19 -03; 789ms ago
    Process: 154540 ExecStart=/usr/local/captagent/sbin/captagent -f $CFGFILE -d (code=exited, status=0/SUCCESS)
   Main PID: 154541 (captagent)
      Tasks: 4 (limit: 309341)
     Memory: 1.4M
        CPU: 748ms
     CGroup: /system.slice/captagent.service
             └─154541 /usr/local/captagent/sbin/captagent -f /usr/local/captagent/etc/captagent/captagent.xml -d

mai 07 14:39:19 SPCEN-HOMER-AGENT1 systemd[1]: Starting Captagent - monitoring system...
mai 07 14:39:19 SPCEN-HOMER-AGENT1 captagent[154540]: [NOTICE] Loaded core config
mai 07 14:39:19 SPCEN-HOMER-AGENT1 systemd[1]: Started Captagent - monitoring system.
mai 07 14:39:19 SPCEN-HOMER-AGENT1 captagent[154541]: [ERR] socket_pcap.c:1499 bad values in the config
mai 07 14:39:19 SPCEN-HOMER-AGENT1 captagent[154541]: [ERR] protocol_sip.c:533 bad parsing
mai 07 14:39:19 SPCEN-HOMER-AGENT1 captagent[154541]: [ERR] protocol_sip.c:514 SIP PARSE ERROR [-1]
mai 07 14:39:19 SPCEN-HOMER-AGENT1 captagent[154541]:
mai 07 14:39:19 SPCEN-HOMER-AGENT1 captagent[154541]: [ERR] protocol_sip.c:533 bad parsing
mai 07 14:39:19 SPCEN-HOMER-AGENT1 captagent[154541]: [ERR] protocol_sip.c:514 SIP PARSE ERROR [-1]
mai 07 14:39:19 SPCEN-HOMER-AGENT1 captagent[154541]:
root@SPCEN-HOMER-AGENT1:/usr/local/captagent/etc/captagent# systemctl status captagent
● captagent.service - Captagent - monitoring system
     Loaded: loaded (/etc/systemd/system/captagent.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Tue 2024-05-07 14:39:23 -03; 968ms ago
    Process: 154557 ExecStart=/usr/local/captagent/sbin/captagent -f $CFGFILE -d (code=exited, status=0/SUCCESS)
   Main PID: 154558 (code=killed, signal=SEGV)
        CPU: 1.183s

mai 07 14:39:23 SPCEN-HOMER-AGENT1 systemd[1]: captagent.service: Scheduled restart job, restart counter is at 5.
mai 07 14:39:23 SPCEN-HOMER-AGENT1 systemd[1]: Stopped Captagent - monitoring system.
mai 07 14:39:23 SPCEN-HOMER-AGENT1 systemd[1]: captagent.service: Consumed 1.183s CPU time.
mai 07 14:39:23 SPCEN-HOMER-AGENT1 systemd[1]: captagent.service: Start request repeated too quickly.
mai 07 14:39:23 SPCEN-HOMER-AGENT1 systemd[1]: captagent.service: Failed with result 'signal'.
mai 07 14:39:23 SPCEN-HOMER-AGENT1 systemd[1]: Failed to start Captagent - monitoring system.

**Comment by matuskaacc** [comment]
I have tried do this but is ocurring error:
root@SPCEN-HOMER-AGENT1:/usr/local/captagent/etc/captagent# cat socket_pcap.xml
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="enp129s0f0"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="true"/>
                <param name="websocket-detection" value="false"/>
                <param name="tcpdefrag" value="true"/>
                <param name="erspan" value="true"/>
                
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                   <value>ip</value>
                </param>
            </settings>
        </profile>

**Comment by kYroL01** [comment]
Just remove these lines
```
                <param name="filter">
		    <value>port 5060</value>
		</param>
```

**Comment by matuskaacc** [comment]
Its ocurring this error:
![image](https://github.com/sipcapture/captagent/assets/168797033/605516c8-3a85-49c8-a429-17906bc13d73)

**Comment by matuskaacc** [comment]
[sip_invite_fragments_not_reassembling.zip](https://github.com/sipcapture/captagent/files/15249728/sip_invite_fragments_not_reassembling.zip)
This is the pcap with the two packets parts  of UDP SIP Invite fragmented that isn't working the reassembling. thank you.

**Comment by kYroL01** [comment]
I see this traffic has VLAN layer. Have you tried to use this filter in socket_pcap.xml ?

```
<param name="filter">
         <value>vlan and port 5060</value>
</param>
```

**Comment by matuskaacc** [comment]
I tried this sugestion with vlan and port in filter configuration but didn't work. Heplify is working nice
./heplify -i enp129s0f0 -pr 5060-5500 -hs 127.0.0.1:9060 -sipassembly true -dim OPTIONS,NOTIFY

**Comment by kYroL01** [comment]
Ah, wait wait, now it makes sense: you're using `-sipssembly` which reassemble the out of order SIP at application level, not transport level, which is not implemented in Captagent.

BTW this does not reflects the pcap you shared, that it must be reassembled with no issue on Captagent.

Just to try, could you please remove the `-sipassembly` from the heplify command and see if it's still working fine or not ? 

Thank you

**Comment by matuskaacc** [comment]
When i remove the -sipassembly works nice also.Then the parameter -sipassembly doesn't make diference to heplify processing complete Invite. Have you tested with my pcap file if captagent is processing all Invite with SDP?

**Comment by matuskaacc** [comment]
The fragmentation problem was resolved with this configuration/filter in the socket_pcap.xml file: 
root@SPOCEN-HOMER-AGENT1:/usr/local/captagent/etc/captagent# cat socket_pcap.xml 
<?xml version="1.0"?> <document type="captagent_module/xml"> 
<module name="socket_pcap" description="HEP Socket" serial="2014010402"> 
<profile name="socketspcap_sip" description="HEP Socket" enable="true" serial=" 2014010402"> 
<settings> 
<param name="dev" value="enp129s0f1"/> 
<param name="promisc" value="true"/> 
<param name="reasm" value="true"/> 
<param name="websocket-detection" value="false"/> 
<param name="tcpdefrag" value="false"/> 
<param name="erspan" value="false"/> 
 
< param name="capture-plan" value="sip_capture_plan.cfg"/> 
<param name="filter"> <value>portrange 5060-5500 or ip</value> 
</param> </settings> </profile>

**Comment by kYroL01** [comment]
Thanks @matuskaacc this means you have VLAN and non-VLAN traffic to be processed in the same time.
Thank you for sharing this.
