### ISSUE TITLE
issue with RTCP process (captagent 6)

### ISSUE THREAD

**Issue by Mickaelh51** [sipcapture/captagent#36]
Hi,
I have an issue with is_rtcp_exist function.

```
root@capturenode1:/usr/local/etc/captagent# [ERR] conf_function.c:451 find_export_record: <is_rtcp_exist> not found 

parse error (38,21-22): unknown command, missing loadmodule?
```

all modules are in lib directory:

```
root@capturenode1:/usr/local/etc/captagent# ls /usr/local/lib/captagent/modules/
capt_cli.so	  protocol_rtcp.la  proto_uni.so    socket_raw.so     transport_hep.so
core_hep.so	  protocol_rtcp.so  socket_pcap.a   socket_rtcpxr.a   transport_json.a
database_hash.a   protocol_sip.a    socket_pcap.la  socket_rtcpxr.la  transport_json.la
database_hash.la  protocol_sip.la   socket_pcap.so  socket_rtcpxr.so  transport_json.so
database_hash.so  protocol_sip.so   socket_raw.a    transport_hep.a
protocol_rtcp.a   proto_rtcp.so     socket_raw.la   transport_hep.la
```
Git cloned today
have you any help for me please ?

thanks in advance

**Comment by Mickaelh51** [comment]
After reinstall the sources, I have another issue. I'm going to open other ticket.

**Comment by adubovikov** [comment]
please wait, i will do some important changes for rtcp. 

ETA ~ 40-50 min :-)

**Comment by Mickaelh51** [comment]
Hi,
Ok it's good ;)

I'm waiting

**Comment by Mickaelh51** [comment]
for your information my new issue is about: parse_rtcp_to_json function

because I have:
```
"couldn't parse RTCP to json
```

**Comment by adubovikov** [comment]
ok, please check new git and specialty all config/capture plan changes.

**Comment by Mickaelh51** [comment]
very good for captagent, I have a result in rtcp_capture now ;)
but I'm not seeing this result in homer-ui. maybe a bug.... I will check asap.
