### ISSUE TITLE
Cisco phone INVITE - Bad SDP

### ISSUE THREAD

**Issue by btrain1227** [sipcapture/captagent#4]
Cisco 7960, 7965 and others that run v8 or higher firmware have their INVITE messages tossed with the "BAD SDP. Couldn't parse it!" error. The "c=" line comes after the "m=" in their SDP.

v=0
o=Cisco-SIPUA 7221 0 IN IP4 10.10.10.10
s=SIP Call
t=0 0
m=audio 20096 RTP/AVP 0 8 18 9 116 101
c=IN IP4 10.10.10.10
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:9 G722/8000
a=rtpmap:116 iLBC/8000
a=fmtp:116 mode=20
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv

**Comment by adubovikov** [comment]
please check the last git

https://github.com/sipcapture/captagent/commit/f32837bac2bc9a765f4c331b79fafbaaf45c5ea3

**Comment by btrain1227** [comment]
Looks good. Thanks!
