### ISSUE TITLE
fatal error: json/json.h: No such file or directory using jason-c

### ISSUE THREAD

**Issue by Homer-Rivera** [sipcapture/captagent#46]
I am using json-c  0.12-2 and when installing captagent 6 I run make and get this error.

```
transport_json.c:44:23: fatal error: json/json.h: No such file or directory
```

I updated src/modules/transport/json/transport_json.c and changed the include to be

```
#include <json-c/json.h>
```

That solved my issue but I wanted to know if there was a better way to go about this?

I am running archlinux.

Thanks

**Comment by lmangani** [comment]
Did you install the ```-dev``` package as well?

**Comment by lmangani** [comment]
Re-Open if still needed.
