### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by julioo** [sipcapture/captagent#47]
Hello,

I've installed homer from the last pull,
Since on the login page I have theses errors : 

Error: results.data.data is undefined
login/<@https://w.x.y.z/js/modules/auth/services/authentication.js:41:17
Ae/e/l.promise.then/I@https://w.x.y.z/lib/angular/angular.min.js:100:135
Ae/g/<.then/<@https://w.x.y.z/lib/angular/angular.min.js:101:308
Yd/this.$get</k.prototype.$eval@https://w.x.y.z/lib/angular/angular.min.js:112:28
Yd/this.$get</k.prototype.$digest@https://w.x.y.z/lib/angular/angular.min.js:109:113
Yd/this.$get</k.prototype.$apply@https://w.x.y.z/lib/angular/angular.min.js:112:360
h@https://w.x.y.z/lib/angular/angular.min.js:72:325
x@https://w.x.y.z/lib/angular/angular.min.js:77:288
we/</z.onreadystatechange@https://w.x.y.z/lib/angular/angular.min.js:78:340

https://w.x.y.z/lib/angular/angular.min.js
Line 92

I'm centos 7 

Thank you

**Comment by adubovikov** [comment]
sorry, please open this issue in HOMER-UI
