### ISSUE TITLE
Issues with .deb-Build and installation

### ISSUE THREAD

**Issue by winem** [sipcapture/captagent#48]
Hi, 

I experienced a few issues building and installing captagent on Debian 7.9. 

##### System details: 
OS: Debian Wheezy 7.9 
Installed packages during setup: Standard system utilities & ssh server 

My scripts to build the and install the .deb including workarounds: 

### build-captagent.sh  

```bash
#!/bin/bash
# build captagent.deb

### some vars 
email="xxx"
fullname="yyy"

### install curl + dependencies 
apt-get install curl dh-make build-essential devscripts fakeroot debootstrap pbuilder autotools-dev dh-autoreconf flex bison libexpat1-dev libpcap0.8-dev libjson0-dev

### prepare build
DEBEMAIL="$email"
DEBFULLNAME="$fullname"
export DEBEMAIL DEBFULLNAME 

mkdir -p build_pkgs && cd build_pkgs
curl -Lv https://github.com/sipcapture/captagent/archive/v6.0.1.tar.gz -o captagent-6.0.1.tar.gz 
tar -xvzf captagent-6.0.1.tar.gz 

# replace 2 locations
sed -i 's,/usr/local/bin/captagent,/usr/bin/captagent,' debian/captagent.init
sed -i 's,/usr/lib64/captagent/modules,/usr/lib/x86_64-linux-gnu/captagent/modules,' conf/captagent.xml

### start build 
cd captagent-6.0.1 
dh_make -f ../captagent-6.0.1.tar.gz
rm -rf debian/*.EX debian/*.ex debian/README.*
cp -r pkg/debian/* debian/

# clean up && build package && create .deb 
fakeroot debian/rules clean && fakeroot debian/rules build && fakeroot debian/rules binary

# build tar 
tar -cvzf /tmp/captagent_6.0.1-1-deb.tar.gz ../captagent_6.0.1-1_amd64.deb conf/database_hash.xml 
```
Both sed commands in the script above are required workarounds: 
* captagent will be installed to /usr/bin instead of /usr/local/bin
* modules are deployed into /usr1/lib/x86_64-linux-gnu/captagent/modules/ but captagent.xml does not yet support multi-arch supporting systems 

### install-captagent.sh
```bash 
#!/bin/bash

# install
dpkg -i captagent_6.0.1-1_amd64.deb

# create symlink 
ln -s /etc/captagent/ /usr/local/etc/captagent

# copy database_hash.xml (required during startup)
cp conf/database_hash.xml /etc/captagent/
```
Both, ln and cp command, are used to fix some issues again: 
* conf files are not deployed to /usr/local/etc/captagent/ 
* database_hash.xml is not deployed during install (tried to fix this adding `%config(noreplace) %{_sysconfdir}/%name/database_hast.xml in captagent.spec.in on line 168 without success) 

Let me know if I may assist you in any way.  

Best regards,
Marcel

**Comment by lmangani** [comment]
Thanks for your input @winem

**Comment by lmangani** [comment]
Package generation is now handled by FPM and available here: https://github.com/sipcapture/captagent/tree/master/pkg/fpm
