### ISSUE TITLE
captagent6 error parsing RTCP to json

### ISSUE THREAD

**Issue by aberrios85** [sipcapture/captagent#49]
Getting ```ERR] protocol_sip.c:124 couldn't parse RTCP to json``` while trying to capture rtcp. Not sure how to debug. Using ```captagent 6.0.1```

**Comment by lmangani** [comment]
@aberrios85 if you get this frequently or are able to replicate this issue, please try to capture the original packet for troubleshooting

**Comment by aberrios85** [comment]
@lmangani I'll give it a go, but its on a busy server :). can I use the capture-plan to dump out the problem packet?

**Comment by adubovikov** [comment]
only to add more debug output and recompile the module.

**Comment by aberrios85** [comment]
I'm not sure I'm going to be able to grab the problem packets, it is too busy. However I may be able to edit the module to spit it out.

**Comment by aberrios85** [comment]
Seems to be hit and miss, I now have some rtcp reports in mysql but not as many as hoped. Wonder if this is just a config issue.. Will close this thread.

**Comment by aberrios85** [comment]
Nope still mainly an issue, about 1 in 50 reports are successfully parsed. Not sure what to do.

**Comment by adubovikov** [comment]
again, please try to catch the bad parsed rtcp packets and send to us.

**Comment by aberrios85** [comment]
Am trying but proving difficult, I'm not a C developer, trying to get the module to dump out the packet when it can't parse it. 

Alternatively, using a shotgun approach to capturing rtp/rtcp traffic is too noisy.

**Comment by adubovikov** [comment]
Antonio,

how we can help you, if we don't have possibility to do analyze of these
bad packets? Try use tcpdump and filter all packets except rtcp and compare
with that you have in DB.

sorry, but we are waiting an input from your side.

thank you.

Wbr,
Alexandr

**Comment by aberrios85** [comment]
I'm looking at trying to get `protocol_rtcp.c` to dump out the packet when it can't parse it. rather than tcpdump capture on the machine and guess at matching up the problem packet.

**Comment by aberrios85** [comment]
I believe this to be one of the problem packets: https://gist.github.com/aberrios85/44a725a146b0c5ab1415

**Comment by adubovikov** [comment]
please set the debug level to 10 and syslog to true and restart the captagent. After, please check the syslog and analyze or provide the debug info.

**Comment by aberrios85** [comment]
will do

**Comment by aberrios85** [comment]
after running for a few hours I get nothing in syslog and in stdout I just a load of:

```[DEBUG] database_hash.c:127 IP PORT: IP_REDACTED:10841
[DEBUG] database_hash.c:226 IP PORT: [IP_REDACTED:10841]
[DEBUG] database_hash.c:226 IP PORT: [IP_REDACTED:20021]
[ERR] protocol_sip.c:124 Couldnot find this call```

**Comment by adubovikov** [comment]
so, all good ?

**Comment by aberrios85** [comment]
Nothing in rtcp_capture table.

**Comment by adubovikov** [comment]
so, please check if you have SIP messages on this interface and rtcp tracking and sip parsing is active

**Comment by aberrios85** [comment]
ah, yeah stupid me, I disabled sip capture in socket_pcap.xml because the stdout debug was too noisy but get rtcp active. Forgot this would be needed. derp.

**Comment by aberrios85** [comment]
Ah okay, so a lot of them seem to be: 

```
[DEBUG] parser_rtcp.c:65 Parsing compound packet (total of 104 bytes)

[DEBUG] parser_rtcp.c:71 #1 SR (200)

[DEBUG] parser_rtcp.c:117 #2 SDES (202)

[DEBUG] parser_rtcp.c:162 #3 BYE (203)

[DEBUG] parser_rtcp.c:184 End of RTCP packet

[DEBUG] protocol_rtcp.c:101 GOODBYE or APP MESSAGE. Ignore!

[ERR] protocol_sip.c:124 couldn't parse RTCP to json
```

Which I guess is totally correct.

So this might be to do with our strange setup for audio processing, and the audio processor not sending rtcp reports. However the Asterisk leg of the call should gen reports.

**Comment by adubovikov** [comment]
any progress ? or  should we close the ticket ?

**Comment by aberrios85** [comment]
Hi yeah, close the ticket. I'm not sure what's happening. I tried Asterisk 13's res_hep and it worked great first time, every time. So we're looking to migrate from Asterisk 11 to 13.

**Comment by adubovikov** [comment]
ok. thank you
