### ISSUE TITLE
multiple dev in capagent

### ISSUE THREAD

**Issue by shahbour** [sipcapture/captagent#50]
Is it possible to capture from multiple interfaces currently i am using  any but i need to apply filter on one of the interface and not both .

Is that possible and how ?

**Comment by adubovikov** [comment]
in captagent4 is possible to create only one listening profile, in this case you can run 2 captagents or create a bond interface.

with captagent6 you can create multiple listening profile: each for own interface.

**Comment by shahbour** [comment]
is captagent4 for ipv4 and captagent6  ipv6 ? if no where can i find captagent6 ?

**Comment by adubovikov** [comment]
4 and 6 are versions and has nothing with IPv4 and v6

anyway:
https://github.com/sipcapture/captagent/tree/captagent6
