### ISSUE TITLE
Issues starting captagent, files missing

### ISSUE THREAD

**Issue by sjobke** [sipcapture/captagent#51]
Hi, 

When i try to run captagent, i got the following errors, why are these files missing? I did a succesfull make & make install

Version 6.0.0

captagent -n
[NOTICE] Loaded core config
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/transport_json.so: cannot open shared object file: No such file or directory]
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/transport_hep.so: cannot open shared object file: No such file or directory]
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/protocol_sip.so: cannot open shared object file: No such file or directory]
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/database_hash.so: cannot open shared object file: No such file or directory]
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/protocol_sip.so: cannot open shared object file: No such file or directory]
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/protocol_rtcp.so: cannot open shared object file: No such file or directory]
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/socket_rtcpxr.so: cannot open shared object file: No such file or directory]
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/socket_pcap.so: cannot open shared object file: No such file or directory]
[ERR] modules.c:75 dlopen error [/usr/lib64/captagent/modules/socket_raw.so: cannot open shared object file: No such file or directory]

**Comment by adubovikov** [comment]
Hi,

please check the modules path in the captagent.xml

**Comment by lmangani** [comment]
Wiki was pointing to old branch, please pull master and use the new corrected defaults
