### ISSUE TITLE
setup capture for rtcp

### ISSUE THREAD

**Issue by pcw11211** [sipcapture/captagent#53]
how do i setup captagent to capture rtcp and how/where can the info/charts be viewed ?

**Comment by lmangani** [comment]
Hi,

In order to capture RTCP packets you need to load and configure the ```protocol_rtcp``` module:
```<load module="protocol_rtcp" register="local"> ```

The reports will be correlated to their corrensponding SIP sessions and visualized in [HOMER 5](http://github.com/sipcapture/homer) call details when matching

**Comment by pcw11211** [comment]
in /usr/local/etc/captagent/captagent.xml 
`<load module="socket_pcap" register="local"/>`
in  /usr/local/etc/captagent/protocol_rtcp.xml
`<?xml version="1.0"?>`
`<document type="captagent_module/xml">`
`    <module name="protocol_rtcp" description="RTCP Protocol" serial="2014010402">`
`        <profile name="proto_rtcp" description="PROTO RTCP" enable="true" serial="2014010402">`
`            <settings>`
`                <param name="rtcp-version" value="2"/>`
`            </settings>`
      `</profile>`
   `</module>`
`</document>`
 /usr/local/etc/captagent/socket_pcap.xml
` <profile name="socketspcap_rtcp" description="RTCP Socket" enable="true" serial="2014010402">`
            `<settings>`
                `<param name="dev" value="eth10"/>`
                `<param name="promisc" value="true"/>`
                `<param name="reasm" value="false"/>`
                `<param name="capture-filter" value="rtcp"/>`
               `<param name="capture-plan" value="rtcp_capture_plan.cfg"/>`
                `<param name="filter">`
                    `<value>portrange 10000-60000</value>`
          `      </param>`
         `   </settings>`
        `</profile>`
everything else default

which database/table does the trcp info go to?

**Comment by adubovikov** [comment]
Hi,

it should be populated into the rtcp_capture table.

Wbr,
Alexandr

**Comment by pcw11211** [comment]
nothing in rtcp_capture
is rtcp_capture suppose to be rotated like sip_capture tables?
all i get in captagent debug is 
[DEBUG] database_hash.c:111 RTCP CALLID: 600856161@192.168.1.41
[DEBUG] database_hash.c:112 RTCP IP PORT: XXX.XXX.XXX.XXX:29747
rest is [DEBUG] protocol_sip nothing with protocol_rtcp

**Comment by adubovikov** [comment]
it has internal partitioning.

looks like you don't have any rtcp packets on this interface at all. Can 
you please check it ?

**Comment by pcw11211** [comment]
![image](https://cloud.githubusercontent.com/assets/16885161/12585776/7c973e46-c41b-11e5-909e-f25895520f3d.png)

rtcp is there

**Comment by pcw11211** [comment]
please share a captagent debug output (sample) for rtcp packet

**Comment by lmangani** [comment]
Should be one of the capture settings - is your device really ```eth10```?
