### ISSUE TITLE
Fatal:  libjson not found.

### ISSUE THREAD

**Issue by jfjeronimo** [sipcapture/captagent#54]
Hi,

Trying to install the new version (Captagent 6) in Ubuntu 12.04 server (precise), I get the following error:

 checking for json_object_get in -ljson... no
 checking for json_object_get in -ljson-c... no
 ERROR:  You need libjson to build CaptAgent API module.
         Verify that you have libjson.a or libjson.so installed
         If it is in a different directory, try using
         the LDFLAGS to set its proper path.
configure: error: Fatal:  libjson not found.

Thanks for your help!

**Comment by adubovikov** [comment]
please install libjson0-dev.

**Comment by jfjeronimo** [comment]
It Works! Thank you !!
