### ISSUE TITLE
Install issue Debian 8 Jessie on Raspberry Pi

### ISSUE THREAD

**Issue by johnn2689** [sipcapture/captagent#56]
I encountered an issue after building and configuring the captagent, following the guide from [this git hub site](https://github.com/sipcapture/captagent/wiki/Installation). 

`cd /usr/src
  git clone https://github.com/sipcapture/captagent.git captagent
  cd captagent
  ./build.sh
  ./configure
  make && make install`

I get to the last step fine. It seems to occur when checking the hardware. Any ideas? 

root@raspbx:/usr/src/captagent# make && make install
Making all in src
make[1]: Entering directory '/usr/src/captagent/src'
make  all-recursive
make[2]: Entering directory '/usr/src/captagent/src'
Making all in .
make[3]: Entering directory '/usr/src/captagent/src'
gcc -DHAVE_CONFIG_H -I.  -DSYSCONFDIR='"/usr/local/etc"' -I../include  -g -fPIC -rdynamic -I../include -g -O2 -MT captagent.o -MD -MP -MF .deps/captagent.Tpo -c -o captagent.o captagent.c
In file included from captagent.c:52:0:
captagent.c: In function ‘print_hw’:
captagent.h:48:103: error: impossible constraint in ‘asm’
 static inline int ghk(char *_0){unsigned _O=1,aO=0;FILE *f;char _1[50];md5_byte_t h[33];md5_state_t c;asm volatile("cpuid":"=a"(_O),"=b"(aO),"=c"(aO),"=d"(aO):"0"(_O),"2"(aO));aO=snprintf(_1,100,"%d:%d:%d:%d:%d:%d_",_O&0xF,(_O>>4)&0xF,(_O>>8)&0xF,(_O>>12)&0x3,(_O>>16)&0xF,(_O>>20)&0xFF);f=fopen("/sys/class/net/eth0/address","r");if(f==NULL)f=fopen("/sys/class/net/em1/address","r");if(f==NULL)f=fopen("/sys/class/net/em2/address","r");if(f!=NULL){fgets(_1+aO,20,f);fclose(f);aO=strlen(_1);_1[aO-1]='\0';md5_init(&c);md5_append(&c,(const md5_byte_t*)_1,aO-1);md5_finish(&c,h);for(aO=0;aO<16;aO++)sprintf(_0+(aO*2),"%02X",(unsigned int)h[aO]);return 1;}return 0;}
                                                                                                       ^
Makefile:579: recipe for target 'captagent.o' failed
make[3]: *** [captagent.o] Error 1
make[3]: Leaving directory '/usr/src/captagent/src'
Makefile:639: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/captagent/src'
Makefile:456: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/captagent/src'
Makefile:441: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Esteban87** [comment]
I have same issue trying build captagent 6 in debian 8 Raspberry PI 2:

Making all in src
make[1]: ingresso nella directory "/usr/src/captagent/src"
make  all-recursive
make[2]: ingresso nella directory "/usr/src/captagent/src"
Making all in .
make[3]: ingresso nella directory "/usr/src/captagent/src"
gcc -DHAVE_CONFIG_H -I.  -DSYSCONFDIR='"/usr/local/etc"' -I../include  -g -fPIC -rdynamic -I../include -g -O2 -MT captagent.o -MD -MP -MF .deps/captagent.Tpo -c -o captagent.o captagent.c
In file included from captagent.c:52:0:
captagent.c: In function 'print_hw':
captagent.h:48:103: error: impossible constraint in 'asm'
 static inline int ghk(char *_0){unsigned _O=1,aO=0;FILE *f;char _1[50];md5_byte_t h[33];md5_state_t c;asm volatile("cpuid":"=a"(_O),"=b"(aO),"=c"(aO),"=d"(aO):"0"(_O),"2"(aO));aO=snprintf(_1,100,"%d:%d:%d:%d:%d:%d_",_O&0xF,(_O>>4)&0xF,(_O>>8)&0xF,(_O>>12)&0x3,(_O>>16)&0xF,(_O>>20)&0xFF);f=fopen("/sys/class/net/eth0/address","r");if(f==NULL)f=fopen("/sys/class/net/em1/address","r");if(f==NULL)f=fopen("/sys/class/net/em2/address","r");if(f!=NULL){fgets(_1+aO,20,f);fclose(f);aO=strlen(_1);_1[aO-1]='\0';md5_init(&c);md5_append(&c,(const md5_byte_t*)_1,aO-1);md5_finish(&c,h);for(aO=0;aO<16;aO++)sprintf(_0+(aO*2),"%02X",(unsigned int)h[aO]);return 1;}return 0;}
                                                                                                       ^
Makefile:579: set di istruzioni per l'obiettivo "captagent.o" non riuscito
make[3]: *** [captagent.o] Errore 1
make[3]: uscita dalla directory "/usr/src/captagent/src"
Makefile:639: set di istruzioni per l'obiettivo "all-recursive" non riuscito
make[2]: *** [all-recursive] Errore 1
make[2]: uscita dalla directory "/usr/src/captagent/src"
Makefile:456: set di istruzioni per l'obiettivo "all" non riuscito
make[1]: *** [all] Errore 2
make[1]: uscita dalla directory "/usr/src/captagent/src"
Makefile:441: set di istruzioni per l'obiettivo "all-recursive" non riuscito
make: *** [all-recursive] Errore 1

**Comment by adubovikov** [comment]
Raspbery has ARM processor and in this case asm doesn't work. 

Let me check that i can do

**Comment by adubovikov** [comment]
as quick workaround:

https://github.com/adubovikov/captagent/commit/d882c487fb0a07cd5dafb3fea9a63531e32471c8

**Comment by Esteban87** [comment]
Thanks, now the install process end without errors, but i have some trouble to  configure the captagent.
I use this config in captagent.xml file:

<?xml version="1.0"?>
<document type="captagent/xml">
        <configuration name="core.conf" description="CORE Settings" serial="2014024212">
            <settings>
                <param name="debug" value="3"/>
                <param name="version" value="2"/>
                <param name="serial" value="2014056501"/>
                <param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
                <param name="daemon" value="false"/>
                <param name="syslog" value="false"/>
                <param name="pid_file" value="/var/run/captagent.pid"/>
                <param name="module_path" value="/usr/local/lib/captagent/modules"/>
                <param name="config_path" value="/captagent6/conf"/>
                <param name="capture_plans_path" value="/etc/captagent/captureplans"/>
                <param name="backup" value="/etc/captagent/backup"/>
                <param name="chroot" value="/var/lib/captagent"/>
            </settings>
        </configuration>
        <configuration name="modules.conf" description="Modules">
            <modules>
                <load module="transport_json" register="local"/>
                <load module="transport_hep" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="database_hash" register="local"/>
                <load module="protocol_sip" register="local"/>
                <load module="protocol_rtcp" register="local"/>
                <load module="socket_rtcpxr" register="local"/>
                <load module="socket_pcap" register="local"/>
                <load module="socket_raw" register="local"/>
            
            </modules>
        </configuration>
        

        <configuration name="core_hep.conf" description="HEP Socket">
          <settings>
            <param name="version" value="3"/>
            <param name="capture-host" value="MY_Homer5_IP"/>
            <param name="capture-port" value="9060"/>
            <param name="capture-proto" value="udp"/>
            <param name="capture-id" value="2001"/>
            <param name="capture-password" value="myHep"/>
            <param name="payload-compression" value="false" />
          </settings>
        </configuration>



        <configuration name="proto_uni.conf" description="UNI Proto Basic capture">
          <settings>
            <param name="port" value="5060"/>
            
            
            <param name="dev"  value="eth0"/>
            <param name="promisc" value="true"/>
            
            <param name="ip-proto" value="udp"/>
            <param name="proto-type"  value="sip"/>
            <param name="sip-parse"  value="true"/>
            <param name="rtcp-tracking"  value="true"/>
            <param name="reasm"  value="false"/>
            <param name="tcpdefrag"  value="false"/>
            <param name="debug" value ="false"/>
            <param name="buildin-reasm-filter" value="false"/>
            
            
                
                
          </settings>
        </configuration>

        <configuration name="proto_rtcp.conf" description="RTCP capture">
          <settings>
            
            <param name="dev"  value="eth0"/>
            <param name="promisc" value="true"/>
            <param name="debug" value ="false"/>
            <param name="debug" value ="false"/>
            
            
            
            
          </settings>
        </configuration>

        
        <configuration name="capt_cli.conf" description="CLI socket">
          <settings>
            <param name="cli-host" value="localhost"/>
            <param name="cli-port" value="8909"/>
            <param name="cli-password" value="12345"/>
          </settings>
        </configuration>
</document>


but when captagent start i see a log "HEP send error"...Homer 5 server run on a docker container installed on a ubuntu 15.10 host located in the same network subnet of the captagent. I try to trace network traffic incoming to the homer host, but don't see any HEP packet incoming... 
The sip server is an Asterisk 11. When i start a sip packet capture (example sngrep) on the captagent host i can see sip traffic incoming and outgoing..
How can i verify the homer server config in the docker container?
There is a user / password to login the Homer5 container's console?

thanks for your support

**Comment by lmangani** [comment]
```HEP send error``` indicates the agent is unable to reach the HEP socket
please check ```transport_hep.xml``` and confirm it contains the correct IP:PORT for your Homer docker instance

**Comment by Esteban87** [comment]
Thanks Lorenzo,
Now the captagent start without errors, and i can see UDP packets on port 6060 coming to the docker interface.. but nothing appear when i try to search in the homer5 webpage..

thanks for your support

**Comment by lmangani** [comment]
@Esteban87 do you see packets being inserted in the database partition for the current date?
Do you see any output/errors on the console of the container from Kamailio?
