### ISSUE TITLE
error starting captagent, can not find libpcap.so.1

### ISSUE THREAD

**Issue by fborot** [sipcapture/captagent#58]
when starting captagent it complains about not finding the libpcap.so.1 file

[root@PROXY-02 captagent]# captagent start -d
captagent: error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory
[root@PROXY-02 captagent]#

the file is here:
/usr/local/lib/libpcap.so.1

[root@PROXY-02 captagent]# ls -la /usr/local/lib/libpcap.so.1
lrwxrwxrwx 1 root root 16 Apr  1 17:07 /usr/local/lib/libpcap.so.1 -> libpcap.so.1.1.1
[root@PROXY-02 captagent]#

where does it expect it to be?
thank you

**Comment by fborot** [comment]
this is the content of my /usr/local/lib/ folder


[root@AW-ATL-PROXY-02 captagent]# cd /usr/local/lib
[root@AW-ATL-PROXY-02 lib]# ls -la
total 1276
drwxr-xr-x  4 root root   4096 Apr  1 17:15 .
drwxr-xr-x 14 root root   4096 Apr  1 15:29 ..
drwxr-xr-x  3 root root   4096 Apr  1 17:15 captagent
-rw-r--r--  1 root root   6956 Apr  1 17:06 libfl.a
-rw-r--r--  1 root root   7112 Apr  1 17:06 libfl_pic.a
-rw-r--r--  1 root root 158884 Apr  1 17:09 libjson.a
-rwxr-xr-x  1 root root    920 Apr  1 17:09 libjson.la
lrwxrwxrwx  1 root root     16 Apr  1 17:09 libjson.so -> libjson.so.0.1.0
lrwxrwxrwx  1 root root     16 Apr  1 17:09 libjson.so.0 -> libjson.so.0.1.0
-rwxr-xr-x  1 root root  99648 Apr  1 17:09 libjson.so.0.1.0
-rw-r--r--  1 root root 209370 Apr  1 17:04 libltdl.a
-rwxr-xr-x  1 root root    922 Apr  1 17:04 libltdl.la
lrwxrwxrwx  1 root root     16 Apr  1 17:04 libltdl.so -> libltdl.so.7.3.1
lrwxrwxrwx  1 root root     16 Apr  1 17:04 libltdl.so.7 -> libltdl.so.7.3.1
-rwxr-xr-x  1 root root 124142 Apr  1 17:04 libltdl.so.7.3.1
-rw-r--r--  1 root root 385660 Apr  1 17:07 libpcap.a
lrwxrwxrwx  1 root root     12 Apr  1 17:07 libpcap.so -> libpcap.so.1
lrwxrwxrwx  1 root root     16 Apr  1 17:07 libpcap.so.1 -> libpcap.so.1.1.1
-rwxr-xr-x  1 root root 241134 Apr  1 17:07 libpcap.so.1.1.1
drwxr-xr-x  2 root root   4096 Apr  1 17:09 pkgconfig
[root@AW-ATL-PROXY-02 lib]#

**Comment by adubovikov** [comment]
Can u please show the result of

ldd captagent

**Comment by adubovikov** [comment]
And be sure that /usr/local/lib is in your ldpath.

Or check the variable LD_PATH

**Comment by fborot** [comment]
thank you, what I did was to create a captagent.conf inside "/etc/ld.so.conf.d/" with the line:

/usr/local/lib/
then I ran ldconfig and it starts but says:
[root@AW-ATL-PROXY-02 bin]# ./captagent start -d
[NOTICE] Loaded core config
[root@PROXY-02 bin]# [ERR] transport_hep.c:617 HEP send error.

**Comment by fborot** [comment]
this is my transport_hep.xml file:

<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="transport_hep" description="HEP Protocol" serial="2014010402">
        <profile name="hepsocket" description="Transport HEP" enable="true" serial="2014010402">
            <settings>
                <param name="version" value="3"/>
                <param name="capture-host" value="A.B.C.146"/>
                <param name="capture-port" value="9061"/>
                <param name="capture-proto" value="udp"/>
                <param name="capture-id" value="2001"/>
                <param name="capture-password" value="myhep"/>
                <param name="payload-compression" value="false"/>
            </settings>
        </profile>
    </module>
</document>

and my socket_pcap.xml

<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="eth1"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                    <value>portrange 5060-5091</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_rtcp" description="RTCP Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="capture-filter" value="rtcp"/>
                <param name="capture-plan" value="rtcp_capture_plan.cfg"/>
                <param name="filter">
                    <value>portrange 3000-5000</value>
                </param>
            </settings>
        </profile>
    </module>
</document>

**Comment by fborot** [comment]
these are my transport and socket files: 192.168.1.146 is my homer server

`<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="transport_hep" description="HEP Protocol" serial="2014010402">
        <profile name="hepsocket" description="Transport HEP" enable="true" serial="2014010402">
            <settings>
                <param name="version" value="3"/>
                <param name="capture-host" value="192.168.1.146"/>
                <param name="capture-port" value="9061"/>
                <param name="capture-proto" value="udp"/>
                <param name="capture-id" value="2001"/>
                <param name="capture-password" value="myhep"/>
                <param name="payload-compression" value="false"/>
            </settings>
        </profile>
    </module>
</document>
`
`<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
        <profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
            <settings>
                <param name="dev" value="eth1"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="capture-plan" value="sip_capture_plan.cfg"/>
                <param name="filter">
                    <value>portrange 5060-5091</value>
                </param>
            </settings>
        </profile>
        <profile name="socketspcap_rtcp" description="RTCP Socket" enable="false" serial="2014010402">
            <settings>
                <param name="dev" value="any"/>
                <param name="promisc" value="true"/>
                <param name="reasm" value="false"/>
                <param name="capture-filter" value="rtcp"/>
                <param name="capture-plan" value="rtcp_capture_plan.cfg"/>
                <param name="filter">
                    <value>portrange 3000-5000</value>
                </param>
            </settings>
        </profile>
    </module>
</document>
`

**Comment by fborot** [comment]
solved, the client has port 9061 and the server 9060, thank you

**Comment by adubovikov** [comment]
You are welcome. Please close the ticket
