### ISSUE TITLE
Is ERSPAN supported

### ISSUE THREAD

**Issue by shahbour** [sipcapture/captagent#59]
Hello

I was using RSPAN to capture packets from my network and forward them to captagent , due to some complexity i want to use ERSPAN , i test it and if i do wireshark it do decapsulate the sip packets and show them but when trying to configure captagent it doesn't recognize the packets because they are encapsulated 

more info about [ERSPAN](https://supportforums.cisco.com/document/139236/understanding-spanrspanand-erspan)

**Comment by lmangani** [comment]
Hi @shahbour 

This is currently not supported, if you wish to contribute or sponsor this feature feel free to contact support@sipcapture.org

**Comment by lmangani** [comment]
PS: As an interim solution you can try something like https://sourceforge.net/projects/rcdcap/

**Comment by shahbour** [comment]
i will do that , i tried what this [URL](http://brezular.com/2015/05/03/decapsulation-erspan-traffic-with-open-source-tools/) says but did not work

**Comment by shahbour** [comment]
Just want to confirm that rcdcap worked perfectly

**Comment by lmangani** [comment]
Excellent, thanks for the confirmation & glad it worked!
