### ISSUE TITLE
RTCP capture: "Couldnot find this call"

### ISSUE THREAD

**Issue by dougbtv** [sipcapture/captagent#61]
Having a bit of an issue trying to capture RTCP. Current setup is homer-docker for the capture server.

The client is an Asterisk machine, making a call between a Zoiper softphone. I'm using the 6.1 branch of captagent (happy to test against master or otherwise, figured I saw you guys talking about merging that branch to master). I've confirmed that RTCP is being sent between the 2 SIP UA's, e.g. [this wireshark screencap](http://i.imgur.com/fXszdFQ.png). And also took a pcap at the Homer capture server and it doesn't look like there's any RTCP info coming over (that is, just eyeballing it, I can see the ASCII for the SIP messages, but nothing else)

I ran into the same issue as reported in #55 where RTCP wasn't enabled due to `database_hash` module not being loaded or being loaded in the improper order. However, once I got there I ran into the same issue was the user in question.

When running captagent, the output I have is:
```
[root@asterisk1ri3int captagent]# captagent -n -f /etc/captagent/captagent.xml
[NOTICE] Loaded core config
[ERR] protocol_sip.c:124 Couldnot find this call

[ERR] protocol_sip.c:124 Couldnot find this call

[ERR] protocol_sip.c:124 Couldnot find this call
```

I can find the line that's producing that output in the [capture-plan for RTCP at this line](https://github.com/sipcapture/captagent/blob/master/conf/captureplans/rtcp_capture_plan.cfg#L23).

I tried removing that `if` statement in the capture plan, and it winds up erroring on the next if statement with the `couldn't parse RTCP to json` in the captagent output.

I figured you guys might know exactly what's going on -- but in terms of contributing, one thing I might be able to do is setup the Travis CI tests to run the application, as well as run some SIP UA's and have it perform a capture.

My configuration is as follows, mostly it's default except I've been keeping my configs in `/etc/` and then just changes as noted in these two issues #55 and #53 -- plus of course my IPs / creds in `transport_hep.xml`. Let me know if I'm missing any files in my config you'd like to see.

### captagent.xml

```xml
<?xml version="1.0"?>
<document type="captagent/xml">
	<configuration name="core.conf" description="CORE Settings" serial="2014024212">
	    <settings>
		<param name="debug" value="3"/>
		<param name="version" value="2"/>
		<param name="serial" value="2014056501"/>
		<param name="uuid" value="00781a4a-5b69-11e4-9522-bb79a8fcf0f3"/>
		<param name="daemon" value="false"/>
		<param name="syslog" value="false"/>
		<param name="pid_file" value="/var/run/captagent.pid"/>
		<!-- Configure using installation path if different from default -->
		<param name="module_path" value="/usr/local/lib/captagent/modules"/>
		<param name="config_path" value="/etc/captagent"/>
		<param name="capture_plans_path" value="/etc/captagent/captureplans"/>
		<param name="backup" value="/etc/captagent/backup"/>
		<param name="chroot" value="/var/lib/captagent"/>
	    </settings>
	</configuration>
	<configuration name="modules.conf" description="Modules">
	    <modules>
	
		<load module="transport_hep" register="local"/>
		<load module="protocol_sip" register="local"/>
		<load module="protocol_rtcp" register="local"/>		                                  
		<load module="socket_rtcpxr" register="local"/>
   		<load module="database_hash" register="local"/>
		<load module="socket_pcap" register="local"/>
		<load module="socket_raw" register="local"/>
	    <!--
	    	<load module="transport_json" register="local"/>

		<load module="interface_http" register="local"/>
		<load module="database_redis" register="local"/>
		<load module="socket_pfring" register="local"/>
 	    -->
	    </modules>
	</configuration>
</document>
```

### socket_pcap.xml

```xml
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
	<profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
	    <settings>
		<param name="dev" value="eth0"/>
		<param name="promisc" value="true"/>
		<param name="reasm" value="false"/>
		<param name="capture-plan" value="sip_capture_plan.cfg"/>
		<param name="filter">
		    <value>portrange 5060-5091</value>
		</param>
	    </settings>
	</profile>
	<profile name="socketspcap_rtcp" description="RTCP Socket" enable="true" serial="2014010402">
	    <settings>
		<param name="dev" value="eth0"/>
		<param name="promisc" value="true"/>
		<param name="reasm" value="false"/>
		<!-- size in MB -->
		<param name="ring-buffer" value="20"/>
		<!-- for rtp && rtcp < 250 -->
		<param name="snap-len" value="256"/>
		<param name="capture-filter" value="rtcp"/>
		<param name="capture-plan" value="rtcp_capture_plan.cfg"/>
		<param name="filter">
		    <value>portrange 5060-50000</value>
		</param>
	    </settings>
	</profile>
    </module>
</document>
```

### protocol_rtcp.xml

```xml
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="protocol_rtcp" description="RTCP Protocol" serial="2014010402">
	<profile name="proto_rtcp" description="PROTO RTCP" enable="true" serial="2014010402">
	    <settings>
		<param name="rtcp-version" value="2"/>
	    </settings>
	</profile>
    </module>
</document>
```

### protocol_sip.xml

```xml
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="protocol_sip" description="SIP Protocol" serial="2014010402">
	<profile name="proto_sip" description="PROTO SIP" enable="true" serial="2014010402">
	    <settings>
		<param name="dialog-type" value="2"/>
		<param name="dialog-timeout" value="180"/>
	    </settings>
	</profile>
    </module>
</document>
```

### transport_hep.xml

```xml
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="transport_hep" description="HEP Protocol" serial="2014010402">
	<profile name="hepsocket" description="Transport HEP" enable="true" serial="2014010402">
	    <settings>
		<param name="version" value="3"/>
		<param name="capture-host" value="192.168.122.133"/>
		<param name="capture-port" value="9060"/>
		<param name="capture-proto" value="udp"/>
		<param name="capture-id" value="2001"/>
		<param name="capture-password" value="myHep"/>
		<param name="payload-compression" value="false"/>
	    </settings>
	</profile>
    </module>
</document>
```

**Comment by pinchasMT** [comment]
can you please post sip_capture_plan.cfg
mine has un-commented
```
  if(sip_has_sdp())
                 {
                        #Activate it for RTCP checks
                        if(!check_rtcp_ipport())
                        {
                                clog("ERROR", "ALREADY EXIST");
                        }
                 }

```

**Comment by dougbtv** [comment]
@pinchasMT sure thing, here's my `sip_capture_plan.cfg`

```
capture[pcap] {

	# here we can check source/destination IP/port, message size
	if(msg_check("size", "100")) {

	    #Do parsing
	    if(parse_sip()) {
		#Can be defined many profiles in transport_hep.xml	
		
		if(!send_hep("hepsocket")) {
		    clog("ERROR", "Error sending HEP!!!!");
		}
		
		# if(sip_has_sdp())
		# {
		#	#Activate it for RTCP checks
		#	if(!check_rtcp_ipport())
		#	{
		#		clog("ERROR", "ALREADY EXIST");
		#	}
		# }

		#Duplicate all INVITEs to JSON transport
		# if(sip_is_method() && sip_check("method","INVITE")) {
		#    #Can be defined many profiles in transport_json.xml
		#    if(!send_json("jsonsocket")) {
		#	clog("ERROR", "Error sending JSON!!!");
		#    }
		# }
	    }
	}
	drop;
}
```

**Comment by dougbtv** [comment]
Ah ha, I'll try uncommenting that too, now I see maybe what you're driving at.

**Comment by lmangani** [comment]
Portrange for RTCP is a little off too, and overlaps with the SIP range:
```
            <value>portrange 5060-50000</value>
```

**Comment by pinchasMT** [comment]
I"m not the developer of this project, full respect to them, but my suggestion is to un-comment those lines. please correct me if I"m wrong

**Comment by dougbtv** [comment]
@lmangani thanks for the heads up!

and @pinchasMT -- excellent suggestion and great eye, I appreciate that. It works!!! :+1: Many thanks indeed.

![rtcp working](http://imgur.com/JlnUBWB)

aaaaaah :) Perfect that's what I wanted to see.

I might think about doc'ing up the process here, it wasn't quite intuitive, but, appreciate the eyeballs guys, thank you!!

**Comment by lmangani** [comment]
For completion, by default RTCP mirroring is disabled and related lines commented (as per the JSON mirroring feature example) I will add this to the default files specifying this is required for RTCP pairing.

**Comment by pinchasMT** [comment]
little question, is any of nodes behind NAT? RCTP showing private IP's but SDP showing public IP.
the reason why im asking is because my nodes are behind NAT and im not getting anything in RTCP graph

**Comment by lmangani** [comment]
@pinchasMT do you see RTCP packets being delivered to the HEP interface? If so, what correlation ID do they carry, if any?
```
ngrep -W byline port 9060 | grep -i jitter
```

**Comment by pinchasMT** [comment]
i dont see any HEP encapsulated RTCP packets, i think its because sdp has private ip
im on 6.0.1

**Comment by dougbtv** [comment]
@pinchasMT just for your reference, this is a pretty unrealistic use-case as it's totally on the same subnet in dev. For what it's worth... Zoiper presents the SDP with a WAN IP, but I have Asterisk ignore it (by telling Asterisk "hey, this UA is NAT'ed").

And in this case it works. 

When I implement in production, I'll let you know (hopefully I remember!) as I do have NAT'ed UA's in production.

**Comment by adubovikov** [comment]
@pinchasMT for your scenario:
who changes a private IP to a public ? Asterisk set your public IP to SDP or you have a SBC with SIP ALG ?

**Comment by pinchasMT** [comment]
i have done some testing, i do get (only one way) RTCP with SIP-ALG enabled in the router running NAT, but it doesn't catch all sip traffic. therefore we have opensips add "VIA" to sip and do NAT detection. when SDP is not overwritten with SIP-ALG no RTCP packets are arriving from captagent

p.s. https://github.com/sipcapture/captagent/issues/60

**Comment by vijayaa** [comment]
@pinchasMT  We are also facing the same issue. Can you please help us in solving this. We are using FreeSWITCH Server
