### ISSUE TITLE
Captagent 6.1.0 Debian Wheezy: "This is not RTCP"

### ISSUE THREAD

**Issue by lcligny** [sipcapture/captagent#64]
Hello everyone,

I'm facing an issue with RTCP parsing with captagent 6.1.0 on Debian Wheezy and Asterisk 11.15.0 compiled from a git clone made the 18th May 2016, like explained on the doc:

`git clone https://github.com/sipcapture/captagent.git captagent`
`cd captagent`
`./build.sh`
`./configure`
`make && make install`

RTCP are sent and received on the node running captagent, but the parser says "[ERR] protocol_sip.c:131 This is not RTCP" for each RTCP packets.

A tcpdump shows RTCP packets and wireshark RTCP dissector is able to give me packets details.
I searched on the src, and I think my packets are for some reason not compliant with tests within the code (check_rtcp_version function maybe?) but my very little dev knowledge is confusing me.

So you'll find thereafter my captagent config, and capture of 6 RTCP packets corresponding to 6 "This is not RTCP" I got today.

Thanks for your help, and congrats for your amazing sipcapture/homer suite ;)

[captagent_config.zip](https://github.com/sipcapture/captagent/files/274165/captagent_config.zip)
[RTCPdump.zip](https://github.com/sipcapture/captagent/files/274173/RTCPdump.zip)

**Comment by adubovikov** [comment]
fixed. please check it again!

**Comment by lcligny** [comment]
RTCP is correctly handled now, thanks a lot. But now I have an issue with a 'NUL' inserted at the very end of json "msg" field  on rtcp_capture table. It seems to confuse php json_decode() on Homer's Report.php. When I UPDATE the table with the very same data, the 'NUL' disapears and RTCP data is correclty shown on Homer.

I will open a new issue if I'm unable to solve it myself.

**Comment by adubovikov** [comment]
ok, thank you! Please close the ticket and open a new one.

**Comment by lcligny** [comment]
Just for anyone facing the same "msg" field issue with Mysql 5.7, I solved by

`ALTER TABLE rtcp_capture MODIFY msg JSON;`

on homer_data db.
