### ISSUE TITLE
Default CFGFILE / etc directory

### ISSUE THREAD

**Issue by tkteun** [sipcapture/captagent#65]
The init scripts supplied with captagent all point to _/usr/local/captagent/etc/captagent.xml_ while these are installed in _/usr/local/captagent/etc/captagent/captagent.xml_

**Comment by adubovikov** [comment]
what's distributive ?

**Comment by tkteun** [comment]
Distributions?

Debian Wheezy & Jessie
Centos / RHEL 6 & 7

https://github.com/sipcapture/captagent/search?utf8=✓&q=%2Fusr%2Flocal%2Fcaptagent%2Fetc%2Fcaptagent.xml

**Comment by adubovikov** [comment]
should be ok now.

**Comment by tkteun** [comment]
Ahh, nice...

I thought I was going crazy, but you already fixed it... Thanks!

**Comment by adubovikov** [comment]
:-) thanks for the report.
