### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by kemathy** [sipcapture/captagent#7]
Hi, 

We wanted to run multiple instances of captagent on the same server; so, we created 3 init scripts, to be able to run captagent with different configuration files, different pidfile, and lock file.

We modified our configurations to deactivate cli module, because Alexandr told us it can't be run multiple times. This part is OK.

But, every time we'd like to start / restart captagent services, we got some errors about filters, or sometimes it doesn't simply start... And if we retry to start the service twice or more, it finally start, and works correctly... It's a bit strange, and it's by the way impossible to automatically start the multiple captagent instances at the server bootup.

Do you have any idea about that ? 
If you need further informations, feel free to ask ;-)

Thanks, 
Kevin

**Comment by adubovikov** [comment]
waiting for capt6....

**Comment by kemathy** [comment]
Ok, thanks ;-)

**Comment by adubovikov** [comment]
I think we can close it. 6.x  has been released.
