### ISSUE TITLE
100% CPU usage captagent

### ISSUE THREAD

**Issue by killdashnine** [sipcapture/captagent#70]
Continued from #66 as memory leak appears resolved, but now I am seeing 100% CPU.
Will update ticket with more details later.

**Comment by adubovikov** [comment]
please provide more input :-)

**Comment by killdashnine** [comment]
Hi, now testing as of which commit I see the 100% CPU issue. I am currently testing bbc7e6ced2462bf30b41c19c0aa454e047542127. And going down until I stop seeing 100% CPU issue.

It takes around 10 minutes before the 100% CPU arises

**Comment by lmangani** [comment]
Thanks @killdashnine very much appreciated and looking forward any findings

**Comment by adubovikov** [comment]
can you comment out in the socket_pcap.c:

pcap_freecode(&filter);

and test again ? 

can you please also provide the version of your libpcap ?

**Comment by killdashnine** [comment]
Ok, I've narrowed it down a bit more, not seeing this on debian currently. Only on CentOS.

On CentOS 6:

Version     : 1.4.0

But seeing same issue with CentOS 7:

Version     : 1.5.3

Captagent is now running with pcap_freecode commented out, will let you know about the results

**Comment by killdashnine** [comment]
Alexandr, left it running for 26 minutes now and not seeing the 100% CPU issue. To double check I will clean the source directory and make a fresh export and see if the stock HEAD version is still having the 100% CPU.

**Comment by adubovikov** [comment]
Can you please confirm after you enable pcap_freecode you are getting 100% ?

**Comment by killdashnine** [comment]
Yes when pcap_freecode is enabled I see 100% CPU after 5-10 minutes of running.

**Comment by adubovikov** [comment]
very strange, I have tested on centos 6.... don't have any issue. Do you use VM or real HW ?

**Comment by killdashnine** [comment]
Hardware with currently 90 concurrent calls on this node. But seeing this on multiple HW machines on multiple locations with CentOS 6 and CentOS 7

**Comment by adubovikov** [comment]
ok. I have commented it out as a temporally solution. Can you please share your captagent configs ?

**Comment by adubovikov** [comment]
I think we can close the ticket

**Comment by nward** [comment]
Hi @adubovikov - we are hitting high CPU usage on 6.1.0.20, and I was looking for a way to apply a patch to resolve this to eliminate (or better, fix) this as the issue - it looks like the call to pcap_freecode hasn't been un-commented. Is it important to do so? I'm not familiar with the codebase, but, my understanding is that not calling with leave unfree-ed memory. That seems fine if it's only called a few times, but if it's called a lot that could be a problem.

If it needs to be un-commented, I'd be open to diving in a bit and figuring out what's going wrong.

**Comment by lmangani** [comment]
@nward latest version is 6.2 which should be completely unaffected, any blockers upgrading?

**Comment by nward** [comment]
I don't have a problem with that at all - but I don't see a tag or a release on here. Is it elsewhere?

**Comment by lmangani** [comment]
It's the very master. Compiling the latest codebase should get you a 6.2 - In case of issues happy to help, unless @adubovikov wants to do otherwise

**Comment by nward** [comment]
Ah, I see 6.2.11 Debian packages checked in as binary etc. but I don't see any way to see which commit those builds are compiled against.

Perhaps we can get a tag each release, so we can track them? Release tarballs would be an additional nice to have, but not important.
Are release commits tracked somewhere I'm not seeing? I'd like to build to specific "release" commits, rather than whatever the latest master is.

**Comment by nward** [comment]
Ha ha you beat me to it! It would be amazing if we had these tags/tarballs going forward. Cheers for sorting that so fast!
