### ISSUE TITLE
HEP TCP Socket Failure on AWS ELB

### ISSUE THREAD

**Issue by johnpaullarsen** [sipcapture/captagent#71]
Hi, 

I think captagent has a problem with not closing HEP TCP connections cleanly...

We're hoping to use captagent to mirror SIP from an SBC running in AWS to a fraud detection application running on another AWS host. The HEP3 connection from the captagent to our application will use Elastic Load Balancer in TCP mode.

While testing this configuration, I've noticed that if the load balancer closes the TCP connection to captagent, then captagent gets into a state where it can no longer send HEP packets, it continually gets SIGPIPE whenever it attempts to send a packet. It seems that captagent has not responded correctly to the FIN from the load balancer and believes the connection is still valid. The following is printed to the console each time it attempts to send a packet:

[ERR] transport_hep.c:895 SIGPIPE... trying to reconnect...
[ERR] transport_hep.c:658 HEP send error.

The load balancer has an idle timeout that causes it to close the connection if nothing is sent for 60 seconds. Unfortunately extended idle periods are likely with our application.

Any guidance or help with the issue would be much appreciated. I can provide a pcap file if required

**Comment by adubovikov** [comment]
you can decrease the reconnect error:
https://github.com/sipcapture/captagent/blob/master/src/modules/transport/hep/transport_hep.c#L488

**Comment by lmangani** [comment]
I'm curious @johnpaullarsen is the "other" application a project you can name?

**Comment by johnpaullarsen** [comment]
It appears that the captagent socket remains in CLOSE_WAIT for a long time (15min), and that its just swallowing HEP packets during that time. I can reproduce the problem using nc rather than the load balancer:

On monitoring host: nc -kl 9200
start captagent (HEP tcp to 9200 on monitoring host)
Send 1 call. HEP output appears on nc console
Stop nc and wait > 60sec
nc -kl 9200
Send more calls, now nothing appears on nc console
netstat -not on captagent host shows socket in CLOSE_WAIT. It remains in CLOSE_WAIT for 15 mins or more
Eventually CLOSE_WAIT times out, then calls will be sent via HEP and appear in nc

I tried setting so_reuseaddr and so_linger, but it didn't seem to help.

The product is Tollshield, we generally install a physical probe, and port mirror from the switch to the probe, but we're currently looking for a way to "soft mirror" for AWS based SBCs.

**Comment by adubovikov** [comment]
the last version of captagent has libuv TCP implementation. Please re-check

**Comment by adubovikov** [comment]
I close the ticket, please reopen if you will have some update.
