### ISSUE TITLE
debian8 / make problem

### ISSUE THREAD

**Issue by Rico29** [sipcapture/captagent#72]
Hello,
Trying to compile captagent6 with : 
```
make clean && make distclean && ./build.sh
/configure --enable-ssl --enable-compression
```

result seems OK : 
```
captagent 6.1.0.20
Build directory............. :
Installation prefix......... : /usr/local/captagent
HEP Compression............. : yes
HEP SSL/TLS................. : yes
Flex........................ : flex
Bison....................... : bison -y

Build with REDIS............ : no
Build with MySQL............ : no
Build with PCRE............. : no
Build with LibUV............ : no
```

But when running make, I get errors about SSL stuff : 
```
In file included from captagent.c:46:0:
../include/captagent/modules_api.h:188:3: error: unknown type name ‘SSL’
   SSL *ssl;
   ^
../include/captagent/modules_api.h:189:3: error: unknown type name ‘SSL_CTX’
   SSL_CTX *ctx;
   ^
```

Any idea about that ?

Compiling without  "--enable-ssl --enable-compression" seem to work fine.
Regards,
Cédric

**Comment by lmangani** [comment]
Hi @Rico29 

Wiki extended to cover the requirements: https://github.com/sipcapture/captagent/wiki/Installation

**Comment by Rico29** [comment]
Hi,
I've already follow that.

```
root@#:/usr/src/captagent# apt-get -y install openssl libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version.
openssl is already the newest version.
openssl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.


root@#:/usr/src/captagent# ./configure --enable-ssl --silent && make

captagent 6.1.0.20

Build directory............. :
Installation prefix......... : /usr/local/captagent
HEP Compression............. : no
HEP SSL/TLS................. : yes
Flex........................ : flex
Bison....................... : bison -y

Build with REDIS............ : no
Build with MySQL............ : no
Build with PCRE............. : no
Build with LibUV............ : no

Making all in src
make[1]: Entering directory '/usr/src/captagent/src'
make  all-recursive
make[2]: Entering directory '/usr/src/captagent/src'
Making all in .
make[3]: Entering directory '/usr/src/captagent/src'
gcc -DHAVE_CONFIG_H -I.  -DSYSCONFDIR='"/usr/local/captagent/etc"' -I../include  -g -fPIC -rdynamic -I../include -g -O2 -MT captagent.o -MD -MP -MF .deps/captagent.Tpo -c -o captagent.o captagent.c
In file included from captagent.c:46:0:
../include/captagent/modules_api.h:188:3: error: unknown type name ‘SSL’
   SSL *ssl;
   ^
../include/captagent/modules_api.h:189:3: error: unknown type name ‘SSL_CTX’
   SSL_CTX *ctx;
   ^
Makefile:586: recipe for target 'captagent.o' failed
make[3]: *** [captagent.o] Error 1
make[3]: Leaving directory '/usr/src/captagent/src'
Makefile:646: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/captagent/src'
Makefile:463: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/captagent/src'
Makefile:448: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```



Regards

**Comment by iamninjabob** [comment]
Hi there. I've been having the same issue working on a Raspberry Pi v3. Here is what I am seeing. Same with Rico I was following the guide you linked. 

If I do not enable SSL the make && make install run with out error.

## comands from my terminal:
 mkdir /usr/src/libuv
cd /usr/src/libuv
 wget http://ftp.us.debian.org/debian/pool/main/libu/libuv/libuv0.10_0.10.28-6_armhf.deb
 wget http://ftp.us.debian.org/debian/pool/main/libu/libuv/libuv0.10-dev_0.10.28-6_armhf.deb
 dpkg -i libuv0.10_0.10.28-6_armhf.deb
 dpkg -i libuv0.10-dev_0.10.28-6_armhf.deb
apt-get update
apt-get install -f libexpat-dev libpcap-dev m4 autoconf chkconfig libjson0-dev libtool automake flex bison libuv-dev chkconfig openssl libssl-dev -y
cd /usr/src
 git clone https://github.com/sipcapture/captagent.git captagent
cd captagent
 ./build.sh
 ./configure --enable-ssl --enable-compression 
 make && make install

and I get the following response:

Making all in src
make[1]: Entering directory '/usr/src/captagent/src'
make  all-recursive
make[2]: Entering directory '/usr/src/captagent/src'
Making all in .
make[3]: Entering directory '/usr/src/captagent/src'
gcc -DHAVE_CONFIG_H -I.  -DSYSCONFDIR='"/usr/local/captagent/etc"' -I../include  -g -fPIC -rdynamic -I../include -g -O2 -MT captagent.o -MD -MP -MF .deps/captagent.Tpo -c -o captagent.o captagent.c
In file included from captagent.c:46:0:
../include/captagent/modules_api.h:188:3: error: unknown type name ‘SSL’
   SSL *ssl;
   ^
../include/captagent/modules_api.h:189:3: error: unknown type name ‘SSL_CTX’
   SSL_CTX *ctx;
   ^
Makefile:621: recipe for target 'captagent.o' failed
make[3]: *** [captagent.o] Error 1
make[3]: Leaving directory '/usr/src/captagent/src'
Makefile:702: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/captagent/src'
Makefile:494: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/captagent/src'
Makefile:443: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

I hope this helps!

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/412b412016509e7d59f31cdb530dae68a5e09940
