### ISSUE TITLE
Using & in pcap filter generates invalid filter 

### ISSUE THREAD

**Issue by SipSeb** [sipcapture/captagent#78]
The sample captagent.xml says:

```
                        ((ip[6:2] &amp; 0x3fff != 0) - syntax for REASM packets
```

But when inserting this as filter value in socket_pcap.xml, you get this error after reloading:

```
[ERR] socket_pcap.c:549 Failed to compile filter " 0x3fff != 0)": syntax error
```

It discards everything left of the &amp; and takes the right side of it as the filter, which is - of course - invalid.
I inserted some logging into socket_pcap.c to print out all settings at the moment when they are read. And from what I see, the value is already given back like that from the xml_get function. 

That's basically where my C skills end.

Looks like there is a bug in the xml settings reader.

**Comment by adubovikov** [comment]
did you test the last git ?

**Comment by SipSeb** [comment]
Sorry, got to testing the latest commit (from September 28) only now. But it looks no different. My filter looks like this:
```
<param name="filter">
    <value>(port 5060 and (host 172.20.21.3 or not net 172.20.21.0/24)) or (ip[6:2] &amp; 0x3fff != 0)</value>
</param>
```

And when starting captagent, I get:

```
@4000000057f798b5046deb34 [NOTICE] Loaded core config
@4000000057f798b504ed9ab4 [ERR] socket_pcap.c:553 Failed to compile filter " 0x3fff != 0)": syntax error
```

**Comment by adubovikov** [comment]
You should not add reassembly filter in the filter tag, just activate the
params for it. Check my patch.

**Comment by adubovikov** [comment]
ipv6fragments = true

https://github.com/sipcapture/captagent/commit/a53e1c64e92ae1737175c03a8d2a7d7f87754aab

**Comment by SipSeb** [comment]
@adubovikov are you there? Haven't heard of my pull request, but I can confirm that our customer support is much happier now because they see a lot more packets. Some are still cut off after the first fragment but at least they are there.

**Comment by adubovikov** [comment]
sorry ;-) didn't see it!

done!

**Comment by adubovikov** [comment]
and thank you! :-)
