### ISSUE TITLE
Documentation for filter parameter in config is wrong

### ISSUE THREAD

**Issue by cgarciaarano** [sipcapture/captagent#8]
Hi, 

we've just deployed last version,
```
git log -1
commit 9f4b04fe9ad1b6a0b158c55fbc2bdda39161d301
Author: Alexandr Dubovikov <alexandr.dubovikov@gmail.com>
Date:   Wed Mar 25 12:55:38 2015 +0100

    added debug version
```

 and trying to filter out a host with this configuration, as explained in the config template:

```
<configuration name="proto_uni.conf" description="UNI Proto Basic capture">
  <settings>
        ...
       <param name="filter" value="not host HOSTNAME"/>
```

we've noticed that doesn't work. We have prefixed the filter with and `and`, and it's working ok. 

```
<configuration name="proto_uni.conf" description="UNI Proto Basic capture">
  <settings>
        ...
       <param name="filter" value="and not host HOSTNAME"/>
```
Please, fix the configuration template.

Regards

**Comment by lmangani** [comment]
Enhancement implemented in https://github.com/sipcapture/captagent/commit/519b404dda7dcabe2a60b6aac5e89528eeee6a81
