### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by andycol** [sipcapture/captagent#80]
Hi Guys

every now and then the below error spits out on the captagent server

WARNING: too many recursive routing table lookups (11) giving up!

**Comment by adubovikov** [comment]
Hi Andycol,

can you share your captagent's version and configs ?

Wbr,
Alexandr

**Comment by andycol** [comment]
Hi Alexandr

we are using the latest version of captagent

captagent.xml
https://pastebin.freeswitch.org/view/55ae779d

transport_hep.xml
https://pastebin.freeswitch.org/view/ac8d43c6

socket_pcap.xml
https://pastebin.freeswitch.org/view/937a88ef

rtcp_capture_plan.cfg
https://pastebin.freeswitch.org/view/a44e9f3c

**Comment by adubovikov** [comment]
Are you sure about the latest ? I recommend take the last git and recompile.

also I don't see the sip_capture_plan

Wbr,
Alexandr

**Comment by andycol** [comment]
if i do that will it change anything on my configs?
see sip_capture_plan
https://pastebin.freeswitch.org/view/4725bf94

**Comment by adubovikov** [comment]
so, as I see the configs are not actual as well. Specially check the
socket_pcap.xml, filter section for RTCP

**Comment by andycol** [comment]
what do you mean?

**Comment by adubovikov** [comment]
I mean the filter param for RTCP socket in the socket_pcap.xml

https://github.com/sipcapture/captagent/blob/master/conf/socket_pcap.xml#L28

**Comment by andycol** [comment]
will that not overlap with the sip ports?
i changed it to 10000-2000 as that is the rtp ports we use

**Comment by adubovikov** [comment]
you have to add the lenght size check

**Comment by andycol** [comment]
ok i will add it 
should i still get latest git and recompile?

**Comment by andycol** [comment]
still getting WARNING: too many recursive routing table lookups (11) giving up!

**Comment by adubovikov** [comment]
can you disable RTCP socket and test again ?

also, please provide  ldd result of the transport_hep.so module

**Comment by andycol** [comment]
when i disable the rtp socket it works fine
can u explain what you mean for ldd results of transport hep module

**Comment by adubovikov** [comment]
ldd /path/to/you/transport_hep.so

**Comment by andycol** [comment]
not a dynamic executable

**Comment by adubovikov** [comment]
are u sure that you installed the captagent correct ? I am not

i.e. my output

ldd /usr/local/captagent/lib/captagent/modules/transport_hep.so 

	linux-vdso.so.1 (0x00007ffcbe54c000)
	libuv.so.0.10 => /usr/lib/x86_64-linux-gnu/libuv.so.0.10 (0x00007fb41a16b000)
	libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007fb419f2b000)
....

**Comment by andycol** [comment]
yes i did the following
./build.sh
./configure
make
make installl

**Comment by andycol** [comment]
sorry send you wrong file
mine shows

linux-vdso.so.1 (0x00007ffe16bd6000)
        libuv.so.0.10 => /usr/lib/x86_64-linux-gnu/libuv.so.0.10 (0x00007fd74ee77000)
        libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007fd74ec37000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fd74ea0e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd74e80a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd74e5ed000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd74e242000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd74df41000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd74dd39000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd74f29f000)

**Comment by adubovikov** [comment]
i recommend you first uninstall everything and do it again until you couldn't provide similar ldd output

**Comment by adubovikov** [comment]
please disable daemon mode set debug to 5 and run captagent in console.

the output share to me

**Comment by andycol** [comment]
how do u disable daemon mode?

**Comment by andycol** [comment]
now spits out
[ERR] protocol_sip.c:124 Couldnot find this call
other error is gone

**Comment by adubovikov** [comment]
this is ok, because these rtcp packets are for already established connections. So, please disable debug to 1 and run captagetn one more time

**Comment by andycol** [comment]
ok now i am not seeing the error
so do you think everything is running fine?

**Comment by adubovikov** [comment]
you should tell me :-) I don't have any access to your system, therefore I can only guess....if you see sip and rtcp messages in your DB and don't see any errors, probably all works good...

**Comment by andycol** [comment]
ok it looks all good :)


you can close this issue and i will re-open if needed

**Comment by andycol** [comment]
sorry but the error is still there

WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
