### ISSUE TITLE
WARNING: too many recursive routing table lookups (11) giving up!

### ISSUE THREAD

**Issue by andycol** [sipcapture/captagent#81]
sorry but the error is still there

WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
Hi Alexandr

still occuring and spamming the screen

WARNING: too many recursive routing table lookups (11) giving up!

WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!
WARNING: too many recursive routing table lookups (11) giving up!

**Comment by adubovikov** [comment]
can you please recheck with last version ? we have fixed some issue related table lookup

**Comment by andycol** [comment]
how do i upgrade without re-installing?

**Comment by adubovikov** [comment]
unfortunately, only re-install

**Comment by lmangani** [comment]
Hopefully this was sorted - feel free to reopen if you still experience issues & thanks for the report!
