### ISSUE TITLE
build error: pointer-trouble-at-implicit

### ISSUE THREAD

**Issue by dpocock** [sipcapture/captagent#85]
This error occurs in 2 places, it is part of the report from Debian

https://qa.debian.org/bls/packages/c/captagent.html

```
E pointer-trouble-at-implicit localapi.c:37 
E pointer-trouble-at-implicit localapi.c:48 
```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/c1cf99f33a466295c4c0e9e33c1c0d8297a6eccd

can you please recheck ?

**Comment by lmangani** [comment]
Closing, feel free to reopen if needed - Thanks!
