### ISSUE TITLE
various warnings from Debian builds

### ISSUE THREAD

**Issue by dpocock** [sipcapture/captagent#86]
https://qa.debian.org/bls/packages/c/captagent.html

I pointer-cast-size-mismatch capplan.tab.y:151 
I pointer-cast-size-mismatch capplan.tab.y:193 
I pointer-cast-size-mismatch socket_pcap.c:645 
W implicit-declaration localapi.c:41 
W implicit-declaration localapi.c:42 
W implicit-declaration localapi.c:44 
W implicit-declaration localapi.c:46 
W implicit-declaration md5.c:167 
W implicit-declaration modules.c:152 
W implicit-declaration socket_raw.c:498 
W implicit-declaration socket_raw.c:515 
W implicit-declaration socket_rtcpxr.c:215 
W implicit-declaration socket_rtcpxr.c:238 
W pointer-from-integer socket_pcap.c:863 
W pointer-from-integer socket_raw.c:751 
W pointer-from-integer socket_rtcpxr.c:442

**Comment by adubovikov** [comment]
thanks will check ASAP

**Comment by lmangani** [comment]
@kYroL01 could you check if this is still needed? thanks!

**Comment by kYroL01** [comment]
SUre, I'll check asap

**Comment by kYroL01** [comment]
The only warnings remains from this list are

> pointer-cast-size-mismatch capplan.tab.y:151
> I pointer-cast-size-mismatch capplan.tab.y:193

The other seems to be fixed.
I close the issue but investigate on these two.
If any news, please comment and report.
Thanks
