### ISSUE TITLE
Question: SIPS Capture

### ISSUE THREAD

**Issue by twmartin** [sipcapture/captagent#88]
Is it possible to capture SIPS with captagent? I've set up and configured a vanilla captagent with debug set to 10, but I seem to only receive the below sip parse errors when running the service in the foreground:

```
.
.
.
[DEBUG] captagent.c:315 The Captagent is ready
210101235959Z0��1erver@thawte.com0vision1!0UThawte Premium Server CA1(0&    *�H��
                 0  UZA10U
                             Western Cape10U    Cape Town10U
Thawte Consulting cc1(0&U
]   *�H��um-server@thawte.com0��0n Services Division1!0UThawte Premium Server CA1(0&  *�H��

[ERR] protocol_sip.c:372 bad parsing
[ERR] protocol_sip.c:353 SIP PARSE ERROR [-1]
```

**Comment by sergey-safarov** [comment]
Think this is related to https://github.com/sipcapture/captagent/issues/89

**Comment by lmangani** [comment]
Experimental TLS decryption has been added to Captagent - more details on our [wiki](https://github.com/sipcapture/captagent/wiki/TLS)
All testers welcome! Closing this old thread to make space for new ones.
