### ISSUE TITLE
capturing TLS server and client hello details, including certificates

### ISSUE THREAD

**Issue by dpocock** [sipcapture/captagent#89]
TLS connections can't be monitored with captagent, but it would be useful if the agent could monitor the client and server hello messages during the TLS protocol setup.

In particular, capture the server certificate chain and the client certificate chain and send these over HEP to the database.

In the database, it would be useful to have a table of all certificates ever seen with the following columns:
- certificate CN and subjectAltName details
- certificate (full DER or PEM)
- certificate expiry date
- certificate hash SHA256
- last time the certificate was seen in a client hello and the client IP
- last time the certificate was seen in a server hello and the server IP

as well as a table listing each TLS connection:
- the client and server IP/ports details
- ciphers offered by each side
- any vendor identifying text from the hello messages
- whether the connection was established successfully and if not, the failure code and which side issued the error
- when the connection was closed, by which side and any error code

This is probably not only useful for SIP, but also XMPP and other protocols.

**Comment by lmangani** [comment]
@dpocock a good soul is working on basic TLS support for captagent. Once the new code is available, we can start extending the tables to (optionally) also collect protocol and certificate details as suggested. 

We'll track progress in this Issue.

**Comment by kevinlong206** [comment]
@lmangani If this fine soul needs help testing, I'm up for it. I have lots of freepbx with chan_sip only,  too much of a headache to migrate to pjsip,  and all use TLS. Would love to get homer running with captagent on these. Thx

**Comment by sergey-safarov** [comment]
Think this is related to issue https://github.com/sipcapture/captagent/issues/88

**Comment by kYroL01** [comment]
Hi all.
TLS dissection is implemented. Now I'm going to finish the biggest work on certificate as @dpocock suggest asap.
Does anyone have TLS1.3 pcap to share with me for a complete work ? Thanks

**Comment by sergey-safarov** [comment]
I can try make required PCAP
What is openssl version supports of TLS1.3.?

**Comment by sergey-safarov** [comment]
Required openssl 1.1.1
I will update openssl on my testbox recompile my SIP server part and SIP client part with new openssl lib.

**Comment by sergey-safarov** [comment]
Hello Michele @kYroL01 
Required files in tls-1.3.zip
[tls-1.3.zip](https://github.com/sipcapture/captagent/files/1220443/tls-1.3.zip)

**Comment by sergey-safarov** [comment]
Used openssl commit https://github.com/openssl/openssl/commit/bdcacd93b14ed7381a922b41d74c481224ef9fa1

**Comment by kYroL01** [comment]
THanks you very much @sergey-safarov

**Comment by sergey-safarov** [comment]
My five cents on the issue of security
A private key can not be sent over the network. Only in manual load on capagent and on homer daemon.

**Comment by kYroL01** [comment]
Soon there will be update on this work. Stay tuned. Thanks to all!

**Comment by kYroL01** [comment]
In this commit I dump the certificate as a `.der` file as @dpocock said. The dissection is better now for TLS v1 and v2 and I'm working on better and exaustive dissector to extract fields requested. Feel free guys to test and tell me if something must be improved.
I think `der` file is better also to create a `.pem` file, good for _openssl_ parsing.
The certificates extracted are saved in a directory I created.

I'm working on how to properly dissect TLS v1.3 and how to extract the other fields requested.
Stay tuned and let me know if there are anything to fix or improved. Appreciate that.

**Comment by lmangani** [comment]
Experimental TLS decryption has been added to Captagent - more details on our [wiki](https://github.com/sipcapture/captagent/wiki/TLS)
All testers welcome! Closing this old thread to make space for new ones.
