### ISSUE TITLE
captagent.c:pid_file handling and default value

### ISSUE THREAD

**Issue by zecke** [sipcapture/captagent#90]
Hi,

the first observation is the "if (ptr) free(ptr)" pattern. The GNU libc man page says:

```
If ptr is NULL, no operation is performed.
```

(https://linux.die.net/man/3/free) (and FreeBSD 1.0 from 1991.. https://www.freebsd.org/cgi/man.cgi?query=free&apropos=0&sektion=0&manpath=FreeBSD+1.0-RELEASE&arch=default&format=html)

The second part is that pid_file gets initialized from a string located in .ro memory of the application and on CTRL+C the static string is freed.
- Are you okay with removing the "if()" in patches?
- I am sending a patch to remove the static initialization and use strdup to initialize it with a default if not initialized.
- There is code that checks for pid_file != NULL but it seems to be unlikely (unless strdup(optval) fails)?

**Comment by adubovikov** [comment]
Thank you,
Please make a pull request and we will accept it. 

Again, thanks
