### ISSUE TITLE
CR's at end of SIP packet captured being replaced with random data in HEP stream

### ISSUE THREAD

**Issue by dancapper** [sipcapture/captagent#96]
I am observing that for any SIP packet captured by our captagent, the HEP packet sent has the last 4 octets (which are usually carriage returns 0d 0a 0d 0a) are replaced by random data.  This is then stored in the database and shown in HOMER (in the typical use case scenario)

I'm not proficient enough in C to figure out what is causing the bug but it as if the CRs are being truncated, but that has not been factored in the length of the struct being sent in the HEP packet (so whatever random data is stored in that memory location is sent instead)

If you are unable to reproduce this I will be happy to provide additional information, it happens 100% of the time for me

**Comment by lmangani** [comment]
Hi @dancapper 
Could you kindly provide a PCAP/dump privately to support@sipcapture.org for a check?

**Comment by adubovikov** [comment]
Can you please also provide the versions of captagent and kamailio ?

thank you!

**Comment by dancapper** [comment]
Have sent captures as requested

Captagent was built from MASTER the day of the report.

**Comment by dancapper** [comment]
Apologies.  I believe Kamailio doesn't factor into the issue; the bad data exists in the HEP stream as captured.  Thanks.

**Comment by dancapper** [comment]
I think it is to do with VLAN tagging, because servers which get untagged traffic are not affected, but my server which sees the VLAN tags has the issue.  And I have noted whatever the packet contents, last 4 bytes are replaced with "junk" data

**Comment by dancapper** [comment]
Found captagent was accounting twice for the (4 byte) length of the 802.1Q VLAN Tag header when it exists.  I have submitted a pull request which appears to resolve this issue.

**Comment by lmangani** [comment]
Thanks @dancapper much appreciated!
