### ISSUE TITLE
Captagent: [ERR] protocol_sip.c:132 Couldnot find this call

### ISSUE THREAD

**Issue by tslytsly** [sipcapture/captagent#97]
Hi Guys,

I keep getting these errors in my Captagent log: `[ERR] protocol_sip.c:132 Couldnot find this call`
I have uncommented the SDP section in my `sip_capture_plan.cfg` and I have configured the `socket_pcap.xml` to capture the correct range of ports.

I think it might be because our PBX is NAT aware and is populating the SDP with the public IP.
So there is a mis-match between the SDP info and the IP headers on the packets.

Is there any way to configure the NAT'd public IP to the PBX's private IP?

Thanks

**Comment by adubovikov** [comment]
unfortunately the current version will count RTCP packets if source ip/destination ip match to IPs in SDP of the call.

**Comment by tslytsly** [comment]
Hi @adubovikov 
Thanks for the reply. 
Are there plans to add this in the furture?
We really like Homer, but most of our installations are behind NAT.
 
Is there a way to hack this in the short term please?

Thanks

**Comment by adubovikov** [comment]
you can always send request to support@sipcapture.org for a development quote.

or wait until will have a free time to add the feature, but until end of this year is unrealistic

**Comment by tslytsly** [comment]
Thanks @adubovikov 

We're not in a rush for this.

**Comment by pinchasMT** [comment]
+1
