### ISSUE TITLE
Can't Open configuration File : transport_hep.xml

### ISSUE THREAD

**Issue by Aookii** [sipcapture/captagent#98]
Hi everybody,

Im having issue configuring Captagent. After a fine installation using Makefile on debian 8 i started the service , the service is running but it show me these errors :

> nov. 24 08:32:30 fusionpbx systemd[1]: Started LSB: Start the Captagent.
> nov. 24 08:32:30 fusionpbx captagent[2173]: .
> nov. 24 08:32:30 fusionpbx captagent[2173]: [ERR] xmlread.c:170 Parse error at line [8]:[not well-formed (invalid token)]
> nov. 24 08:32:30 fusionpbx captagent[2173]: [ERR] transport_hep.c:1004 Unable to open configuration file: /usr/local/captagent/etc/captagent/transport_hep.xml

I checked the location, the file is in the right place.

Thank you.

**Comment by adubovikov** [comment]
[ERR] xmlread.c:170 Parse error *at line [8]:[*not well-formed (invalid
token)]

please check that you have at this line.

**Comment by adubovikov** [comment]
I think the issue has been fixed. Please reopen if is not
